import assert from 'node:assert/strict';
import {describe,it} from 'node:test';
import {DEFAULT_ENDINGS,createTerminalEvidence,evaluateTerminalEvidence,validateEndingDefinitions,type CollapseCause,type EndingDefinition,type TerminalEvidence} from '../src/game/domain/EndOfDayResults.ts';
import {createPacingProfile,DEVELOPER_PACING_PROFILE,WORKDAY_DURATION_MS} from '../src/game/domain/WorkdayPacing.ts';
import {WorkdaySession} from '../src/game/domain/WorkdaySession.ts';

const base=(causes:readonly CollapseCause[]=['stamina'],overrides:Partial<TerminalEvidence>={}):TerminalEvidence=>createTerminalEvidence({elapsedGameMs:WORKDAY_DURATION_MS+60_000,dayIndex:2,dayElapsedGameMs:60_000,resources:{stamina:0,poHappiness:70,systemStability:80,technicalDebt:10},needs:{sleepiness:30,toilet:30},healthRisk:0,collapseCauses:causes,causalSource:'test alert',activeInterruptionIds:['still-open'],completedTaskIds:['a','b'],resolutions:[],resolvedIncidentIds:[],criticalNeedEpisodes:{sleepiness:0,toilet:0},boosterCounts:{coffee:0,cokeZero:0},...overrides});

describe('collapse evaluation',()=>{
 it('produces an immutable ending and evidence-backed autopsy without a victory score',()=>{const result=evaluateTerminalEvidence(base());assert.equal(result.ending.id,'burnout-as-a-service');assert.equal(result.survivalLabel,'Day 2 · 09:01');assert.equal(result.autopsy.length,6);assert.match(result.autopsy.at(-1)!.value,/test alert/);assert.equal('total' in result,false);assert.throws(()=>Object.assign(result.evidence.resources,{stamina:99}));});
 it('prioritizes combined failures and distinguishes stimulant outcomes',()=>{assert.equal(evaluateTerminalEvidence(base(['stamina','firing','outage'],{resources:{stamina:0,poHappiness:0,systemStability:0,technicalDebt:90}})).ending.id,'everything-is-fine');assert.equal(evaluateTerminalEvidence(base(['health'],{healthRisk:100,boosterCounts:{coffee:4,cokeZero:0},resources:{stamina:40,poHappiness:40,systemStability:40,technicalDebt:0}})).ending.id,'cardiac-standup');assert.equal(evaluateTerminalEvidence(base(['health'],{healthRisk:100,boosterCounts:{coffee:1,cokeZero:6},resources:{stamina:40,poHappiness:40,systemStability:40,technicalDebt:0}})).ending.id,'zero-sugar-full-incident');});
 it('validates stable authored priority slots',()=>{const ending=(id:string,priority:number,order:number):EndingDefinition=>({id,title:id,narrative:id,priority,order,matches:()=>true});assert.equal(evaluateTerminalEvidence(base(),[ending('later',5,2),ending('first',5,1)]).ending.id,'first');assert.throws(()=>validateEndingDefinitions([ending('x',1,0),ending('x',0,1)]));assert.throws(()=>validateEndingDefinitions([]));assert.equal(DEFAULT_ENDINGS.length,12);});
});

describe('multi-day collapse lifecycle',()=>{
 it('continues through 17:00 with partial recovery and fresh daily workload',()=>{const quiet=createPacingProfile({...DEVELOPER_PACING_PROFILE,bands:DEVELOPER_PACING_PROFILE.bands.map(b=>({...b,minimumSpawnIntervalMs:WORKDAY_DURATION_MS*2,maximumSpawnIntervalMs:WORKDAY_DURATION_MS*2}))});const session=new WorkdaySession(quiet,42,()=>{},false);session.playerNeeds.mutateNeed('toilet',70);session.advanceGameMs(WORKDAY_DURATION_MS);assert.equal(session.lifecycle,'active');assert.equal(session.result,null);assert.equal(session.workday.snapshot.dayIndex,2);assert.equal(session.workday.snapshot.clockHour,9);assert.equal(session.playerNeeds.snapshot.toilet.value,0);assert.ok(session.workday.snapshot.resources.stamina<=75);});
 it('latches the first visible collapse and freezes later entry points',()=>{const session=new WorkdaySession(DEVELOPER_PACING_PROFILE,8,()=>{},false);session.workday.mutateResource('systemStability',-100);const result=session.finalize('production-errors')!;assert.equal(result.evidence.collapseCauses[0],'outage');assert.equal(result.evidence.causalSource,'production-errors');assert.strictEqual(session.finalize(),result);const before=structuredClone(result);session.advanceGameMs(60_000);assert.deepEqual(result,before);assert.deepEqual(session.legalActions(),[]);});
 it('uses cumulative stimulant risk as a hidden terminal channel',()=>{const session=new WorkdaySession(DEVELOPER_PACING_PROFILE,7,()=>{},false);for(let i=0;i<5;i++){session.boosters.synchronize({elapsedGameMs:i*2_000_000,stamina:10,isDecisionOpen:false,isDayComplete:false});session.boosters.activate('coffee',{elapsedGameMs:i*2_000_000,stamina:10,isDecisionOpen:false,isDayComplete:false});}assert.ok(session.healthRisk>=100);assert.equal(session.finalize('coffee overuse')?.evidence.collapseCauses[0],'health');});
});
