import assert from 'node:assert/strict';
import {describe,it} from 'node:test';
import {DEFAULT_ENDINGS,DEFAULT_SCORING_CONFIG,SCORE_CATEGORY_IDS,createTerminalEvidence,evaluateTerminalEvidence,validateEndingDefinitions,validateScoringConfig,type EndingDefinition,type TerminalEvidence} from '../src/game/domain/EndOfDayResults.ts';
import {DEVELOPER_PACING_PROFILE,WORKDAY_DURATION_MS} from '../src/game/domain/WorkdayPacing.ts';
import {WorkdaySession} from '../src/game/domain/WorkdaySession.ts';

const base=(overrides:Partial<TerminalEvidence>={}):TerminalEvidence=>createTerminalEvidence({elapsedGameMs:WORKDAY_DURATION_MS,resources:{stamina:60,poHappiness:70,systemStability:80,technicalDebt:10},needs:{sleepiness:30,toilet:30},completedTaskIds:['a','b'],resolutions:[],resolvedIncidentIds:[],criticalNeedEpisodes:{sleepiness:0,toilet:0},boosterCounts:{coffee:0,cokeZero:0},...overrides});
describe('end-of-day evaluation',()=>{
 it('covers every bounded explainable category and deeply freezes output',()=>{const input=base({resources:{stamina:0,poHappiness:100,systemStability:100,technicalDebt:100},needs:{sleepiness:100,toilet:100},completedTaskIds:['a','b','c','d','e','f'],resolutions:[{eventId:'t',choiceId:'c',category:'teammate',resultKarma:'constructive'}],resolvedIncidentIds:['i1','i2','i3','i4'],boosterCounts:{coffee:4,cokeZero:3}});const result=evaluateTerminalEvidence(input);assert.deepEqual(result.scoreLines.map(x=>x.id),SCORE_CATEGORY_IDS);assert.ok(result.total>=result.minimumTotal&&result.total<=result.maximumTotal);for(const line of result.scoreLines)assert.ok(line.contribution>=line.minimum&&line.contribution<=line.maximum);assert.match(result.scoreLines.find(x=>x.id==='boosters')!.evidence,/Coffee 4 · Coke Zero 3/);assert.match(result.scoreLines.find(x=>x.id==='catastrophes')!.evidence,/stamina/);assert.throws(()=>Object.assign(result.evidence.resources,{stamina:99}));});
 it('is deterministic and selects all seven reachable endings',()=>{const fixtures:Record<string,TerminalEvidence>={
  'staff-engineer':base(),
  '10x-engineer':base({completedTaskIds:['a','b','c','d'],resources:{stamina:10,poHappiness:60,systemStability:60,technicalDebt:40}}),
  'incident-commander':base({resolvedIncidentIds:['a','b','c']}),
  'promoted-to-management':base({resources:{stamina:60,poHappiness:95,systemStability:70,technicalDebt:5},resolutions:[{eventId:'a',choiceId:'a',category:'teammate',resultKarma:'constructive'},{eventId:'b',choiceId:'b',category:'teammate',resultKarma:'constructive'}]}),
  'the-transcendent':base({completedTaskIds:['a','b','c'],boosterCounts:{coffee:2,cokeZero:2}}),
  'biological-incident':base({needs:{sleepiness:40,toilet:95}}),
  'unicorn-day':base({resources:{stamina:100,poHappiness:100,systemStability:100,technicalDebt:0},needs:{sleepiness:0,toilet:0},completedTaskIds:['a','b','c','d','e']})};
  for(const [id,evidence] of Object.entries(fixtures)){const a=evaluateTerminalEvidence(evidence),b=evaluateTerminalEvidence(evidence);assert.equal(a.ending.id,id);assert.deepEqual(a,b);}
 });
 it('uses priority then declaration order and rejects malformed configuration',()=>{const ending=(id:string,priority:number,order:number,fallback=false):EndingDefinition=>({id,title:id,narrative:id,priority,order,fallback,matches:()=>true});assert.equal(evaluateTerminalEvidence(base(),DEFAULT_SCORING_CONFIG,[ending('later',5,2),ending('first',5,1),ending('fallback',0,3,true)]).ending.id,'first');assert.throws(()=>validateScoringConfig({...DEFAULT_SCORING_CONFIG,rules:DEFAULT_SCORING_CONFIG.rules.slice(1)}));assert.throws(()=>validateScoringConfig({...DEFAULT_SCORING_CONFIG,maximumTotal:Number.NaN}));assert.throws(()=>validateEndingDefinitions([ending('x',1,0),ending('x',0,1,true)]));assert.throws(()=>validateEndingDefinitions(DEFAULT_ENDINGS.filter(x=>!x.fallback)));assert.throws(()=>validateEndingDefinitions([{...ending('never',2,0),matches:()=>false},ending('fallback',0,1,true)]),/unreachable/);});
});
describe('terminal session lifecycle',()=>{
 it('finalizes exactly once at 17:00, freezes all later entry points, and resets fresh',()=>{const session=new WorkdaySession(DEVELOPER_PACING_PROFILE,42);session.advanceGameMs(WORKDAY_DURATION_MS);const result=session.finalize()!;assert.equal(session.lifecycle,'results');assert.equal(result.evidence.elapsedGameMs,WORKDAY_DURATION_MS);assert.strictEqual(session.finalize(),result);const before=structuredClone(result);session.advanceGameMs(60_000);session.advanceRealMs(1000);assert.deepEqual(result,before);assert.deepEqual(session.legalActions(),[]);session.reset();assert.equal(session.lifecycle,'active');assert.equal(session.result,null);assert.equal(session.workday.snapshot.elapsedGameMs,0);});
 it('captures resolved scoring facts once without aliases',()=>{const session=new WorkdaySession(DEVELOPER_PACING_PROFILE,7);session.interruptions.activate('team-review-request');session.interruptions.open('team-review-request');const p=session.interruptions.beginResolution('review-carefully')!;session.interruptions.finalizeResolution(p.interruptionId);assert.equal(session.interruptions.finalizeResolution(p.interruptionId),false);session.advanceGameMs(WORKDAY_DURATION_MS);const result=session.finalize()!;assert.equal(result.evidence.resolutions.filter(x=>x.eventId==='team-review-request').length,1);assert.equal(result.evidence.resolutions[0]?.resultKarma,'constructive');session.reset();assert.equal(result.evidence.resolutions.length,1);});
 it('finishes an accepted terminal action before capture and preserves recoverable zero resources',()=>{const session=new WorkdaySession(DEVELOPER_PACING_PROFILE,8);session.workday.mutateResource('systemStability',-75);assert.equal(session.lifecycle,'active');session.workday.mutateResource('systemStability',20);session.workday.spendGameMinutes(479);session.interruptions.activate('production-errors',session.workday.snapshot.elapsedGameMs);session.interruptions.open('production-errors');session.workday.pause('interruption-decision');session.perform({type:'resolve-interruption',interruptionId:'production-errors',choiceId:'rollback'});assert.ok(session.result!.evidence.resources.systemStability>0);assert.ok(session.result?.evidence.resolvedIncidentIds.includes('production-errors'));});
});
