import assert from 'node:assert/strict';
import { describe,it } from 'node:test';
import { ENGINEERING_TASKS } from '../src/game/content/engineeringTasks.ts';
import { INTERRUPTION_CATALOG } from '../src/game/content/poTeamInterruptions.ts';
import { CONSEQUENCE_INTERRUPTION_PACK, PERSONAL_INTERRUPTION_PACK, auditPersonalAndConsequenceCatalog } from '../src/game/content/personalConsequenceInterruptions.ts';
import { DEFAULT_DAY_STATE_CONFIG } from '../src/game/domain/DayState.ts';
import { EventScheduler, type RandomSource } from '../src/game/domain/EventScheduler.ts';
import { InterruptionSession, createRunContext, matchesEligibility, validateInterruptionCatalog, validateInterruptionDefinitions, type InterruptionDefinition } from '../src/game/domain/interruptions.ts';

const ctx=(extra:Parameters<typeof createRunContext>[0] extends infer T?Partial<T>:never={})=>createRunContext({selectedTaskId:null,completedTaskIds:[],resolvedEventIds:[],resolvedChoices:[],resources:DEFAULT_DAY_STATE_CONFIG.initialResources,...extra});
describe('personal and consequence contracts',()=>{
 it('assembles and audits the exact 30-event six-category MVP catalog',()=>{auditPersonalAndConsequenceCatalog(INTERRUPTION_CATALOG,ENGINEERING_TASKS.map(x=>x.id));assert.equal(INTERRUPTION_CATALOG.length,30);assert.deepEqual([...new Set(INTERRUPTION_CATALOG.map(x=>x.category))].sort(),['consequence','personal','product-owner','production','teammate','tooling']);assert.equal(PERSONAL_INTERRUPTION_PACK.length,4);assert.equal(CONSEQUENCE_INTERRUPTION_PACK.length,5);});
 it('uses immutable contextual facts for every new predicate',()=>{const context=ctx({needStages:{sleepiness:2,toilet:3},boosterCounts:{coffee:3,cokeZero:1},incidentCounts:{'production-errors':2},concludedConsequenceIds:['deploy-retry-risk']});assert.ok(Object.isFrozen(context.needStages));assert.ok(matchesEligibility({type:'need-stage',need:'toilet',minimumStage:2},context));assert.ok(matchesEligibility({type:'booster-count',booster:'coffee',minimumCount:3},context));assert.ok(matchesEligibility({type:'incident-count',incidentId:'production-errors',minimumCount:2},context));assert.ok(matchesEligibility({type:'concluded-consequence',consequenceId:'deploy-retry-risk'},context));assert.equal(matchesEligibility({type:'need-stage',need:'sleepiness',minimumStage:3},context),false);});
 it('makes warnings reachable at threshold and suppressible after relief',()=>{const sleep=PERSONAL_INTERRUPTION_PACK[0]!,toilet=PERSONAL_INTERRUPTION_PACK[1]!;assert.ok(matchesEligibility(sleep.eligibility,ctx({needStages:{sleepiness:2,toilet:0}})));assert.equal(matchesEligibility(sleep.eligibility,ctx({needStages:{sleepiness:1,toilet:0}})),false);const session=new InterruptionSession([toilet]);session.activate(toilet.id);assert.deepEqual(session.dismissStale(ctx({needStages:{sleepiness:0,toilet:0}})),[toilet.id]);assert.equal(session.snapshot.active.length,0);});
 it('rejects malformed categories, facts, provenance, references and cooldown metadata',()=>{const valid=PERSONAL_INTERRUPTION_PACK[0]!;const reject=(item:InterruptionDefinition)=>assert.throws(()=>validateInterruptionDefinitions([item]));reject({...valid,category:'later' as never});reject({...valid,eligibility:{type:'need-stage',need:'sleepiness',minimumStage:-1}});reject({...valid,deduplicationKey:'Bad Key'});reject({...valid,cooldownGameMs:9*60*60_000});reject({...valid,deduplicationKey:undefined,cooldownGameMs:1});reject({...CONSEQUENCE_INTERRUPTION_PACK[0]!,cause:undefined});assert.throws(()=>validateInterruptionCatalog([...INTERRUPTION_CATALOG.filter(x=>x.id!=='consequence-deploy-retry'),{...CONSEQUENCE_INTERRUPTION_PACK[4]!,cause:{type:'concluded-consequence',consequenceId:'unknown'}}],ENGINEERING_TASKS.map(x=>x.id)));});
 it('rejects conflicting equivalence metadata and equivalent choice signatures',()=>{const a=PERSONAL_INTERRUPTION_PACK[0]!,b=PERSONAL_INTERRUPTION_PACK[1]!;assert.throws(()=>validateInterruptionDefinitions([a,{...b,deduplicationKey:a.deduplicationKey,cooldownGameMs:1}]));const malformed=[...INTERRUPTION_CATALOG.slice(0,-1),{...INTERRUPTION_CATALOG.at(-1)!,choices:[INTERRUPTION_CATALOG.at(-1)!.choices[0]!,INTERRUPTION_CATALOG.at(-1)!.choices[0]!]}];assert.throws(()=>auditPersonalAndConsequenceCatalog(malformed,ENGINEERING_TASKS.map(x=>x.id)));});
});

describe('deduplication and authoritative cooldown scheduling',()=>{
 const definitions=PERSONAL_INTERRUPTION_PACK.slice(0,2);const config={minimumSpawnIntervalMs:10,maximumSpawnIntervalMs:10,activeLimit:2,endGameMs:100};
 it('filters active equivalents before a single weighted draw',()=>{let draws=0;const random:RandomSource={next:()=>{draws++;return 0;},reset:()=>{draws=0;}};const scheduler=new EventScheduler(definitions,config,1,random);const context=ctx({needStages:{sleepiness:2,toilet:2},activeDeduplicationKeys:['need-sleepiness'],currentGameMs:10});const out=scheduler.synchronize(10,()=>true,context);assert.equal(out[0]?.definitionId,'personal-bathroom-warning');assert.equal(draws,3);});
 it('starts cooldown on handling, freezes without game-time movement, expires, and resets',()=>{const event=definitions[0]!;const session=new InterruptionSession([event]);assert.ok(session.activate(event.id,10));session.setCurrentGameMs(10);session.open(event.id);session.beginResolution(event.choices[0]!.id);session.finalizeResolution(event.id);const deadline=session.snapshot.cooldownUntilGameMs[event.deduplicationKey!]!;assert.equal(session.activate(event.id,deadline-1),false);assert.equal(session.activate(event.id,deadline),true);session.reset();assert.deepEqual(session.snapshot.cooldownUntilGameMs,{});assert.equal(session.snapshot.resolvedOutcomes.length,0);});
 it('replays a seeded accelerated scheduler run across all six categories',()=>{const run=()=>{const scheduler=new EventScheduler(INTERRUPTION_CATALOG,{minimumSpawnIntervalMs:1,maximumSpawnIntervalMs:1,activeLimit:30,endGameMs:80},20260906);const context=ctx({selectedTaskId:'TASK-3178',needStages:{sleepiness:2,toilet:2},boosterCounts:{coffee:3,cokeZero:1},resolvedEventIds:['po-scope-request','team-review-request'],resolvedChoices:[{eventId:'po-scope-request',choiceId:'accept-scope'},{eventId:'team-review-request',choiceId:'quick-approve'}],incidentCounts:{'production-errors':2},concludedConsequenceIds:['deploy-retry-risk'],currentGameMs:60});return scheduler.synchronize(60,()=>true,context).map(candidate=>candidate.definitionId);};const first=run(),second=run();assert.deepEqual(first,second);const categories=new Set(first.map(id=>INTERRUPTION_CATALOG.find(item=>item.id===id)!.category));assert.deepEqual([...categories].sort(),['consequence','personal','product-owner','production','teammate','tooling']);assert.equal(new Set(first).size,first.length);});
});
