import assert from 'node:assert/strict';
import { describe,it } from 'node:test';
import { ENGINEERING_TASKS } from '../src/game/content/engineeringTasks.ts';
import { INTERRUPTION_CATALOG,PO_AND_TEAM_INTERRUPTION_PACK,auditPoAndTeamCatalog } from '../src/game/content/poTeamInterruptions.ts';
import { EventScheduler,evaluateWeight,type RandomSource } from '../src/game/domain/EventScheduler.ts';
import { InterruptionSession,createRunContext,matchesEligibility,validateInterruptionCatalog,type InterruptionDefinition } from '../src/game/domain/interruptions.ts';
import { DEFAULT_DAY_STATE_CONFIG } from '../src/game/domain/DayState.ts';
const ctx=(overrides:Partial<Parameters<typeof createRunContext>[0]>={})=>createRunContext({selectedTaskId:null,completedTaskIds:[],resolvedEventIds:[],resolvedChoices:[],resources:DEFAULT_DAY_STATE_CONFIG.initialResources,...overrides});
describe('PO and team eligibility and catalog',()=>{
 it('matches task, event, choice, all and any predicates from immutable snapshots',()=>{const context=ctx({selectedTaskId:'TASK-3178',completedTaskIds:['BUG-4821'],resolvedEventIds:['po-scope-request'],resolvedChoices:[{eventId:'po-scope-request',choiceId:'accept-scope'}]});assert.ok(Object.isFrozen(context));assert.ok(Object.isFrozen(context.resolvedChoices));assert.equal(matchesEligibility({all:[{type:'selected-task',taskId:'TASK-3178'},{any:[{type:'completed-task',taskId:'BUG-4821'},{type:'resolved-event',eventId:'missing'}]},{type:'resolved-choice',eventId:'po-scope-request',choiceId:'accept-scope'}]},context),true);assert.equal(matchesEligibility(undefined,context),true);});
 it('audits exact totals, topics, reachability, choices, escalation and excluded packs',()=>{auditPoAndTeamCatalog(ENGINEERING_TASKS.map(item=>item.id));assert.equal(PO_AND_TEAM_INTERRUPTION_PACK.filter(item=>item.category==='product-owner').length,6);assert.equal(PO_AND_TEAM_INTERRUPTION_PACK.filter(item=>item.category==='teammate').length,5);assert.deepEqual(new Set(PO_AND_TEAM_INTERRUPTION_PACK.map(item=>item.category)),new Set(['product-owner','teammate']));});
 it('rejects malformed predicates and invalid cross references before scheduling',()=>{const valid=PO_AND_TEAM_INTERRUPTION_PACK[0]!;assert.throws(()=>validateInterruptionCatalog([{...valid,eligibility:{all:[]}}],ENGINEERING_TASKS.map(item=>item.id)),TypeError);assert.throws(()=>validateInterruptionCatalog([{...valid,eligibility:{type:'selected-task',taskId:'NOPE'}}],ENGINEERING_TASKS.map(item=>item.id)),TypeError);assert.throws(()=>validateInterruptionCatalog([{...valid,eligibility:{type:'resolved-choice',eventId:valid.id,choiceId:'NOPE'}}],ENGINEERING_TASKS.map(item=>item.id)),TypeError);assert.throws(()=>validateInterruptionCatalog([{...valid,choices:[valid.choices[0]!]}],ENGINEERING_TASKS.map(item=>item.id)),TypeError);assert.throws(()=>validateInterruptionCatalog([{...valid,choices:[{...valid.choices[0]!,effects:[{type:'resource',resource:'bad',amount:1} as never]},valid.choices[1]!]}],ENGINEERING_TASKS.map(item=>item.id)),TypeError);assert.throws(()=>validateInterruptionCatalog([{...valid,escalationStages:[{...valid.escalationStages![0]!,followUpIds:['missing']}]}],ENGINEERING_TASKS.map(item=>item.id)),TypeError);});
 it('records immutable outcomes exactly once and resets deterministically',()=>{const session=new InterruptionSession(INTERRUPTION_CATALOG);session.activate('po-scope-request');session.open('po-scope-request');session.beginResolution('accept-scope');assert.equal(session.finalizeResolution('po-scope-request'),true);assert.equal(session.finalizeResolution('po-scope-request'),false);assert.deepEqual(session.snapshot.resolvedOutcomes,[{eventId:'po-scope-request',choiceId:'accept-scope'}]);assert.ok(Object.isFrozen(session.snapshot.resolvedOutcomes[0]));session.reset();assert.deepEqual(session.snapshot.resolvedIds,[]);assert.deepEqual(session.snapshot.resolvedOutcomes,[]);});
});
describe('context-aware weighting and scheduling',()=>{
 it('bounds low-PO pressure and leaves teammate weights unchanged and positive',()=>{const po=PO_AND_TEAM_INTERRUPTION_PACK.find(item=>item.id==='po-demo-request')!;const team=PO_AND_TEAM_INTERRUPTION_PACK.find(item=>item.id==='team-review-request')!;const high=ctx({resources:{...DEFAULT_DAY_STATE_CONFIG.initialResources,poHappiness:75}});const low=ctx({resources:{...DEFAULT_DAY_STATE_CONFIG.initialResources,poHappiness:0}});assert.ok(evaluateWeight(po,low)>evaluateWeight(po,high));assert.equal(evaluateWeight(po,low),1.65);assert.equal(evaluateWeight(team,low),evaluateWeight(team,high));assert.ok(evaluateWeight(team,low)>0);});
 it('filters ineligible definitions, survives empty pools, replays context history, and never reweights queued identities',()=>{const config={minimumSpawnIntervalMs:10,maximumSpawnIntervalMs:10,activeLimit:1,endGameMs:50};const random=():RandomSource=>({next:()=>.5,reset:()=>{}});const definitions:InterruptionDefinition[]=[{...PO_AND_TEAM_INTERRUPTION_PACK[0]!,id:'conditional',eligibility:{type:'selected-task',taskId:'TASK-3178'}},{...PO_AND_TEAM_INTERRUPTION_PACK[7]!,id:'fallback'}];const run=()=>{const s=new EventScheduler(definitions,config,1,random());const out:string[]=[];s.synchronize(20,x=>{out.push(x.definitionId);return true;},ctx({selectedTaskId:'TASK-3178'}));return out;};assert.deepEqual(run(),run());const empty=new EventScheduler([{...definitions[0]!,baseWeight:1}],config,1,random());assert.deepEqual(empty.synchronize(10,()=>true,ctx()),[]);assert.ok(empty.snapshot.nextSpawnGameMs!==null);const queued=new EventScheduler(definitions,config,1,random());queued.synchronize(20,()=>true,ctx({selectedTaskId:'TASK-3178'}));const before=queued.snapshot.pending[0];queued.synchronize(30,()=>true,ctx({resources:{...DEFAULT_DAY_STATE_CONFIG.initialResources,poHappiness:0}}));assert.deepEqual(queued.snapshot.pending.find(item=>item.sequence===before?.sequence),before);});
 it('drives the ignored teammate public escalation and follow-up once',()=>{const session=new InterruptionSession(INTERRUPTION_CATALOG);session.activate('teammate-help',0);const transition=session.ignore('teammate-help');assert.match(session.snapshot.active[0]!.copy,/public engineering channel/i);assert.deepEqual(transition[0]!.followUpIds,['team-public-followup']);assert.equal(session.ignore('teammate-help').length,0);});
});
