import assert from 'node:assert/strict';import{describe,it}from'node:test';
import{CodingDisruptionLedger}from'../src/game/domain/CodingDisruptionLedger.ts';
import{CodingSession}from'../src/game/domain/CodingSession.ts';
import{ConsequenceQueue}from'../src/game/domain/ConsequenceQueue.ts';
import{EffectEngine}from'../src/game/domain/EffectEngine.ts';
import{INTERRUPTION_CATALOG}from'../src/game/content/poTeamInterruptions.ts';
import{PRODUCTION_AND_TOOLING_PACK,auditProductionAndToolingCatalog}from'../src/game/content/productionToolingInterruptions.ts';
import{ENGINEERING_TASKS}from'../src/game/content/engineeringTasks.ts';
import{InterruptionSession,validateInterruptionDefinitions,type InterruptionDefinition}from'../src/game/domain/interruptions.ts';
import{evaluateWeight}from'../src/game/domain/EventScheduler.ts';import{DEFAULT_DAY_STATE_CONFIG}from'../src/game/domain/DayState.ts';
const block={type:'coding-disruption',id:'block',speedFactor:0,durationGameMs:100,startFeedback:'Blocked.',endFeedback:'Recovered.'}as const;
describe('production and tooling contracts',()=>{
 it('audits exact totals, topics, reachability, classifications, and exclusions',()=>{auditProductionAndToolingCatalog(INTERRUPTION_CATALOG,ENGINEERING_TASKS.map(x=>x.id));assert.equal(PRODUCTION_AND_TOOLING_PACK.filter(x=>x.category==='production').length,6);assert.equal(PRODUCTION_AND_TOOLING_PACK.filter(x=>x.category==='tooling').length,4);assert.ok(PRODUCTION_AND_TOOLING_PACK.every(x=>x.incidentControl));assert.ok(PRODUCTION_AND_TOOLING_PACK.flatMap(x=>x.topics??[]).every(x=>!['personal','consequence-pack'].includes(x)));});
 it('rejects malformed classification, disruption, uncertainty, and debt severity before activation',()=>{const valid=PRODUCTION_AND_TOOLING_PACK[0]!;const reject=(d:InterruptionDefinition)=>assert.throws(()=>validateInterruptionDefinitions([d]));reject({...valid,incidentControl:'other' as never});reject({...valid,choices:[{...valid.choices[0]!,effects:[{...block,durationGameMs:0}]},valid.choices[1]!]});reject({...valid,choices:[{...valid.choices[0]!,effects:[{type:'delayed',id:'later',delayGameMs:1,effects:[],scheduledFeedback:'soon',concludedFeedback:'done'}]},valid.choices[1]!]});reject({...valid,escalationStages:[{...valid.escalationStages![0]!,debtSeverityModifier:{perDebtPoint:1,minimumRank:-1,maximumRank:4}}]});reject({...valid,category:'tooling',incidentControl:'external',escalationStages:[{...valid.escalationStages![0]!,debtSeverityModifier:{perDebtPoint:1,minimumRank:0,maximumRank:3}}]});});
 it('validates disruptions nested in delayed and probabilistic effects',()=>{const valid=PRODUCTION_AND_TOOLING_PACK[0]!;validateInterruptionDefinitions([{...valid,choices:[{...valid.choices[0]!,outcomeCertainty:'uncertain',effects:[{type:'delayed',id:'later',delayGameMs:1,scheduledFeedback:'Scheduled.',concludedFeedback:'Done.',effects:[block]}]}, {...valid.choices[1]!,outcomeCertainty:'uncertain',effects:[{type:'probability',id:'maybe',chance:.5,successEffects:[block],failureEffects:[],successFeedback:'Hit.',failureFeedback:'Miss.'}]}]}]);});
 it('changes only declared production weight under high debt',()=>{const resources={...DEFAULT_DAY_STATE_CONFIG.initialResources,technicalDebt:80};const base={selectedTaskId:null,completedTaskIds:[],resolvedEventIds:[],resolvedChoices:[],resources};const changed=PRODUCTION_AND_TOOLING_PACK.find(x=>x.id==='production-errors')!;const plain=PRODUCTION_AND_TOOLING_PACK.find(x=>x.id==='production-latency')!;const tool=PRODUCTION_AND_TOOLING_PACK.find(x=>x.category==='tooling')!;assert.ok(evaluateWeight(changed,base)>changed.baseWeight!);assert.equal(evaluateWeight(plain,base),plain.baseWeight);assert.equal(evaluateWeight(tool,base),tool.baseWeight);});
});
describe('authoritative disruptions',()=>{
 it('uses immutable deadlines, restrictive overlap, stable exact-once expiry, pause, and reset',()=>{const l=new CodingDisruptionLedger();l.add({...block,id:'slow',speedFactor:.5,durationGameMs:50},'a',10);l.add(block,'b',10);assert.equal(l.snapshot.effectiveSpeedFactor,0);assert.ok(Object.isFrozen(l.snapshot.active));assert.equal(l.synchronize(59).length,0);assert.deepEqual(l.synchronize(110).map(x=>x.id),['slow','block']);assert.equal(l.synchronize(110).length,0);assert.equal(l.snapshot.effectiveSpeedFactor,1);l.add(block,'b',200);l.reset();assert.equal(l.snapshot.active.length,0);});
 it('routes immediate, delayed, and probabilistic disruption branches',()=>{let time=0;const l=new CodingDisruptionLedger();const q=new ConsequenceQueue();const engine=new EffectEngine({mutateResource:()=>{},reduceFocus:()=>{},reduceTaskProgress:()=>{},disruptions:l,queue:q,gameTime:()=>time,technicalDebt:()=>0,feedback:()=>{}},1,{next:()=>0,reset:()=>{}});engine.execute([block,{type:'delayed',id:'later',delayGameMs:5,effects:[{...block,id:'delayed'}],scheduledFeedback:'Soon.',concludedFeedback:'Done.'},{type:'probability',id:'maybe',chance:1,successEffects:[{...block,id:'probable'}],successFeedback:'Yes.',failureFeedback:'No.'}],'source');assert.deepEqual(l.snapshot.active.map(x=>x.id),['block','probable']);time=5;engine.synchronize();assert.ok(l.snapshot.active.some(x=>x.id==='delayed'));engine.reset();assert.equal(l.snapshot.active.length,0);});
 it('full blocks cost no Stamina and partial speed preserves bounded focus and work',()=>{const c=new CodingSession({workPerGameMinute:10,staminaPerGameMinute:2,focusGainPerGameMinute:.1});c.synchronizeAvailability(true,100,true);c.requestCoding(true);c.setRuntimeModifiers({codingSpeed:0,focusGain:1});assert.deepEqual(c.update(60_000,100,100),{staminaCost:0,workProduced:0,hitBoundary:false});assert.equal(c.snapshot.isCodingRequested,false);c.setRuntimeModifiers({codingSpeed:.5,focusGain:1});assert.equal(c.snapshot.isCodingRequested,false);c.requestCoding(true);const result=c.update(60_000,100,100);assert.ok(result.workProduced>0&&result.workProduced<10);assert.equal(result.staminaCost,2);assert.ok(c.snapshot.focus>=0&&c.snapshot.focus<=1);});
});
describe('debt-sensitive escalation',()=>{it('snapshots bounded entry severity and preserves it after debt changes',()=>{let debt=0;const event=PRODUCTION_AND_TOOLING_PACK.find(x=>x.id==='production-errors')!;const s=new InterruptionSession([event],0,false,()=>debt);s.activate(event.id,0);debt=100;s.ignore(event.id);assert.equal(s.snapshot.active[0]!.severity,'critical');debt=0;assert.equal(s.snapshot.active[0]!.severity,'critical');});it('preserves authored severity when unmodified and cancels unentered stages on resolution',()=>{const event=PRODUCTION_AND_TOOLING_PACK.find(x=>x.id==='production-latency')!;const s=new InterruptionSession([event],0,false,()=>100);s.activate(event.id,0);s.ignore(event.id);assert.equal(s.snapshot.active[0]!.severity,'critical');s.open(event.id);s.beginResolution(event.choices[0]!.id);s.setCurrentGameMs(99999999);s.finalizeResolution(event.id);assert.equal(s.snapshot.active.length,0);});});
