import assert from 'node:assert/strict';
import {describe,it} from 'node:test';
import {activePacingBand,createPacingProfile,DEVELOPER_PACING_PROFILE,NORMAL_PACING_PROFILE,splitPacingInterval,WORKDAY_DURATION_MS} from '../src/game/domain/WorkdayPacing.ts';

describe('workday pacing profiles',()=>{
    it('covers the workday exactly with immutable named bands and faster developer time',()=>{assert.equal(NORMAL_PACING_PROFILE.bands[0].startGameMs,0);assert.equal(NORMAL_PACING_PROFILE.bands.at(-1)?.endGameMs,WORKDAY_DURATION_MS);assert.ok(DEVELOPER_PACING_PROFILE.gameMinutesPerRealSecond>NORMAL_PACING_PROFILE.gameMinutesPerRealSecond);assert.throws(()=>Object.assign(NORMAL_PACING_PROFILE.bands[0],{id:'bad'}));});
    it('rejects identities, gaps, overlaps, ordering, unknown keys and modifier bounds',()=>{const base=NORMAL_PACING_PROFILE;const replace=(index:number,value:object)=>base.bands.map((band,i)=>i===index?{...band,...value}:band);assert.throws(()=>createPacingProfile({...base,id:'hard' as never}),/Unknown pacing profile/);assert.throws(()=>createPacingProfile({...base,bands:replace(1,{startGameMs:base.bands[1].startGameMs+1})}),/gap-free/);assert.throws(()=>createPacingProfile({...base,bands:replace(1,{id:'lunch'}) as never}),/identities/);assert.throws(()=>createPacingProfile({...base,bands:replace(0,{needRateModifiers:{hunger:1}}) as never}),/Unknown need/);assert.throws(()=>createPacingProfile({...base,bands:replace(0,{categoryWeightModifiers:{production:9}})}),/modifier/);});
    it('uses exact half-open boundaries and splits multi-band jumps without step dependence',()=>{const boundary=NORMAL_PACING_PROFILE.bands[0].endGameMs;assert.equal(activePacingBand(NORMAL_PACING_PROFILE,boundary-1).id,'morning');assert.equal(activePacingBand(NORMAL_PACING_PROFILE,boundary).id,'normal-workload');assert.equal(activePacingBand(NORMAL_PACING_PROFILE,WORKDAY_DURATION_MS).id,'endgame');const intervals=splitPacingInterval(NORMAL_PACING_PROFILE,boundary-60_000,NORMAL_PACING_PROFILE.bands[3].startGameMs+60_000);assert.deepEqual(intervals.map(x=>x.band.id),['morning','normal-workload','lunch','main-chaos']);assert.equal(intervals.reduce((sum,x)=>sum+x.durationGameMs,0),NORMAL_PACING_PROFILE.bands[3].startGameMs+120_000-boundary);assert.deepEqual(splitPacingInterval(NORMAL_PACING_PROFILE,10,10),[]);});
});
