import type { AiModeId,AiModeProfile } from '../content/aiModes';
import { AI_MODE_PROFILES } from '../content/aiModes';
import { validateAiModeCatalog } from './AiModeCatalog';
export type AiCyclePhase='available'|'planning'|'generating'|'review';
export interface AiBatch {readonly id:string;readonly cycleId:string;readonly taskId:string;readonly mode:AiModeId;readonly revisionTier:number;readonly proposedWork:number;readonly changedFiles:readonly string[];readonly tests:readonly string[];readonly signals:readonly string[];readonly hiddenSignalCount:number;readonly adverse:boolean;readonly effects:readonly Record<string,unknown>[]}
export interface AiCycleSnapshot {readonly phase:AiCyclePhase;readonly cycleId:string|null;readonly taskId:string|null;readonly mode:AiModeId|null;readonly revisionTier:number;readonly elapsedGameMs:number;readonly totalGameMs:number;readonly progress:number;readonly batch:AiBatch|null;readonly isAvailable:boolean;readonly disabledReason:string|null}
export interface ReviewTransition {readonly accepted:boolean;readonly batch:AiBatch|null;readonly staminaCost:number}
type Context={readonly taskId:string|null;readonly available:boolean;readonly disabledReason?:string|null;readonly focus:number;readonly workBoundary:number};
const hash=(input:string)=>{let h=2166136261;for(let i=0;i<input.length;i++){h^=input.charCodeAt(i);h=Math.imul(h,16777619);}return h>>>0;};
const random=(seed:number,key:string)=>hash(`${seed}:${key}`)/4294967296;
const freezeBatch=(batch:AiBatch):AiBatch=>Object.freeze({...batch,changedFiles:Object.freeze([...batch.changedFiles]),tests:Object.freeze([...batch.tests]),signals:Object.freeze([...batch.signals]),effects:Object.freeze([...batch.effects])});
export class AiWorkCycle{
 private phase:AiCyclePhase='available';private cycleId:string|null=null;private taskId:string|null=null;private mode:AiModeId|null=null;private tier=0;private elapsed=0;private total=0;private currentBatch:AiBatch|null=null;private sequence=0;private context:Context={taskId:null,available:false,focus:0,workBoundary:0};private readonly profiles:ReadonlyMap<AiModeId,AiModeProfile>;
 constructor(readonly seed:number,catalog:readonly AiModeProfile[]=AI_MODE_PROFILES){if(!Number.isInteger(seed))throw new TypeError('AI cycle seed must be an integer.');validateAiModeCatalog(catalog);this.profiles=new Map(catalog.map(p=>[p.id,p]));}
 get snapshot():AiCycleSnapshot{return Object.freeze({phase:this.phase,cycleId:this.cycleId,taskId:this.taskId,mode:this.mode,revisionTier:this.tier,elapsedGameMs:this.elapsed,totalGameMs:this.total,progress:this.total?Math.min(1,this.elapsed/this.total):0,batch:this.currentBatch,isAvailable:this.phase==='available'&&this.context.available,disabledReason:this.phase==='available'&&!this.context.available?(this.context.disabledReason??'Unavailable'):null});}
 synchronize(context:Context):void{if(!Number.isFinite(context.focus)||context.focus<0||context.focus>1||!Number.isFinite(context.workBoundary)||context.workBoundary<0)throw new RangeError('AI cycle context is invalid.');this.context=Object.freeze({...context});if(this.phase!=='available'&&context.taskId!==this.taskId)this.cancel();}
 start(mode:AiModeId,expectedTaskId:string):boolean{if(!this.snapshot.isAvailable||this.context.taskId!==expectedTaskId)return false;const profile=this.profiles.get(mode);if(!profile)return false;this.sequence++;this.cycleId=`cycle-${this.sequence}`;this.taskId=expectedTaskId;this.mode=mode;this.tier=0;this.elapsed=0;this.phase=profile.planningGameMs>0?'planning':'generating';this.total=this.phase==='planning'?profile.planningGameMs:profile.generationGameMs;this.currentBatch=null;return true;}
 advance(gameMs:number,speedFactor=1):void{if(!Number.isFinite(gameMs)||gameMs<0||!Number.isFinite(speedFactor)||speedFactor<0||speedFactor>1)throw new RangeError('AI cycle advancement is invalid.');let remaining=gameMs*speedFactor;while(remaining>0&&(this.phase==='planning'||this.phase==='generating')){const used=Math.min(remaining,this.total-this.elapsed);this.elapsed+=used;remaining-=used;if(this.elapsed<this.total)break;const profile=this.profile!;if(this.phase==='planning'){this.phase='generating';this.elapsed=0;this.total=profile.generationGameMs;}else{this.currentBatch=this.generateBatch();this.phase='review';this.elapsed=this.total;}}}
 approve(expected:{taskId:string;cycleId:string;batchId:string}):ReviewTransition{if(!this.matches(expected))return Object.freeze({accepted:false,batch:null,staminaCost:0});const batch=this.currentBatch!;this.clear();return Object.freeze({accepted:true,batch,staminaCost:0});}
 revise(expected:{taskId:string;cycleId:string;batchId:string}):ReviewTransition{if(!this.matches(expected))return Object.freeze({accepted:false,batch:null,staminaCost:0});const old=this.currentBatch!,profile=this.profile!;this.tier=Math.min(profile.revision.maximumTier,this.tier+1);this.currentBatch=null;this.phase='generating';this.elapsed=0;this.total=profile.revision.generationGameMs;return Object.freeze({accepted:true,batch:old,staminaCost:profile.revision.staminaCost});}
 cancel():void{this.clear();}reset():void{this.sequence=0;this.clear();}
 private get profile():AiModeProfile|null{return this.mode?this.profiles.get(this.mode)??null:null;}
 private matches(e:{taskId:string;cycleId:string;batchId:string}):boolean{return this.phase==='review'&&this.taskId===e.taskId&&this.cycleId===e.cycleId&&this.currentBatch?.id===e.batchId;}
 private generateBatch():AiBatch{const p=this.profile!,key=`${this.cycleId}:${this.taskId}:${p.id}:${this.tier}`;const proposed=Math.min(this.context.workBoundary,p.work.minimum+(p.work.maximum-p.work.minimum)*random(this.seed,`${key}:work`));const chance=Math.max(0,p.quality.adverseChance-this.tier*p.quality.revisionImprovement);const adverse=random(this.seed,`${key}:risk`)<chance;const applicable=adverse?['Potential regression in an edge path.','Dependency behavior remains uncertain.']:['No blocking concerns detected.'];const reveal=Math.min(applicable.length,p.evidence.concerns+this.tier+(this.context.focus>=.66?1:0));const fileCount=Math.max(1,Math.ceil(proposed/5));const testCount=Math.max(1,p.evidence.tests+this.tier+(this.context.focus>=.8?1:0));return freezeBatch({id:`batch-${this.sequence}-${this.tier}`,cycleId:this.cycleId!,taskId:this.taskId!,mode:p.id,revisionTier:this.tier,proposedWork:proposed,changedFiles:Array.from({length:fileCount},(_,i)=>`src/change-${i+1}.ts`),tests:Array.from({length:testCount},(_,i)=>`test-${i+1}: ${i?'integration':'unit'} checks pass`),signals:applicable.slice(0,reveal),hiddenSignalCount:applicable.length-reveal,adverse,effects:adverse?p.adverseEffects:[]});}
 private clear():void{this.phase='available';this.cycleId=null;this.taskId=null;this.mode=null;this.tier=0;this.elapsed=0;this.total=0;this.currentBatch=null;}
}
