export interface CodingSessionConfig { readonly workPerGameMinute:number;readonly staminaPerGameMinute:number;readonly focusGainPerGameMinute:number;readonly focusDecayPerGameMinute:number;readonly baseFocusMultiplier:number;readonly maximumFocusMultiplier:number }
export interface CodingRuntimeModifiers { readonly codingSpeed:number;readonly focusGain:number }
export const NEUTRAL_CODING_MODIFIERS:CodingRuntimeModifiers=Object.freeze({codingSpeed:1,focusGain:1});
export interface CodingSessionSnapshot { readonly focus:number;readonly focusMultiplier:number;readonly isCodingRequested:boolean;readonly isAvailable:boolean;readonly isCoding:boolean;readonly modifiers:CodingRuntimeModifiers }
export interface CodingUpdateResult { readonly staminaCost:number;readonly workProduced:number;readonly hitBoundary:boolean }
export const DEFAULT_CODING_SESSION_CONFIG:CodingSessionConfig=Object.freeze({workPerGameMinute:.34,staminaPerGameMinute:.18,focusGainPerGameMinute:.025,focusDecayPerGameMinute:.05,baseFocusMultiplier:1,maximumFocusMultiplier:2});
type Observer=(snapshot:CodingSessionSnapshot)=>void;
export class CodingSession{
 readonly config:CodingSessionConfig;private focus=0;private codingRequested=false;private workdayAvailable=true;private taskAvailable=true;private availableStamina=0;private modifiers:CodingRuntimeModifiers=NEUTRAL_CODING_MODIFIERS;private readonly observers=new Set<Observer>();
 constructor(overrides:Partial<CodingSessionConfig>={}){this.config=Object.freeze({...DEFAULT_CODING_SESSION_CONFIG,...overrides});this.validateConfig();}
 get snapshot():CodingSessionSnapshot{const isAvailable=this.workdayAvailable&&this.taskAvailable&&this.availableStamina>0;return Object.freeze({focus:this.focus,focusMultiplier:this.focusMultiplier(this.focus),isCodingRequested:this.codingRequested,isAvailable,isCoding:isAvailable&&this.codingRequested,modifiers:this.modifiers});}
 setRuntimeModifiers(modifiers:CodingRuntimeModifiers=NEUTRAL_CODING_MODIFIERS):void{if(![modifiers.codingSpeed,modifiers.focusGain].every(v=>Number.isFinite(v)&&v>=0&&v<=1))throw new RangeError('Coding runtime modifiers must be finite values between zero and one.');if(modifiers.codingSpeed===this.modifiers.codingSpeed&&modifiers.focusGain===this.modifiers.focusGain)return;this.modifiers=Object.freeze({...modifiers});this.notify();}
 synchronizeAvailability(workdayAvailable:boolean,availableStamina:number,taskAvailable=true):void{if(!Number.isFinite(availableStamina)||availableStamina<0)throw new RangeError('Available Stamina must be finite and non-negative.');const before=this.snapshot.isAvailable;const changed=this.availableStamina!==availableStamina||this.workdayAvailable!==workdayAvailable||this.taskAvailable!==taskAvailable;this.workdayAvailable=workdayAvailable;this.availableStamina=availableStamina;this.taskAvailable=taskAvailable;if(before&&!this.snapshot.isAvailable)this.codingRequested=false;if(changed||before!==this.snapshot.isAvailable)this.notify();}
 requestCoding(requested:boolean):void{const next=requested&&this.snapshot.isAvailable;if(next===this.codingRequested)return;this.codingRequested=next;this.notify();}
 cancelCoding():void{this.requestCoding(false);}
 reduceFocus(amount:number):void{if(!Number.isFinite(amount)||amount<0)throw new RangeError('Focus reduction must be finite and non-negative.');const next=Math.max(0,this.focus-amount);if(next===this.focus)return;this.focus=next;this.notify();}
 update(elapsedGameMs:number,availableStamina=this.availableStamina,workBoundary=Infinity):CodingUpdateResult{if(!Number.isFinite(elapsedGameMs)||elapsedGameMs<=0)return Object.freeze({staminaCost:0,workProduced:0,hitBoundary:false});if(!Number.isFinite(availableStamina)||availableStamina<0||Number.isNaN(workBoundary)||workBoundary<0)throw new RangeError('Coding inputs must be non-negative.');this.availableStamina=availableStamina;const before=this.snapshot;if(!before.isAvailable){this.codingRequested=false;if(before.isCodingRequested)this.notify();return Object.freeze({staminaCost:0,workProduced:0,hitBoundary:false});}const requestedMinutes=elapsedGameMs/60000;if(!this.codingRequested){const next=Math.max(0,this.focus-this.config.focusDecayPerGameMinute*requestedMinutes);if(next!==this.focus){this.focus=next;this.notify();}return Object.freeze({staminaCost:0,workProduced:0,hitBoundary:false});}const staminaMinutes=this.config.staminaPerGameMinute===0?requestedMinutes:availableStamina/this.config.staminaPerGameMinute;let usable=Math.min(requestedMinutes,staminaMinutes);usable=Math.min(usable,this.minutesForWork(workBoundary,usable));const workProduced=Math.min(workBoundary,this.integratedWork(usable));const staminaCost=Math.min(availableStamina,usable*this.config.staminaPerGameMinute);this.focus=Math.min(1,this.focus+this.effectiveFocusGain*usable);this.availableStamina=Math.max(0,availableStamina-staminaCost);const hitBoundary=Number.isFinite(workBoundary)&&workProduced>=workBoundary-1e-10;if(this.availableStamina===0||hitBoundary)this.codingRequested=false;if(usable>0||before.isCodingRequested!==this.codingRequested)this.notify();return Object.freeze({staminaCost,workProduced,hitBoundary});}
 subscribe(observer:Observer):()=>void{this.observers.add(observer);return()=>this.observers.delete(observer);}
 private integratedWork(minutes:number):number{if(minutes<=0)return 0;const gain=this.effectiveFocusGain;const untilMax=gain===0?Infinity:(1-this.focus)/gain;const growing=Math.min(minutes,untilMax);const range=this.config.maximumFocusMultiplier-this.config.baseFocusMultiplier;const rate=this.config.workPerGameMinute*this.modifiers.codingSpeed;return rate*(this.focusMultiplier(this.focus)*growing+range*gain*growing*growing/2)+rate*this.config.maximumFocusMultiplier*(minutes-growing);}
 private minutesForWork(work:number,max:number):number{if(work<=0)return 0;if(this.integratedWork(max)<=work)return max;let low=0,high=max;for(let i=0;i<52;i++){const middle=(low+high)/2;if(this.integratedWork(middle)<work)low=middle;else high=middle;}return high;}
 private focusMultiplier(focus:number):number{return this.config.baseFocusMultiplier+(this.config.maximumFocusMultiplier-this.config.baseFocusMultiplier)*focus;}
 private get effectiveFocusGain():number{return this.config.focusGainPerGameMinute*this.modifiers.focusGain;}
 private notify():void{const snapshot=this.snapshot;this.observers.forEach(observer=>observer(snapshot));}
 private validateConfig():void{const c=this.config;[c.workPerGameMinute,c.staminaPerGameMinute,c.focusGainPerGameMinute,c.focusDecayPerGameMinute].forEach(rate=>{if(!Number.isFinite(rate)||rate<0)throw new RangeError('Coding rates must be finite and non-negative.');});if(c.workPerGameMinute<=0)throw new RangeError('Coding work rate must be positive.');if(!Number.isFinite(c.baseFocusMultiplier)||c.baseFocusMultiplier<=0||!Number.isFinite(c.maximumFocusMultiplier)||c.maximumFocusMultiplier<c.baseFocusMultiplier)throw new RangeError('Focus multiplier bounds must be positive and ordered.');}
}
