import type { ResourceKey } from './DayState';
export interface TechnicalDebtModifier { readonly perDebtPoint:number; readonly minimum?:number; readonly maximum?:number }
export interface SelectionWeightModifier { readonly resource:ResourceKey; readonly perPoint:number; readonly referenceValue?:number; readonly minimum?:number; readonly maximum?:number }
export interface ResourceEffect { readonly type:'resource'; readonly resource:ResourceKey; readonly amount:number }
export interface FocusEffect { readonly type:'focus'; readonly reduction:number }
export interface TaskProgressEffect { readonly type:'task-progress'; readonly reduction:number }
export interface DelayedEffect { readonly type:'delayed'; readonly id:string; readonly delayGameMs:number; readonly effects:readonly Effect[]; readonly scheduledFeedback:string; readonly concludedFeedback:string }
export interface ProbabilityEffect { readonly type:'probability'; readonly id:string; readonly chance:number; readonly debtModifier?:TechnicalDebtModifier; readonly successEffects:readonly Effect[]; readonly failureEffects?:readonly Effect[]; readonly successFeedback:string; readonly failureFeedback:string }
export type ImmediateEffect=ResourceEffect|FocusEffect|TaskProgressEffect;
export type Effect=ImmediateEffect|DelayedEffect|ProbabilityEffect;
export interface ConsequenceFeedback { readonly consequenceId:string; readonly sourceId:string; readonly kind:'scheduled'|'concluded'; readonly tone:'neutral'|'positive'|'negative'; readonly text:string }
export const MAX_EFFECT_DEPTH=8;
const nonEmpty=(value:unknown):value is string=>typeof value==='string'&&value.trim().length>0;
export function validateModifier(modifier:TechnicalDebtModifier,owner='modifier'):void{if(!modifier||!Number.isFinite(modifier.perDebtPoint)||(modifier.minimum!==undefined&&!Number.isFinite(modifier.minimum))||(modifier.maximum!==undefined&&!Number.isFinite(modifier.maximum))||(modifier.minimum!==undefined&&modifier.maximum!==undefined&&modifier.minimum>modifier.maximum))throw new TypeError(`${owner} has an invalid Technical Debt modifier.`);}
export function evaluateDebtModifier(base:number,technicalDebt:number,modifier?:TechnicalDebtModifier):number{if(!Number.isFinite(base)||!Number.isFinite(technicalDebt)||technicalDebt<0)throw new RangeError('Modifier inputs must be finite and Technical Debt non-negative.');if(!modifier)return base;validateModifier(modifier);return Math.min(modifier.maximum??Infinity,Math.max(modifier.minimum??-Infinity,base+technicalDebt*modifier.perDebtPoint));}
export function validateSelectionWeightModifier(modifier:SelectionWeightModifier,owner='modifier'):void{if(!modifier||!RESOURCE_KEYS.includes(modifier.resource)||!Number.isFinite(modifier.perPoint)||(modifier.referenceValue!==undefined&&!Number.isFinite(modifier.referenceValue))||(modifier.minimum!==undefined&&!Number.isFinite(modifier.minimum))||(modifier.maximum!==undefined&&!Number.isFinite(modifier.maximum))||(modifier.minimum!==undefined&&modifier.maximum!==undefined&&modifier.minimum>modifier.maximum))throw new TypeError(`${owner} has an invalid selection weight modifier.`);}
import { RESOURCE_KEYS } from './DayState';
export function evaluateSelectionWeight(base:number,resources:Readonly<Record<ResourceKey,number>>,modifier?:SelectionWeightModifier):number{if(!Number.isFinite(base)||base<0)throw new RangeError('Base weight must be finite and non-negative.');if(!modifier)return base;validateSelectionWeightModifier(modifier);const value=resources[modifier.resource];if(!Number.isFinite(value))throw new RangeError(`Resource ${modifier.resource} must be finite.`);const adjusted=base+(value-(modifier.referenceValue??0))*modifier.perPoint;return Math.max(0,Math.min(modifier.maximum??Infinity,Math.max(modifier.minimum??-Infinity,adjusted)));}
export function validateEffects(effects:readonly Effect[],owner:string,depth=0):void{if(!Array.isArray(effects))throw new TypeError(`${owner} has invalid effects.`);if(depth>MAX_EFFECT_DEPTH)throw new RangeError(`${owner} exceeds maximum effect nesting depth.`);for(const effect of effects){if(!effect||typeof effect!=='object')throw new TypeError(`${owner} has an invalid effect.`);if(effect.type==='resource'&&nonEmpty(effect.resource)&&Number.isFinite(effect.amount))continue;if((effect.type==='focus'||effect.type==='task-progress')&&Number.isFinite(effect.reduction)&&effect.reduction>=0)continue;if(effect.type==='delayed'){if(!nonEmpty(effect.id)||!Number.isFinite(effect.delayGameMs)||effect.delayGameMs<=0||!nonEmpty(effect.scheduledFeedback)||!nonEmpty(effect.concludedFeedback))throw new TypeError(`${owner} has an invalid delayed effect.`);validateEffects(effect.effects,effect.id,depth+1);continue;}if(effect.type==='probability'){if(!nonEmpty(effect.id)||!Number.isFinite(effect.chance)||effect.chance<0||effect.chance>1||!nonEmpty(effect.successFeedback)||!nonEmpty(effect.failureFeedback))throw new TypeError(`${owner} has an invalid probability effect.`);if(effect.debtModifier)validateModifier(effect.debtModifier,effect.id);validateEffects(effect.successEffects,effect.id,depth+1);validateEffects(effect.failureEffects??[],effect.id,depth+1);continue;}throw new TypeError(`${owner} has an invalid effect.`);}}
