import type { ResourceValues } from './DayState';
import type { InterruptionCategory,IncidentControl,ResultKarma } from './interruptions';

export const SCORE_CATEGORY_IDS=['features','stability','poHappiness','stamina','technicalDebt','coworkerKarma','incidents','sleepiness','toilet','boosters','catastrophes'] as const;
export type ScoreCategoryId=typeof SCORE_CATEGORY_IDS[number];
export interface TerminalResolutionEvidence {readonly eventId:string;readonly choiceId:string;readonly category:InterruptionCategory;readonly incidentControl?:IncidentControl;readonly resultKarma?:ResultKarma}
export interface TerminalEvidence {readonly elapsedGameMs:number;readonly resources:ResourceValues;readonly needs:Readonly<{sleepiness:number;toilet:number}>;readonly completedTaskIds:readonly string[];readonly resolutions:readonly TerminalResolutionEvidence[];readonly resolvedIncidentIds:readonly string[];readonly criticalNeedEpisodes:Readonly<Record<'sleepiness'|'toilet',number>>;readonly boosterCounts:Readonly<Record<'coffee'|'cokeZero',number>>}
export interface ScoreLine {readonly id:ScoreCategoryId;readonly label:string;readonly evidence:string;readonly contribution:number;readonly minimum:number;readonly maximum:number}
export interface Ending {readonly id:string;readonly title:string;readonly narrative:string;readonly priority:number;readonly order:number}
export interface EvaluatedResult {readonly lifecycle:'results';readonly evidence:TerminalEvidence;readonly scoreLines:readonly ScoreLine[];readonly total:number;readonly minimumTotal:number;readonly maximumTotal:number;readonly ending:Ending}
export interface ScoreRule {readonly id:ScoreCategoryId;readonly label:string;readonly minimum:number;readonly maximum:number;readonly calculate:(evidence:TerminalEvidence)=>Readonly<{value:number;evidence:string}>}
export interface ScoringConfig {readonly minimumTotal:number;readonly maximumTotal:number;readonly rules:readonly ScoreRule[]}
export interface EndingDefinition extends Ending {readonly fallback?:boolean;readonly matches:(evidence:TerminalEvidence,result:Readonly<{total:number;scoreLines:readonly ScoreLine[]}>)=>boolean}

const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value));
const finite=(value:number)=>Number.isFinite(value);
const line=(id:ScoreCategoryId,label:string,minimum:number,maximum:number,calculate:ScoreRule['calculate']):ScoreRule=>Object.freeze({id,label,minimum,maximum,calculate});
export const DEFAULT_SCORING_CONFIG:ScoringConfig=Object.freeze({minimumTotal:0,maximumTotal:100,rules:Object.freeze([
 line('features','Completed features',0,30,e=>({value:e.completedTaskIds.length*6,evidence:`${e.completedTaskIds.length} completed`})),
 line('stability','System Stability',0,12,e=>({value:e.resources.systemStability*.12,evidence:`${Math.round(e.resources.systemStability)}/100`})),
 line('poHappiness','PO Happiness',0,10,e=>({value:e.resources.poHappiness*.1,evidence:`${Math.round(e.resources.poHappiness)}/100`})),
 line('stamina','Stamina remaining',0,8,e=>({value:e.resources.stamina*.08,evidence:`${Math.round(e.resources.stamina)}/100`})),
 line('technicalDebt','Technical Debt',-15,0,e=>({value:-e.resources.technicalDebt*.15,evidence:`${Math.round(e.resources.technicalDebt)} debt`})),
 line('coworkerKarma','Coworker karma',-8,12,e=>{const karma=e.resolutions.reduce((n,r)=>n+(r.resultKarma==='constructive'?1:r.resultKarma==='self-serving'?-1:0),0);return {value:karma*4,evidence:`${karma>=0?'+':''}${karma} karma`};}),
 line('incidents','Incidents resolved',0,12,e=>({value:e.resolvedIncidentIds.length*4,evidence:`${e.resolvedIncidentIds.length} handled`})),
 line('sleepiness','Sleepiness',-8,0,e=>({value:-e.needs.sleepiness*.08,evidence:`${Math.round(e.needs.sleepiness)}%`})),
 line('toilet','Toilet Need',-8,0,e=>({value:-e.needs.toilet*.08,evidence:`${Math.round(e.needs.toilet)}%`})),
 line('boosters','Boosters',-6,0,e=>({value:-(e.boosterCounts.coffee+e.boosterCounts.cokeZero),evidence:`Coffee ${e.boosterCounts.coffee} · Coke Zero ${e.boosterCounts.cokeZero}`})),
 line('catastrophes','Terminal catastrophes',-30,0,e=>{const zero=(['stamina','poHappiness','systemStability'] as const).filter(k=>e.resources[k]===0);return {value:-zero.length*10,evidence:zero.length?zero.join(', '):'None'};})
])});

export const DEFAULT_ENDINGS:readonly EndingDefinition[]=Object.freeze([
 Object.freeze({id:'unicorn-day',title:'Unicorn Day',narrative:'Everything shipped, everyone is happy, and production somehow survived.',priority:100,order:0,matches:(e:TerminalEvidence,r:Readonly<{total:number}>)=>e.completedTaskIds.length===5&&r.total>=55&&!(['stamina','poHappiness','systemStability'] as const).some(k=>e.resources[k]===0)}),
 Object.freeze({id:'biological-incident',title:'Biological Incident',narrative:'The systems held. Your biological service-level objective did not.',priority:90,order:1,matches:(e:TerminalEvidence)=>e.needs.toilet>=95||e.criticalNeedEpisodes.toilet>=2}),
 Object.freeze({id:'the-transcendent',title:'The Transcendent',narrative:'Caffeine, focus, and questionable judgment have merged into one deployable entity.',priority:80,order:2,matches:(e:TerminalEvidence)=>e.boosterCounts.coffee+e.boosterCounts.cokeZero>=4&&e.completedTaskIds.length>=3}),
 Object.freeze({id:'incident-commander',title:'Incident Commander',narrative:'You spent the day turning red dashboards back into merely concerning dashboards.',priority:70,order:3,matches:(e:TerminalEvidence)=>e.resolvedIncidentIds.length>=3}),
 Object.freeze({id:'promoted-to-management',title:'Promoted to Management',narrative:'The code is secondary. The stakeholder alignment has become unstoppable.',priority:60,order:4,matches:(e:TerminalEvidence)=>e.resources.poHappiness>=90&&e.resolutions.filter(r=>r.resultKarma==='constructive').length>=2}),
 Object.freeze({id:'10x-engineer',title:'10x Engineer',narrative:'You completed an alarming amount of work and left tomorrow a detailed apology.',priority:50,order:5,matches:(e:TerminalEvidence)=>e.completedTaskIds.length>=4&&(e.resources.technicalDebt>=35||e.resources.stamina<=20)}),
 Object.freeze({id:'staff-engineer',title:'Staff Engineer',narrative:'You navigated ambiguity, moved the work forward, and survived another calendar invite.',priority:0,order:6,fallback:true,matches:()=>true})
]);

export function validateScoringConfig(config:ScoringConfig):ScoringConfig{if(!finite(config.minimumTotal)||!finite(config.maximumTotal)||config.minimumTotal>=config.maximumTotal)throw new RangeError('Score total bounds are invalid.');if(config.rules.length!==SCORE_CATEGORY_IDS.length)throw new TypeError('Scoring rules must cover every category.');const ids=new Set<ScoreCategoryId>();for(const rule of config.rules){if(!SCORE_CATEGORY_IDS.includes(rule.id)||ids.has(rule.id)||!rule.label.trim()||!finite(rule.minimum)||!finite(rule.maximum)||rule.minimum>rule.maximum||typeof rule.calculate!=='function')throw new TypeError('Malformed scoring rule.');ids.add(rule.id);}return config;}
export function validateEndingDefinitions(definitions:readonly EndingDefinition[]):readonly EndingDefinition[]{const ids=new Set<string>(),slots=new Set<string>();let fallback=0;const witness=createTerminalEvidence({elapsedGameMs:8*60*60_000,resources:{stamina:10,poHappiness:100,systemStability:100,technicalDebt:50},needs:{sleepiness:100,toilet:100},completedTaskIds:['a','b','c','d','e'],resolutions:[{eventId:'a',choiceId:'a',category:'teammate',resultKarma:'constructive'},{eventId:'b',choiceId:'b',category:'teammate',resultKarma:'constructive'}],resolvedIncidentIds:['a','b','c'],criticalNeedEpisodes:{sleepiness:2,toilet:2},boosterCounts:{coffee:3,cokeZero:3}});for(const d of definitions){const slot=`${d.priority}:${d.order}`;if(!d.id.trim()||ids.has(d.id)||!d.title.trim()||!d.narrative.trim()||!Number.isInteger(d.priority)||!Number.isInteger(d.order)||slots.has(slot)||typeof d.matches!=='function')throw new TypeError('Malformed or duplicate ending definition.');if(d.fallback){fallback++;if(!d.matches(emptyEvidence(),{total:0,scoreLines:[]}))throw new TypeError('Ending fallback must be unconditional.');}else if(!d.matches(witness,{total:100,scoreLines:[]}))throw new TypeError(`Ending ${d.id} is unreachable within terminal bounds.`);ids.add(d.id);slots.add(slot);}if(fallback!==1)throw new TypeError('Ending definitions require one fallback.');return definitions;}
export function createTerminalEvidence(input:TerminalEvidence):TerminalEvidence{return Object.freeze({elapsedGameMs:input.elapsedGameMs,resources:Object.freeze({...input.resources}),needs:Object.freeze({...input.needs}),completedTaskIds:Object.freeze([...input.completedTaskIds]),resolutions:Object.freeze(input.resolutions.map(r=>Object.freeze({...r}))),resolvedIncidentIds:Object.freeze([...input.resolvedIncidentIds]),criticalNeedEpisodes:Object.freeze({...input.criticalNeedEpisodes}),boosterCounts:Object.freeze({...input.boosterCounts})});}
export function evaluateTerminalEvidence(input:TerminalEvidence,scoring=DEFAULT_SCORING_CONFIG,endings=DEFAULT_ENDINGS):EvaluatedResult{validateScoringConfig(scoring);validateEndingDefinitions(endings);const evidence=createTerminalEvidence(input);const scoreLines=Object.freeze(scoring.rules.map(rule=>{const raw=rule.calculate(evidence);if(!finite(raw.value)||!raw.evidence.trim())throw new TypeError(`Score rule ${rule.id} returned invalid output.`);return Object.freeze({id:rule.id,label:rule.label,evidence:raw.evidence,contribution:Math.round(clamp(raw.value,rule.minimum,rule.maximum)),minimum:rule.minimum,maximum:rule.maximum});}));const total=clamp(scoreLines.reduce((n,l)=>n+l.contribution,0),scoring.minimumTotal,scoring.maximumTotal);const ending=[...endings].sort((a,b)=>b.priority-a.priority||a.order-b.order).find(d=>d.matches(evidence,{total,scoreLines}));if(!ending)throw new Error('No ending matched terminal evidence.');return Object.freeze({lifecycle:'results',evidence,scoreLines,total,minimumTotal:scoring.minimumTotal,maximumTotal:scoring.maximumTotal,ending:Object.freeze({id:ending.id,title:ending.title,narrative:ending.narrative,priority:ending.priority,order:ending.order})});}
function emptyEvidence():TerminalEvidence{return createTerminalEvidence({elapsedGameMs:8*60*60_000,resources:{stamina:50,poHappiness:50,systemStability:50,technicalDebt:0},needs:{sleepiness:0,toilet:0},completedTaskIds:[],resolutions:[],resolvedIncidentIds:[],criticalNeedEpisodes:{sleepiness:0,toilet:0},boosterCounts:{coffee:0,cokeZero:0}});}
