import type { Effect } from './effects';
import { validateEffects } from './effects';
export type EngineeringTaskPriority='low'|'medium'|'high'|'urgent';export type EngineeringTaskStatus='dormant'|'active'|'completed'|'failed';
export interface TaskDecisionChoiceDefinition{readonly id:string;readonly label:string;readonly description:string;readonly gameMinutes:number;readonly effects:readonly Effect[]}
export interface TaskDecisionDefinition{readonly id:string;readonly title:string;readonly copy:string;readonly threshold:number;readonly choices:readonly TaskDecisionChoiceDefinition[]}
export interface EngineeringTaskDefinition{readonly id:string;readonly title:string;readonly effort:number;readonly priority:EngineeringTaskPriority;readonly rewardCopy:string;readonly riskCopy:string;readonly completionEffects:readonly Effect[];readonly technicalDebtEffects?:readonly Effect[];readonly midpointDecision?:TaskDecisionDefinition;readonly stakeholder?:string;readonly initialDeadlineGameMs?:number;readonly initialStatus?:'active'|'dormant';readonly failureEffects?:readonly Effect[];readonly crisisTaskId?:string}
export interface EngineeringTaskSnapshot extends EngineeringTaskDefinition{readonly status:EngineeringTaskStatus;readonly currentEffort:number;readonly completedWork:number;readonly progress:number;readonly deadlineGameMs:number|null;readonly remainingGameMs:number|null;readonly isSelected:boolean;readonly isComplete:boolean;readonly midpointTriggered:boolean}
export interface EngineeringTaskQueueSnapshot{readonly tasks:readonly EngineeringTaskSnapshot[];readonly selectedTaskId:string|null;readonly selectedTask:EngineeringTaskSnapshot|null;readonly completedTaskIds:readonly string[];readonly runCompletedTaskIds:readonly string[];readonly pendingDecision:Readonly<{taskId:string;definition:TaskDecisionDefinition}>|null}
export interface TaskWorkTransition{readonly appliedWork:number;readonly decisionOpened:boolean;readonly completedTaskId:string|null;readonly completionEffects:readonly Effect[]}
export interface TaskFailureTransition{readonly taskId:string;readonly effects:readonly Effect[];readonly activatedTaskId:string|null}
const priorities:readonly EngineeringTaskPriority[]=['low','medium','high','urgent'],nonEmpty=(v:unknown):v is string=>typeof v==='string'&&v.trim().length>0,freezeEffects=(e:readonly Effect[])=>Object.freeze([...e]);
export function validateEngineeringTaskCatalog(catalog:readonly EngineeringTaskDefinition[]):void{if(!Array.isArray(catalog)||!catalog.length)throw new TypeError('Engineering task catalog must not be empty.');const ids=new Set<string>();for(const t of catalog){if(!nonEmpty(t.id)||ids.has(t.id))throw new TypeError('Engineering task ids must be non-empty and unique.');ids.add(t.id);if(!nonEmpty(t.title)||!nonEmpty(t.rewardCopy)||!nonEmpty(t.riskCopy))throw new TypeError(`${t.id} has invalid copy.`);if(!Number.isFinite(t.effort)||t.effort<=0)throw new RangeError(`${t.id} effort must be positive.`);if(!priorities.includes(t.priority))throw new TypeError(`${t.id} has an invalid priority.`);if(t.stakeholder!==undefined&&!nonEmpty(t.stakeholder))throw new TypeError(`${t.id} has an invalid stakeholder.`);if(t.initialDeadlineGameMs!==undefined&&(!Number.isFinite(t.initialDeadlineGameMs)||t.initialDeadlineGameMs<=0))throw new RangeError(`${t.id} deadline must be positive.`);validateEffects(t.completionEffects,`${t.id} completion effects`);validateEffects(t.technicalDebtEffects??[],`${t.id} debt effects`);validateEffects(t.failureEffects??[],`${t.id} failure effects`);const d=t.midpointDecision;if(d){if(!nonEmpty(d.id)||!nonEmpty(d.title)||!nonEmpty(d.copy)||!Number.isFinite(d.threshold)||d.threshold<=0||d.threshold>=100||!Array.isArray(d.choices)||d.choices.length<2)throw new TypeError(`${t.id} has an invalid midpoint decision.`);const cs=new Set<string>();for(const c of d.choices){if(!nonEmpty(c.id)||cs.has(c.id)||!nonEmpty(c.label)||!nonEmpty(c.description)||!Number.isFinite(c.gameMinutes)||c.gameMinutes<0)throw new TypeError(`${d.id} has an invalid choice.`);cs.add(c.id);validateEffects(c.effects,`${d.id}/${c.id} effects`);}}}for(const t of catalog)if(t.crisisTaskId){const c=catalog.find(x=>x.id===t.crisisTaskId);if(!c||c.initialStatus!=='dormant'||c.crisisTaskId)throw new TypeError(`${t.id} has an invalid crisis task.`);}}
type Runtime={status:EngineeringTaskStatus;effort:number;work:number;deadline:number|null};type Observer=(s:EngineeringTaskQueueSnapshot)=>void;
export class EngineeringTaskQueue{readonly catalog:readonly EngineeringTaskDefinition[];private state=new Map<string,Runtime>();private selectedId:string|null=null;private completed:string[]=[];private runCompleted:string[]=[];private triggered=new Set<string>();private pendingTaskId:string|null=null;private now=0;private readonly observers=new Set<Observer>();
constructor(catalog:readonly EngineeringTaskDefinition[]){validateEngineeringTaskCatalog(catalog);this.catalog=Object.freeze(catalog.map(t=>Object.freeze({...t,completionEffects:freezeEffects(t.completionEffects),technicalDebtEffects:freezeEffects(t.technicalDebtEffects??[]),failureEffects:freezeEffects(t.failureEffects??[]),midpointDecision:t.midpointDecision&&Object.freeze({...t.midpointDecision,choices:Object.freeze(t.midpointDecision.choices.map(c=>Object.freeze({...c,effects:freezeEffects(c.effects)})))})})));this.reset();}
get snapshot():EngineeringTaskQueueSnapshot{const tasks=Object.freeze(this.catalog.map(d=>{const s=this.state.get(d.id)!;return Object.freeze({...d,status:s.status,currentEffort:s.effort,completedWork:s.work,progress:Math.min(100,s.work/s.effort*100),deadlineGameMs:s.deadline,remainingGameMs:s.deadline===null?null:Math.max(0,s.deadline-this.now),isSelected:d.id===this.selectedId,isComplete:s.status==='completed',midpointTriggered:this.triggered.has(d.id)});}));const selectedTask=tasks.find(t=>t.id===this.selectedId)??null,pendingTask=tasks.find(t=>t.id===this.pendingTaskId);return Object.freeze({tasks,selectedTaskId:this.selectedId,selectedTask,completedTaskIds:Object.freeze([...this.completed]),runCompletedTaskIds:Object.freeze([...this.runCompleted,...this.completed]),pendingDecision:pendingTask?.midpointDecision?Object.freeze({taskId:pendingTask.id,definition:pendingTask.midpointDecision}):null});}
setCurrentGameMs(ms:number):void{if(!Number.isFinite(ms)||ms<0)throw new RangeError('Task time must be finite and non-negative.');this.now=ms;}select(id:string):boolean{const s=this.state.get(id);if(!s||s.status!=='active'||id===this.selectedId||this.pendingTaskId)return false;this.selectedId=id;this.notify();return true;}
nextWorkBoundary():number{const t=this.snapshot.selectedTask;if(!t||this.pendingTaskId||t.status!=='active')return 0;const completion=t.currentEffort-t.completedWork,d=t.midpointDecision;if(!d||t.midpointTriggered)return completion;return Math.min(completion,t.currentEffort*d.threshold/100-t.completedWork);}
applyWork(work:number):TaskWorkTransition{if(!Number.isFinite(work)||work<0)throw new RangeError('Task work must be finite and non-negative.');const t=this.snapshot.selectedTask;if(!t||t.status!=='active'||this.pendingTaskId||!work)return Object.freeze({appliedWork:0,decisionOpened:false,completedTaskId:null,completionEffects:Object.freeze([])});const appliedWork=Math.min(work,this.nextWorkBoundary()),s=this.state.get(t.id)!;s.work+=appliedWork;let decisionOpened=false,completedTaskId:string|null=null,effects:readonly Effect[]=Object.freeze([]);const progress=s.work/s.effort*100;if(t.midpointDecision&&!t.midpointTriggered&&progress>=t.midpointDecision.threshold){this.triggered.add(t.id);this.pendingTaskId=t.id;decisionOpened=true;}else if(progress>=100){s.work=s.effort;s.status='completed';s.deadline=null;this.completed.push(t.id);completedTaskId=t.id;effects=Object.freeze([...t.completionEffects,...(t.technicalDebtEffects??[])]);this.selectedId=this.firstActive();}this.notify();return Object.freeze({appliedWork,decisionOpened,completedTaskId,completionEffects:effects});}
resolvePendingDecision(id:string):TaskDecisionChoiceDefinition|null{const p=this.snapshot.pendingDecision,c=p?.definition.choices.find(x=>x.id===id);if(!p||!c)return null;this.pendingTaskId=null;this.notify();return c;}reduceSelectedProgress(a:number):boolean{if(!Number.isFinite(a)||a<0)throw new RangeError('Task progress reduction must be finite and non-negative.');const t=this.snapshot.selectedTask;if(!t||t.status!=='active'||!a)return false;const s=this.state.get(t.id)!,n=Math.max(0,s.work-s.effort*a/100);if(n===s.work)return false;s.work=n;this.notify();return true;}
addEffort(id:string,a:number):boolean{if(!Number.isFinite(a)||a<=0)throw new RangeError('Task effort increase must be positive.');const s=this.state.get(id);if(!s||s.status!=='active')return false;s.effort+=a;this.notify();return true;}setDeadline(id:string,d:number,mode:'set'|'extend'='set'):boolean{if(!Number.isFinite(d)||d<=0)throw new RangeError('Task deadline duration must be positive.');const s=this.state.get(id);if(!s||s.status!=='active'||(mode==='extend'&&s.deadline===null))return false;s.deadline=mode==='extend'?s.deadline!+d:this.now+d;this.notify();return true;}activate(id:string):boolean{const ok=this.activateSilently(id);if(ok){this.selectedId??=id;this.notify();}return ok;}
nextDeadlineGameMs():number|null{let n=Infinity;for(const s of this.state.values())if(s.status==='active'&&s.deadline!==null)n=Math.min(n,s.deadline);return Number.isFinite(n)?n:null;}failOverdue(at:number):readonly TaskFailureTransition[]{this.setCurrentGameMs(at);const out:TaskFailureTransition[]=[];for(const d of this.catalog){const s=this.state.get(d.id)!;if(s.status!=='active'||s.deadline===null||s.deadline>=at)continue;s.status='failed';s.deadline=null;if(this.pendingTaskId===d.id)this.pendingTaskId=null;const activated=d.crisisTaskId&&this.activateSilently(d.crisisTaskId)?d.crisisTaskId:null;out.push(Object.freeze({taskId:d.id,effects:freezeEffects(d.failureEffects??[]),activatedTaskId:activated}));}if(out.length){if(!this.selectedId||this.state.get(this.selectedId)?.status!=='active')this.selectedId=this.firstActive();this.notify();}return Object.freeze(out);}
reset():void{this.state=new Map(this.catalog.map(d=>[d.id,{status:d.initialStatus??'active',effort:d.effort,work:0,deadline:d.initialDeadlineGameMs??null}]));this.selectedId=this.firstActive();this.completed=[];this.runCompleted=[];this.triggered=new Set();this.pendingTaskId=null;this.now=0;this.notify();}
beginNextDay(dayIndex:number):void{if(!Number.isInteger(dayIndex)||dayIndex<2)throw new RangeError('Next day index must be at least two.');this.runCompleted.push(...this.completed.map(id=>`day-${dayIndex-1}:${id}`));for(const d of this.catalog){const s=this.state.get(d.id)!;if(s.status!=='completed')continue;const source=this.catalog.find(x=>x.crisisTaskId===d.id),ss=source&&this.state.get(source.id);s.status=d.initialStatus??'active';s.effort=d.effort;s.work=0;s.deadline=d.initialDeadlineGameMs===undefined?null:this.now+d.initialDeadlineGameMs;if(source&&ss?.status==='failed'){s.status='dormant';ss.status=source.initialStatus??'active';ss.effort=source.effort;ss.work=0;ss.deadline=source.initialDeadlineGameMs===undefined?null:this.now+source.initialDeadlineGameMs;}}this.completed=[];this.triggered=new Set([...this.triggered].filter(id=>this.state.get(id)!.work>0));this.pendingTaskId=null;if(!this.selectedId||this.state.get(this.selectedId)?.status!=='active')this.selectedId=this.firstActive();this.notify();}
subscribe(o:Observer):()=>void{this.observers.add(o);return()=>this.observers.delete(o);}private firstActive():string|null{return this.catalog.find(d=>this.state.get(d.id)?.status==='active')?.id??null;}private activateSilently(id:string):boolean{const s=this.state.get(id);if(!s||s.status!=='dormant')return false;s.status='active';return true;}private notify():void{const s=this.snapshot;this.observers.forEach(o=>o(s));}}
