import { validateEffects,validateModifier,validateSelectionWeightModifier,type Effect,type SelectionWeightModifier } from './effects';
import type { ResourceValues } from './DayState';
import { RESOURCE_KEYS } from './DayState';
export type { ConsequenceFeedback,ConsumeBoosterEffect,DelayedEffect,Effect,ImmediateEffect,ProbabilityEffect,RelieveNeedEffect,ResourceEffect,TechnicalDebtModifier } from './effects';
export const INTERRUPTION_CATEGORIES = ['product-owner', 'production', 'teammate', 'tooling', 'personal', 'consequence'] as const;
export type InterruptionCategory = typeof INTERRUPTION_CATEGORIES[number];
export const INTERRUPTION_SEVERITIES = ['low', 'medium', 'high', 'critical'] as const;
export type InterruptionSeverity = typeof INTERRUPTION_SEVERITIES[number];
export type IncidentControl='external'|'player-fixable';
export type OutcomeCertainty='certain'|'uncertain';
export type ResultKarma='constructive'|'neutral'|'self-serving';
export interface InterruptionFollowUpDefinition {readonly eventId:string;readonly delayGameMs:number}
export type CaseOutcome='resolved'|'failed';
export interface InterruptionChoiceDefinition { readonly id:string; readonly label:string; readonly description:string; readonly gameMinutes:number; readonly effects:readonly Effect[]; readonly followUps?:readonly InterruptionFollowUpDefinition[];readonly caseOutcome?:CaseOutcome;readonly outcomeCertainty?:OutcomeCertainty;readonly resultKarma?:ResultKarma }
export interface DebtSeverityModifier { readonly perDebtPoint:number;readonly minimumRank:number;readonly maximumRank:number }
export interface EscalationStageDefinition { readonly delayGameMs:number; readonly copy:string; readonly severity:InterruptionSeverity; readonly effects:readonly Effect[]; readonly postponeGameMs:number; readonly followUpIds?:readonly string[];readonly debtSeverityModifier?:DebtSeverityModifier }
export type EligibilityFact=
 | Readonly<{type:'resolved-event';eventId:string}>
 | Readonly<{type:'resolved-choice';eventId:string;choiceId:string}>
 | Readonly<{type:'need-stage';need:'sleepiness'|'toilet';minimumStage:number}>
 | Readonly<{type:'booster-count';booster:'coffee'|'cokeZero';minimumCount:number}>
 | Readonly<{type:'incident-count';incidentId:string;minimumCount:number}>
 | Readonly<{type:'concluded-consequence';consequenceId:string}>
 | Readonly<{type:'case-status';caseId:string;status:'open'|CaseOutcome}>;
export type EligibilityPredicate=EligibilityFact|Readonly<{all:readonly EligibilityPredicate[]}>|Readonly<{any:readonly EligibilityPredicate[]}>;
export interface InterruptionRunContext { readonly resolvedEventIds:readonly string[]; readonly resolvedChoices:readonly ResolvedInterruptionOutcome[]; readonly resources:ResourceValues; readonly caseStatuses?:Readonly<Record<string,'open'|CaseOutcome>>;readonly needStages?:Readonly<Record<'sleepiness'|'toilet',number>>; readonly boosterCounts?:Readonly<Record<'coffee'|'cokeZero',number>>; readonly incidentCounts?:Readonly<Record<string,number>>; readonly concludedConsequenceIds?:readonly string[]; readonly activeDeduplicationKeys?:readonly string[]; readonly cooldownUntilGameMs?:Readonly<Record<string,number>>; readonly currentGameMs?:number }
export interface ResolvedInterruptionOutcome { readonly eventId:string;readonly choiceId:string;readonly category?:InterruptionCategory;readonly incidentControl?:IncidentControl;readonly resultKarma?:ResultKarma }
export type ConsequenceCause=Readonly<{type:'resolved-choice';eventId:string;choiceId:string}|{type:'concluded-consequence';consequenceId:string}|{type:'incident-history';incidentId:string;minimumCount:number}|{type:'current-state';predicate:EligibilityPredicate}>;
export interface InterruptionDefinition { readonly id:string;readonly caseId?:string; readonly category:InterruptionCategory; readonly severity:InterruptionSeverity; readonly title:string; readonly copy:string; readonly incidentControl?:IncidentControl;readonly topics?:readonly string[]; readonly choices:readonly InterruptionChoiceDefinition[]; readonly escalationStages?:readonly EscalationStageDefinition[]; readonly eligibility?:EligibilityPredicate; readonly documentedContexts?:readonly InterruptionRunContext[]; readonly baseWeight?:number; readonly selectionWeightModifier?:SelectionWeightModifier; readonly debtWeightModifier?:import('./effects').TechnicalDebtModifier; readonly cause?:ConsequenceCause; readonly deduplicationKey?:string; readonly cooldownGameMs?:number }
type Lifecycle='active'|'deciding'|'resolving';
export interface ActiveInterruptionSnapshot extends InterruptionDefinition { readonly activationGameMs:number; readonly activationSequence:number; readonly ageGameMinutes:number; readonly status:Lifecycle; readonly stageIndex:number; readonly nextEscalationGameMs:number|null }
export interface InterruptionSessionSnapshot { readonly active:readonly ActiveInterruptionSnapshot[]; readonly openInterruption:ActiveInterruptionSnapshot|null; readonly resolvedIds:readonly string[]; readonly resolvedOutcomes:readonly Readonly<{eventId:string;choiceId:string}>[];readonly resultOutcomes:readonly ResolvedInterruptionOutcome[]; readonly incidentCounts:Readonly<Record<string,number>>; readonly concludedConsequenceIds:readonly string[]; readonly cooldownUntilGameMs:Readonly<Record<string,number>> }
export interface PendingInterruptionResolution { readonly interruptionId:string; readonly choice:InterruptionChoiceDefinition }
export interface EscalationTransition { readonly interruptionId:string; readonly stageIndex:number; readonly deadlineGameMs:number; readonly effects:readonly Effect[]; readonly followUpIds:readonly string[] }
export type TransitionBatch=readonly EscalationTransition[];
type ActiveRecord={readonly definition:InterruptionDefinition;readonly activationGameMs:number;readonly activationSequence:number;status:Lifecycle;stageIndex:number;enteredSeverity?:InterruptionSeverity;nextEscalationGameMs:number|null};
type Observer=(snapshot:InterruptionSessionSnapshot)=>void;
const nonEmpty=(value:string)=>typeof value==='string'&&value.trim().length>0;
const freezeEffects=(effects:readonly Effect[])=>Object.freeze(effects.map(effect=>Object.freeze({...effect})));

export function validateInterruptionDefinitions(definitions:readonly InterruptionDefinition[]):readonly InterruptionDefinition[]{
 const ids=new Set<string>();
 for(const d of definitions){
  if(!nonEmpty(d.id)||ids.has(d.id))throw new TypeError('Interruption IDs must be non-empty and unique.');ids.add(d.id);
  if(d.caseId!==undefined&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(d.caseId))throw new TypeError(`Interruption ${d.id} has an invalid case ID.`);
  if(!INTERRUPTION_CATEGORIES.includes(d.category)||!INTERRUPTION_SEVERITIES.includes(d.severity)||!nonEmpty(d.title)||!nonEmpty(d.copy))throw new TypeError(`Invalid interruption metadata for ${d.id}.`);
  if((d.category==='production'||d.category==='tooling')&&!['external','player-fixable'].includes(d.incidentControl??''))throw new TypeError(`Interruption ${d.id} requires valid incident control.`);
  if(d.baseWeight!==undefined&&(!Number.isFinite(d.baseWeight)||d.baseWeight<0))throw new RangeError(`Interruption ${d.id} has invalid base weight.`);if(d.debtWeightModifier)validateModifier(d.debtWeightModifier,d.id);if(d.selectionWeightModifier)validateSelectionWeightModifier(d.selectionWeightModifier,d.id);if(d.eligibility)validateEligibilityPredicate(d.eligibility,d.id);
  if(d.deduplicationKey!==undefined&&!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(d.deduplicationKey))throw new TypeError(`Interruption ${d.id} has invalid deduplication key.`);
  if(d.cooldownGameMs!==undefined&&(!Number.isFinite(d.cooldownGameMs)||d.cooldownGameMs<0||d.cooldownGameMs>8*60*60_000))throw new RangeError(`Interruption ${d.id} has invalid cooldown.`);
  if(d.cooldownGameMs!==undefined&&!d.deduplicationKey)throw new TypeError(`Interruption ${d.id} cooldown requires a deduplication key.`);
  if(d.category==='consequence'&&!d.cause)throw new TypeError(`Consequence ${d.id} requires a cause.`);if(d.category!=='consequence'&&d.cause)throw new TypeError(`Only consequence events may declare a cause.`);if(d.cause)validateCause(d.cause,d.id);
  if(!Array.isArray(d.choices)||d.choices.length<2)throw new TypeError(`Interruption ${d.id} requires at least two choices.`);const choiceIds=new Set<string>();
  for(const c of d.choices){if(!nonEmpty(c.id)||choiceIds.has(c.id)||!nonEmpty(c.label)||!nonEmpty(c.description)||!['certain','uncertain'].includes(c.outcomeCertainty??'certain')||(c.resultKarma!==undefined&&!['constructive','neutral','self-serving'].includes(c.resultKarma))||(c.caseOutcome!==undefined&&!['resolved','failed'].includes(c.caseOutcome)))throw new TypeError(`Interruption ${d.id} has an invalid choice.`);if(d.category==='teammate'&&c.resultKarma===undefined)throw new TypeError(`Teammate choice ${c.id} requires result karma.`);choiceIds.add(c.id);if(!Number.isFinite(c.gameMinutes)||c.gameMinutes<0)throw new RangeError(`Choice ${c.id} has invalid action time.`);if(c.caseOutcome&&c.followUps?.length)throw new TypeError(`Terminal choice ${c.id} cannot schedule follow-ups.`);for(const follow of c.followUps??[])if(!nonEmpty(follow.eventId)||!Number.isFinite(follow.delayGameMs)||follow.delayGameMs<0)throw new TypeError(`Choice ${c.id} has an invalid follow-up.`);validateEffects(c.effects,c.id);validateResourceEffects(c.effects,c.id);const uncertain=c.effects.some((effect:Effect)=>effect.type==='delayed'||effect.type==='probability');if(uncertain&&c.outcomeCertainty!=='uncertain')throw new TypeError(`Choice ${c.id} must label uncertain outcomes.`);}
  for(const stage of d.escalationStages??[]){if(!Number.isFinite(stage.delayGameMs)||stage.delayGameMs<=0||!Number.isFinite(stage.postponeGameMs)||stage.postponeGameMs<=0)throw new RangeError(`Interruption ${d.id} has invalid escalation timing.`);if(!nonEmpty(stage.copy)||!INTERRUPTION_SEVERITIES.includes(stage.severity))throw new TypeError(`Interruption ${d.id} has invalid escalation metadata.`);if(stage.debtSeverityModifier){const m=stage.debtSeverityModifier;if(d.category!=='production'||![m.perDebtPoint,m.minimumRank,m.maximumRank].every(Number.isFinite)||!Number.isInteger(m.minimumRank)||!Number.isInteger(m.maximumRank)||m.minimumRank<0||m.maximumRank>3||m.minimumRank>m.maximumRank)throw new TypeError(`Interruption ${d.id} has an invalid debt severity modifier.`);}validateEffects(stage.effects,d.id);if(stage.followUpIds?.some(id=>!nonEmpty(id)||id===d.id))throw new TypeError(`Interruption ${d.id} has an invalid follow-up.`);}
 }
 for(const d of definitions)for(const stage of d.escalationStages??[])for(const id of stage.followUpIds??[])if(!ids.has(id))throw new TypeError(`Unknown follow-up ${id}.`);
 for(const d of definitions)for(const choice of d.choices)for(const follow of choice.followUps??[])if(!ids.has(follow.eventId))throw new TypeError(`Unknown follow-up ${follow.eventId}.`);
 const groups=new Map<string,number|undefined>();for(const d of definitions)if(d.deduplicationKey){if(groups.has(d.deduplicationKey)&&groups.get(d.deduplicationKey)!==d.cooldownGameMs)throw new TypeError(`Conflicting cooldown metadata for ${d.deduplicationKey}.`);groups.set(d.deduplicationKey,d.cooldownGameMs);}
 const edges=new Map(definitions.map(d=>[d.id,new Set([...(d.escalationStages??[]).flatMap(stage=>stage.followUpIds??[]),...(d.caseId?d.choices.flatMap(choice=>choice.followUps?.map(f=>f.eventId)??[]):[])])]));const visiting=new Set<string>();const visited=new Set<string>();
 const visit=(id:string):void=>{if(visiting.has(id))throw new TypeError('Interruption follow-up graph must be acyclic.');if(visited.has(id))return;visiting.add(id);for(const next of edges.get(id)??[])visit(next);visiting.delete(id);visited.add(id);};definitions.forEach(d=>visit(d.id));
 const cases=new Map<string,InterruptionDefinition[]>();for(const d of definitions)if(d.caseId){const group=cases.get(d.caseId)??[];group.push(d);cases.set(d.caseId,group);}for(const [caseId,nodes] of cases){for(const node of nodes)for(const choice of node.choices)for(const follow of choice.followUps??[])if(definitions.find(d=>d.id===follow.eventId)?.caseId!==caseId)throw new TypeError(`Case ${caseId} has a cross-case follow-up.`);const canTerminate=(id:string,seen=new Set<string>()):boolean=>{if(seen.has(id))return false;seen.add(id);const node=definitions.find(d=>d.id===id)!;return node.choices.some(c=>Boolean(c.caseOutcome)||Boolean(c.followUps?.some(f=>canTerminate(f.eventId,new Set(seen)))));};if(nodes.some(node=>!canTerminate(node.id)))throw new TypeError(`Case ${caseId} has no terminal route.`);}return definitions;
}
function validateResourceEffects(effects:readonly Effect[],owner:string):void{for(const effect of effects){if(effect.type==='resource'&&!RESOURCE_KEYS.includes(effect.resource))throw new TypeError(`${owner} has an invalid resource effect.`);if(effect.type==='delayed')validateResourceEffects(effect.effects,owner);if(effect.type==='probability'){validateResourceEffects(effect.successEffects,owner);validateResourceEffects(effect.failureEffects??[],owner);}}}

function validateEligibilityPredicate(predicate:EligibilityPredicate,owner:string):void{if(!predicate||typeof predicate!=='object')throw new TypeError(`${owner} has malformed eligibility.`);if('all'in predicate||'any'in predicate){const group='all'in predicate?predicate.all:predicate.any;if(!Array.isArray(group)||!group.length)throw new TypeError(`${owner} has an empty eligibility group.`);group.forEach(x=>validateEligibilityPredicate(x,owner));return;}if(predicate.type==='resolved-event'&&nonEmpty(predicate.eventId))return;if(predicate.type==='resolved-choice'&&nonEmpty(predicate.eventId)&&nonEmpty(predicate.choiceId))return;if(predicate.type==='need-stage'&&['sleepiness','toilet'].includes(predicate.need)&&Number.isInteger(predicate.minimumStage)&&predicate.minimumStage>=0&&predicate.minimumStage<=4)return;if(predicate.type==='booster-count'&&['coffee','cokeZero'].includes(predicate.booster)&&Number.isInteger(predicate.minimumCount)&&predicate.minimumCount>=0)return;if(predicate.type==='incident-count'&&nonEmpty(predicate.incidentId)&&Number.isInteger(predicate.minimumCount)&&predicate.minimumCount>0)return;if(predicate.type==='concluded-consequence'&&nonEmpty(predicate.consequenceId))return;if(predicate.type==='case-status'&&nonEmpty(predicate.caseId)&&['open','resolved','failed'].includes(predicate.status))return;throw new TypeError(`${owner} has malformed eligibility.`);}
function validateCause(cause:ConsequenceCause,owner:string):void{if(cause.type==='resolved-choice'&&nonEmpty(cause.eventId)&&nonEmpty(cause.choiceId))return;if(cause.type==='concluded-consequence'&&nonEmpty(cause.consequenceId))return;if(cause.type==='incident-history'&&nonEmpty(cause.incidentId)&&Number.isInteger(cause.minimumCount)&&cause.minimumCount>0)return;if(cause.type==='current-state'){validateEligibilityPredicate(cause.predicate,owner);return;}throw new TypeError(`${owner} has malformed consequence cause.`);}

export function createRunContext(input:InterruptionRunContext):InterruptionRunContext{return Object.freeze({resolvedEventIds:Object.freeze([...input.resolvedEventIds]),resolvedChoices:Object.freeze(input.resolvedChoices.map(item=>Object.freeze({...item}))),resources:Object.freeze({...input.resources}),caseStatuses:Object.freeze({...input.caseStatuses}),needStages:Object.freeze({...input.needStages??{sleepiness:0,toilet:0}}),boosterCounts:Object.freeze({...input.boosterCounts??{coffee:0,cokeZero:0}}),incidentCounts:Object.freeze({...input.incidentCounts}),concludedConsequenceIds:Object.freeze([...(input.concludedConsequenceIds??[])]),activeDeduplicationKeys:Object.freeze([...(input.activeDeduplicationKeys??[])]),cooldownUntilGameMs:Object.freeze({...input.cooldownUntilGameMs}),currentGameMs:input.currentGameMs??0});}
export function matchesEligibility(predicate:EligibilityPredicate|undefined,context:InterruptionRunContext):boolean{if(!predicate)return true;if('all'in predicate)return predicate.all.every(x=>matchesEligibility(x,context));if('any'in predicate)return predicate.any.some(x=>matchesEligibility(x,context));if(predicate.type==='resolved-event')return context.resolvedEventIds.includes(predicate.eventId);if(predicate.type==='resolved-choice')return context.resolvedChoices.some(x=>x.eventId===predicate.eventId&&x.choiceId===predicate.choiceId);if(predicate.type==='need-stage')return(context.needStages?.[predicate.need]??0)>=predicate.minimumStage;if(predicate.type==='booster-count')return(context.boosterCounts?.[predicate.booster]??0)>=predicate.minimumCount;if(predicate.type==='incident-count')return(context.incidentCounts?.[predicate.incidentId]??0)>=predicate.minimumCount;if(predicate.type==='case-status')return predicate.status==='open'?(context.caseStatuses?.[predicate.caseId]??'open')==='open':context.caseStatuses?.[predicate.caseId]===predicate.status;return context.concludedConsequenceIds?.includes(predicate.consequenceId)??false;}

export function validateInterruptionCatalog(definitions:readonly InterruptionDefinition[]):readonly InterruptionDefinition[]{validateInterruptionDefinitions(definitions);const events=new Map(definitions.map(x=>[x.id,x])),caseIds=new Set(definitions.flatMap(x=>x.caseId?[x.caseId]:[]));const check=(p:EligibilityPredicate,owner:string):void=>{if('all'in p){p.all.forEach(x=>check(x,owner));return;}if('any'in p){p.any.forEach(x=>check(x,owner));return;}if(p.type==='resolved-event'&&!events.has(p.eventId))throw new TypeError(`${owner} references unknown event ${p.eventId}.`);if(p.type==='resolved-choice'){const event=events.get(p.eventId);if(!event?.choices.some(c=>c.id===p.choiceId))throw new TypeError(`${owner} references unknown choice ${p.choiceId}.`);}if(p.type==='case-status'&&!caseIds.has(p.caseId))throw new TypeError(`${owner} references unknown case ${p.caseId}.`);};const effectIds=new Set<string>(),collect=(effects:readonly Effect[]):void=>effects.forEach(e=>{if(e.type==='delayed'){effectIds.add(e.id);collect(e.effects);}else if(e.type==='probability'){effectIds.add(e.id);collect(e.successEffects);collect(e.failureEffects??[]);}});for(const item of definitions){item.choices.forEach(c=>collect(c.effects));(item.escalationStages??[]).forEach(s=>collect(s.effects));if(item.eligibility)check(item.eligibility,item.id);if(item.cause?.type==='resolved-choice')check(item.cause,item.id);if(item.cause?.type==='concluded-consequence'&&!effectIds.has(item.cause.consequenceId))throw new TypeError(`${item.id} references unknown consequence ${item.cause.consequenceId}.`);}return definitions;}

export class InterruptionSession{
 private readonly definitions=new Map<string,InterruptionDefinition>();private readonly active=new Map<string,ActiveRecord>();private readonly resolvedIds:string[]=[];private readonly dailyResolvedIds=new Set<string>();private readonly resolvedOutcomes:ResolvedInterruptionOutcome[]=[];private readonly incidentCounts:Record<string,number>={};private readonly concludedConsequenceIds:string[]=[];private readonly cooldownUntilGameMs:Record<string,number>={};private pendingOutcome:ResolvedInterruptionOutcome|null=null;private openId:string|null=null;private currentGameMs:number;private nextActivationSequence=0;private readonly observers=new Set<Observer>();
 constructor(definitions:readonly InterruptionDefinition[],currentGameMs=0,activateInitially=false,private readonly technicalDebt:()=>number=()=>0,private readonly escalationDelay:(authoredDelayGameMs:number,dueGameMs:number)=>number=(delay)=>delay){if(!Number.isFinite(currentGameMs)||currentGameMs<0)throw new RangeError('Activation time must be finite and non-negative.');validateInterruptionDefinitions(definitions);definitions.forEach(d=>this.definitions.set(d.id,d));this.currentGameMs=currentGameMs;if(activateInitially)definitions.forEach(d=>this.activate(d.id,currentGameMs));}
 get snapshot():InterruptionSessionSnapshot{const active=Object.freeze([...this.active.values()].map(r=>this.snapshotRecord(r)));return Object.freeze({active,openInterruption:this.openId?active.find(i=>i.id===this.openId)??null:null,resolvedIds:Object.freeze([...this.resolvedIds]),resolvedOutcomes:Object.freeze(this.resolvedOutcomes.map(item=>Object.freeze({eventId:item.eventId,choiceId:item.choiceId}))),resultOutcomes:Object.freeze(this.resolvedOutcomes.map(item=>Object.freeze({...item}))),incidentCounts:Object.freeze({...this.incidentCounts}),concludedConsequenceIds:Object.freeze([...this.concludedConsequenceIds]),cooldownUntilGameMs:Object.freeze({...this.cooldownUntilGameMs})});}
 activate(id:string,gameMs=this.currentGameMs,activationSequence=this.nextActivationSequence++):boolean{const definition=this.definitions.get(id);if(!definition||this.active.has(id)||(!definition.cooldownGameMs&&this.dailyResolvedIds.has(id))||!Number.isFinite(gameMs)||gameMs<0)return false;const key=definition.deduplicationKey??definition.id;if([...this.active.values()].some(record=>(record.definition.deduplicationKey??record.definition.id)===key)||(this.cooldownUntilGameMs[key]??0)>gameMs)return false;const first=definition.escalationStages?.[0];this.active.set(id,{definition,activationGameMs:gameMs,activationSequence,status:'active',stageIndex:-1,nextEscalationGameMs:first?gameMs+this.resolvedEscalationDelay(first.delayGameMs,gameMs):null});this.notify();return true;}
 setCurrentGameMs(gameMs:number):TransitionBatch{if(!Number.isFinite(gameMs)||gameMs<0)throw new RangeError('Current game time must be finite and non-negative.');this.currentGameMs=gameMs;return this.advanceDue(gameMs);}
 advanceDue(gameMs=this.currentGameMs):TransitionBatch{const result:EscalationTransition[]=[];let guard=0;while(true){const due=[...this.active.values()].filter(r=>r.status==='active'&&r.nextEscalationGameMs!==null&&r.nextEscalationGameMs<=gameMs).sort((a,b)=>a.nextEscalationGameMs!-b.nextEscalationGameMs!||a.activationSequence-b.activationSequence)[0];if(!due)break;if(++guard>1000)throw new Error('Escalation transition limit exceeded.');const transition=this.enterNextStage(due,due.nextEscalationGameMs!);if(transition)result.push(transition);}if(result.length)this.notify();return Object.freeze(result);}
 postpone(id:string):boolean{const r=this.active.get(id);if(!r||r.status!=='active'||r.nextEscalationGameMs===null)return false;const stage=r.definition.escalationStages?.[Math.max(0,r.stageIndex)]??r.definition.escalationStages?.[0];if(!stage)return false;r.nextEscalationGameMs+=stage.postponeGameMs;this.notify();return true;}
 ignore(id:string):TransitionBatch{const r=this.active.get(id);if(!r||r.status!=='active'||r.nextEscalationGameMs===null)return Object.freeze([]);const transition=this.enterNextStage(r,this.currentGameMs);this.notify();return Object.freeze(transition?[transition]:[]);}
 open(id:string):boolean{if(this.openId)return false;const r=this.active.get(id);if(!r||r.status!=='active')return false;r.status='deciding';this.openId=id;this.notify();return true;}
 beginResolution(choiceId:string):PendingInterruptionResolution|null{if(!this.openId)return null;const r=this.active.get(this.openId);const choice=r?.definition.choices.find(c=>c.id===choiceId);if(!r||r.status!=='deciding'||!choice)return null;r.status='resolving';this.pendingOutcome=Object.freeze({eventId:r.definition.id,choiceId:choice.id,category:r.definition.category,incidentControl:r.definition.incidentControl,resultKarma:choice.resultKarma});this.notify();return Object.freeze({interruptionId:r.definition.id,choice});}
 finalizeResolution(id:string):boolean{const r=this.active.get(id);if(!r||r.status!=='resolving'||this.openId!==id||this.pendingOutcome?.eventId!==id)return false;this.active.delete(id);if(!this.resolvedIds.includes(id))this.resolvedIds.push(id);this.dailyResolvedIds.add(id);this.resolvedOutcomes.push(this.pendingOutcome);this.recordHandled(r.definition);this.pendingOutcome=null;this.openId=null;this.notify();return true;}
 beginNextDay():TransitionBatch{const transitions:EscalationTransition[]=[];for(const [id,r] of [...this.active]){const severity=this.snapshotRecord(r).severity;if(severity==='high'||severity==='critical')continue;const transition=r.nextEscalationGameMs===null?null:this.enterNextStage(r,this.currentGameMs);if(transition)transitions.push(transition);this.active.delete(id);this.recordHandled(r.definition);}this.dailyResolvedIds.clear();this.openId=null;this.pendingOutcome=null;this.notify();return Object.freeze(transitions);}
 dismissStale(context:InterruptionRunContext):readonly string[]{const dismissed:string[]=[];for(const [id,r] of this.active){if(r.definition.category==='personal'&&r.status==='active'&&!matchesEligibility(r.definition.eligibility,context)){this.active.delete(id);this.recordHandled(r.definition);dismissed.push(id);}}if(dismissed.length)this.notify();return Object.freeze(dismissed);}
 recordIncident(id:string):void{if(!nonEmpty(id))throw new TypeError('Incident ID must be non-empty.');this.incidentCounts[id]=(this.incidentCounts[id]??0)+1;this.notify();}
 recordConcludedConsequence(id:string):void{if(!nonEmpty(id))throw new TypeError('Consequence ID must be non-empty.');if(!this.concludedConsequenceIds.includes(id)){this.concludedConsequenceIds.push(id);this.notify();}}
 reset():void{this.active.clear();this.dailyResolvedIds.clear();this.resolvedIds.length=0;this.resolvedOutcomes.length=0;for(const key of Object.keys(this.incidentCounts))delete this.incidentCounts[key];this.concludedConsequenceIds.length=0;for(const key of Object.keys(this.cooldownUntilGameMs))delete this.cooldownUntilGameMs[key];this.pendingOutcome=null;this.openId=null;this.nextActivationSequence=0;this.currentGameMs=0;this.notify();}
 subscribe(observer:Observer):()=>void{this.observers.add(observer);let active=true;return()=>{if(active){active=false;this.observers.delete(observer);}};}
 private enterNextStage(r:ActiveRecord,deadline:number):EscalationTransition|null{const index=r.stageIndex+1;const stage=r.definition.escalationStages?.[index];if(!stage){r.nextEscalationGameMs=null;return null;}r.stageIndex=index;const authored=INTERRUPTION_SEVERITIES.indexOf(stage.severity);const modifier=stage.debtSeverityModifier;r.enteredSeverity=modifier?INTERRUPTION_SEVERITIES[Math.min(modifier.maximumRank,Math.max(modifier.minimumRank,Math.round(authored+this.technicalDebt()*modifier.perDebtPoint)))]!:stage.severity;const next=r.definition.escalationStages?.[index+1];r.nextEscalationGameMs=next?deadline+this.resolvedEscalationDelay(next.delayGameMs,deadline):null;return Object.freeze({interruptionId:r.definition.id,stageIndex:index,deadlineGameMs:deadline,effects:freezeEffects(stage.effects),followUpIds:Object.freeze([...(stage.followUpIds??[])])});}
 private resolvedEscalationDelay(authored:number,due:number):number{const value=this.escalationDelay(authored,due);if(!Number.isFinite(value)||value<=0)throw new RangeError('Escalation delay policy must return a finite positive delay.');return value;}
 private snapshotRecord(r:ActiveRecord):ActiveInterruptionSnapshot{const stage=r.stageIndex>=0?r.definition.escalationStages?.[r.stageIndex]:undefined;return Object.freeze({...r.definition,copy:stage?.copy??r.definition.copy,severity:r.enteredSeverity??stage?.severity??r.definition.severity,choices:Object.freeze([...r.definition.choices]),escalationStages:r.definition.escalationStages?Object.freeze([...r.definition.escalationStages]):undefined,activationGameMs:r.activationGameMs,activationSequence:r.activationSequence,ageGameMinutes:Math.max(0,Math.floor((this.currentGameMs-r.activationGameMs)/60000)),status:r.status,stageIndex:r.stageIndex,nextEscalationGameMs:r.nextEscalationGameMs});}
 private recordHandled(definition:InterruptionDefinition):void{const key=definition.deduplicationKey??definition.id;this.cooldownUntilGameMs[key]=this.currentGameMs+(definition.cooldownGameMs??0);if(definition.category==='production'||definition.category==='tooling')this.incidentCounts[definition.id]=(this.incidentCounts[definition.id]??0)+1;}
 private notify():void{const snapshot=this.snapshot;this.observers.forEach(o=>o(snapshot));}
}
