import { BoosterSession,type BoosterId } from './BoosterSession';
import { CodingDisruptionLedger } from './CodingDisruptionLedger';
import { CodingSession } from './CodingSession';
import { ConsequenceQueue } from './ConsequenceQueue';
import { DayState,type ResourceValues } from './DayState';
import { EffectEngine } from './EffectEngine';
import { EngineeringTaskQueue } from './EngineeringTaskQueue';
import { EventScheduler,type ScheduledCandidate } from './EventScheduler';
import { PlayerNeeds,type NeedId } from './PlayerNeeds';
import { activePacingBand,type PacingBandId,type PacingProfile } from './WorkdayPacing';
import { createRunContext,InterruptionSession,type TransitionBatch } from './interruptions';
import type { ConsequenceFeedback } from './effects';
import { ENGINEERING_TASKS } from '../content/engineeringTasks';
import { INTERRUPTION_CATALOG } from '../content/poTeamInterruptions';

export type PlayerAction = Readonly<{type:'code'}|{type:'resolve-interruption';interruptionId:string;choiceId:string}|{type:'resolve-task';choiceId:string}|{type:'switch-task';taskId:string}|{type:'bathroom'}|{type:'booster';boosterId:BoosterId}>;
export interface WorkdayDebugSnapshot {readonly profile:PacingProfile['id'];readonly seed:number;readonly activeBand:PacingBandId;readonly eventPressure:number;readonly quietDurationGameMs:number;readonly resources:ResourceValues;readonly needs:Readonly<Record<NeedId,number>>}
export interface WorkdaySessionMetrics {readonly spawns:readonly Readonly<{id:string;band:PacingBandId;atGameMs:number}>[];readonly resolutions:readonly Readonly<{id:string;band:PacingBandId;atGameMs:number}>[];readonly criticalWindows:readonly Readonly<{need:NeedId;atGameMs:number}>[];readonly recoveryWindows:readonly Readonly<{action:string;atGameMs:number}>[];readonly boosterUse:Readonly<Record<BoosterId,number>>;readonly maximumQuietGameMs:number;readonly peakPressure:number}

export class WorkdaySession {
    readonly workday:DayState;readonly coding:CodingSession;readonly taskQueue:EngineeringTaskQueue;readonly playerNeeds:PlayerNeeds;readonly boosters:BoosterSession;readonly interruptions:InterruptionSession;readonly scheduler:EventScheduler;readonly consequenceQueue:ConsequenceQueue;readonly disruptions:CodingDisruptionLedger;readonly effectEngine:EffectEngine;
    private spawns:{id:string;band:PacingBandId;atGameMs:number}[]=[];private resolutions:{id:string;band:PacingBandId;atGameMs:number}[]=[];private criticalWindows:{need:NeedId;atGameMs:number}[]=[];private recoveryWindows:{action:string;atGameMs:number}[]=[];private peakPressure=0;private maximumQuietGameMs=0;
    constructor(readonly profile:PacingProfile,readonly seed:number,feedback:(record:ConsequenceFeedback)=>void=()=>{}){
        if(!Number.isInteger(seed))throw new TypeError('Workday seed must be an integer.');
        const balance=profile.balance;this.workday=new DayState({gameMinutesPerRealSecond:profile.gameMinutesPerRealSecond,initialResources:balance.initialResources});this.coding=new CodingSession({workPerGameMinute:balance.taskWorkPerGameMinute,staminaPerGameMinute:balance.codingStaminaPerGameMinute});this.taskQueue=new EngineeringTaskQueue(ENGINEERING_TASKS);this.playerNeeds=new PlayerNeeds({bathroomGameMinutes:balance.bathroomGameMinutes,bathroomFocusReduction:balance.bathroomFocusReduction},0,profile);this.boosters=new BoosterSession({boosters:{coffee:{staminaRestoration:balance.coffeeStaminaRestoration},cokeZero:{staminaRestoration:balance.cokeZeroStaminaRestoration,toiletNeedIncrease:balance.cokeZeroToiletIncrease}}},seed+2);this.consequenceQueue=new ConsequenceQueue();this.disruptions=new CodingDisruptionLedger();
        this.interruptions=new InterruptionSession(INTERRUPTION_CATALOG,0,false,()=>this.workday.snapshot.resources.technicalDebt,(delay,due)=>delay/activePacingBand(profile,due).escalationPressure);
        this.scheduler=new EventScheduler(INTERRUPTION_CATALOG,{minimumSpawnIntervalMs:20*60_000,maximumSpawnIntervalMs:35*60_000,activeLimit:3,endGameMs:(17-9)*60*60_000,pacingProfile:profile},seed);
        this.effectEngine=new EffectEngine({mutateResource:(key,amount)=>this.workday.mutateResource(key,amount),reduceFocus:amount=>this.coding.reduceFocus(amount),reduceTaskProgress:amount=>this.taskQueue.reduceSelectedProgress(amount),disruptions:this.disruptions,queue:this.consequenceQueue,gameTime:()=>this.workday.snapshot.elapsedGameMs,technicalDebt:()=>this.workday.snapshot.resources.technicalDebt,feedback,consequenceConcluded:id=>this.interruptions.recordConcludedConsequence(id)},seed+1);
        this.synchronizeAvailability();
    }
    get metrics():WorkdaySessionMetrics{return Object.freeze({spawns:Object.freeze(this.spawns.map(item=>Object.freeze({...item}))),resolutions:Object.freeze(this.resolutions.map(item=>Object.freeze({...item}))),criticalWindows:Object.freeze(this.criticalWindows.map(item=>Object.freeze({...item}))),recoveryWindows:Object.freeze(this.recoveryWindows.map(item=>Object.freeze({...item}))),boosterUse:this.boosters.snapshot.consumptionCounts,maximumQuietGameMs:this.maximumQuietGameMs,peakPressure:this.peakPressure});}
    get debugSnapshot():WorkdayDebugSnapshot{const day=this.workday.snapshot,needs=this.playerNeeds.snapshot,scheduler=this.scheduler.snapshot;return Object.freeze({profile:this.profile.id,seed:this.seed,activeBand:activePacingBand(this.profile,day.elapsedGameMs).id,eventPressure:scheduler.pressure,quietDurationGameMs:scheduler.quietDurationGameMs,resources:day.resources,needs:Object.freeze({sleepiness:needs.sleepiness.value,toilet:needs.toilet.value})});}
    legalActions():readonly PlayerAction[]{
        const day=this.workday.snapshot,task=this.taskQueue.snapshot,intr=this.interruptions.snapshot,actions:PlayerAction[]=[];
        if(intr.openInterruption){for(const choice of intr.openInterruption.choices)actions.push(Object.freeze({type:'resolve-interruption',interruptionId:intr.openInterruption.id,choiceId:choice.id}));return Object.freeze(actions);}
        if(task.pendingDecision){for(const choice of task.pendingDecision.definition.choices)actions.push(Object.freeze({type:'resolve-task',choiceId:choice.id}));return Object.freeze(actions);}
        if(!day.isDayComplete&&task.selectedTask&&day.resources.stamina>0)actions.push(Object.freeze({type:'code'}));
        task.tasks.filter(item=>!item.isComplete&&!item.isSelected).forEach(item=>actions.push(Object.freeze({type:'switch-task',taskId:item.id})));
        if(!day.isDayComplete)actions.push(Object.freeze({type:'bathroom'}));
        this.boosters.synchronize(this.boosterContext());for(const id of ['coffee','cokeZero'] as const)if(this.boosters.snapshot.availability[id].available)actions.push(Object.freeze({type:'booster',boosterId:id}));
        return Object.freeze(actions);
    }
    perform(action:PlayerAction,stepGameMs=this.profile.simulationStepGameMs):void{
        const legal=this.legalActions();if(!legal.some(item=>JSON.stringify(item)===JSON.stringify(action)))throw new Error(`Player policy selected illegal or non-progressing action: ${JSON.stringify(action)}.`);
        if(action.type==='code'){this.coding.requestCoding(true);this.advanceGameMs(Math.min(stepGameMs,60_000));return;}
        if(action.type==='switch-task'){this.taskQueue.select(action.taskId);this.coding.reduceFocus(.2);this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);return;}
        if(action.type==='bathroom'){this.coding.reduceFocus(this.playerNeeds.config.bathroomFocusReduction);this.advanceGameMs(this.playerNeeds.config.bathroomGameMinutes*60_000);this.playerNeeds.relieve('toilet');this.recoveryWindows.push({action:'bathroom',atGameMs:this.workday.snapshot.elapsedGameMs});this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);return;}
        if(action.type==='booster'){const activation=this.boosters.activate(action.boosterId,this.boosterContext());if(!activation.result)throw new Error('Legal booster activation did not progress.');this.workday.mutateResource('stamina',activation.result.staminaRestoration);if(activation.result.toiletNeedIncrease)this.playerNeeds.mutateNeed('toilet',activation.result.toiletNeedIncrease);this.recoveryWindows.push({action:action.boosterId,atGameMs:this.workday.snapshot.elapsedGameMs});this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);return;}
        if(action.type==='resolve-task'){const choice=this.taskQueue.resolvePendingDecision(action.choiceId);if(!choice)throw new Error('Task decision did not progress.');this.workday.resume('task-decision');this.advanceGameMs(choice.gameMinutes*60_000);this.effectEngine.execute(choice.effects,`task:${choice.id}`);this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);return;}
        const pending=this.interruptions.beginResolution(action.choiceId);if(!pending||pending.interruptionId!==action.interruptionId)throw new Error('Interruption decision did not progress.');this.advanceGameMs(pending.choice.gameMinutes*60_000);this.effectEngine.execute(pending.choice.effects,pending.interruptionId);this.interruptions.finalizeResolution(pending.interruptionId);this.resolutions.push({id:pending.interruptionId,band:activePacingBand(this.profile,this.workday.snapshot.elapsedGameMs).id,atGameMs:this.workday.snapshot.elapsedGameMs});this.scheduler.resolved(pending.interruptionId,c=>this.activate(c));this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);this.workday.resume('interruption-decision');this.synchronize();
    }
    advanceRealMs(realMs:number):void{const before=this.workday.snapshot.elapsedGameMs;this.workday.advance(realMs);this.advanceSystems(this.workday.snapshot.elapsedGameMs-before);}
    advanceGameMs(gameMs:number):void{if(!Number.isFinite(gameMs)||gameMs<0)throw new RangeError('Game step must be finite and non-negative.');const before=this.workday.snapshot.elapsedGameMs;this.workday.spendGameMinutes(gameMs/60_000);this.advanceSystems(this.workday.snapshot.elapsedGameMs-before);}
    reset():void{this.workday.reset();this.coding.cancelCoding();this.taskQueue.reset();this.playerNeeds.reset();this.boosters.reset();this.interruptions.reset();this.scheduler.reset();this.effectEngine.reset();this.spawns=[];this.resolutions=[];this.criticalWindows=[];this.recoveryWindows=[];this.peakPressure=0;this.maximumQuietGameMs=0;this.synchronizeAvailability();}
    private advanceSystems(elapsedGameMs:number):void{this.synchronize();const coding=this.coding.update(elapsedGameMs,this.workday.snapshot.resources.stamina,this.taskQueue.nextWorkBoundary());if(coding.staminaCost)this.workday.mutateResource('stamina',-coding.staminaCost);if(coding.workProduced){const result=this.taskQueue.applyWork(coding.workProduced);if(result.completionEffects.length)this.effectEngine.execute(result.completionEffects,result.completedTaskId!);if(result.decisionOpened)this.workday.pause('task-decision');}this.synchronizeAvailability();}
    private synchronize():void{const now=this.workday.snapshot.elapsedGameMs;const needs=this.playerNeeds.synchronize(now);if(needs.additionalStaminaCost)this.workday.mutateResource('stamina',-needs.additionalStaminaCost);for(const transition of needs.transitions){if(transition.criticalEffect){this.criticalWindows.push({need:transition.need,atGameMs:transition.atGameMs});this.coding.reduceFocus(transition.criticalEffect.focusReduction);if(transition.criticalEffect.staminaCost)this.workday.mutateResource('stamina',-transition.criticalEffect.staminaCost);}}
        this.scheduler.synchronize(now,c=>this.activate(c),this.context());let batch=this.interruptions.setCurrentGameMs(now),guard=0;while(batch.length){if(++guard>1000)throw new Error('Workday synchronization transition limit exceeded.');this.applyTransitions(batch);batch=this.interruptions.setCurrentGameMs(now);}this.effectEngine.synchronize(now);this.disruptions.synchronize(now);this.maximumQuietGameMs=Math.max(this.maximumQuietGameMs,this.scheduler.snapshot.quietDurationGameMs);this.peakPressure=Math.max(this.peakPressure,this.scheduler.snapshot.pressure);if(this.interruptions.snapshot.active.length&&!this.interruptions.snapshot.openInterruption){const first=this.interruptions.snapshot.active[0]!;if(this.interruptions.open(first.id))this.workday.pause('interruption-decision');}this.synchronizeAvailability();}
    private activate(candidate:ScheduledCandidate):boolean{const activated=this.interruptions.activate(candidate.definitionId,candidate.dueGameMs,candidate.sequence);if(activated)this.spawns.push({id:candidate.definitionId,band:activePacingBand(this.profile,candidate.dueGameMs).id,atGameMs:candidate.dueGameMs});return activated;}
    private applyTransitions(batch:TransitionBatch):void{for(const item of batch){this.effectEngine.execute(item.effects,item.interruptionId);for(const follow of item.followUpIds)this.scheduler.enqueueFollowUp(follow,item.deadlineGameMs,c=>this.activate(c));}}
    private context(){const day=this.workday.snapshot,tasks=this.taskQueue.snapshot,history=this.interruptions.snapshot,needs=this.playerNeeds.snapshot,boosters=this.boosters.snapshot;const stage=(id:NeedId)=>this.playerNeeds.config.needs[id].stages.findIndex(item=>item.id===needs[id].stage.id);return createRunContext({selectedTaskId:tasks.selectedTaskId,completedTaskIds:tasks.completedTaskIds,resolvedEventIds:history.resolvedIds,resolvedChoices:history.resolvedOutcomes,resources:day.resources,needStages:{sleepiness:stage('sleepiness'),toilet:stage('toilet')},boosterCounts:boosters.consumptionCounts,incidentCounts:history.incidentCounts,concludedConsequenceIds:history.concludedConsequenceIds,activeDeduplicationKeys:history.active.map(item=>item.deduplicationKey??item.id),cooldownUntilGameMs:history.cooldownUntilGameMs,currentGameMs:day.elapsedGameMs});}
    private boosterContext(){const day=this.workday.snapshot;return {elapsedGameMs:day.elapsedGameMs,stamina:day.resources.stamina,isDecisionOpen:Boolean(this.interruptions.snapshot.openInterruption||this.taskQueue.snapshot.pendingDecision),isDayComplete:day.isDayComplete};}
    private synchronizeAvailability():void{const day=this.workday.snapshot,needs=this.playerNeeds.snapshot;this.coding.setRuntimeModifiers({codingSpeed:Math.min(needs.codingSpeedModifier,this.disruptions.snapshot.effectiveSpeedFactor),focusGain:needs.focusGainModifier});this.coding.synchronizeAvailability(!day.isPaused&&!day.isDayComplete,day.resources.stamina,Boolean(this.taskQueue.snapshot.selectedTask)&&!this.taskQueue.snapshot.pendingDecision);}
}
