import { RESOURCE_KEYS,type ResourceKey } from './DayState';
import type { NeedId } from './PlayerNeeds';
import { PACING_BAND_IDS,WORKDAY_DURATION_MS,type PacingBandId,type PacingProfile } from './WorkdayPacing';
import { WorkdaySession,type PlayerAction,type WorkdayDebugSnapshot } from './WorkdaySession';

export interface PlayerPolicy {readonly id:string;choose(actions:readonly PlayerAction[],snapshot:WorkdayDebugSnapshot):PlayerAction}
export interface BandReport {readonly spawns:number;readonly resolutions:number}
export interface SimulationReport {readonly profile:PacingProfile['id'];readonly seed:number;readonly policy:string;readonly stepGameMs:number;readonly elapsedGameMs:number;readonly elapsedRealMs:number;readonly bands:Readonly<Record<PacingBandId,BandReport>>;readonly maximumQuietGameMs:number;readonly peakPressure:number;readonly floodDeferrals:number;readonly emptyQuietEvaluations:number;readonly resourceExtrema:Readonly<Record<ResourceKey,Readonly<{minimum:number;maximum:number}>>>;readonly needExtrema:Readonly<Record<NeedId,Readonly<{minimum:number;maximum:number}>>>;readonly criticalWindows:readonly Readonly<{need:NeedId;atGameMs:number}>[];readonly recoveryWindows:readonly Readonly<{action:string;atGameMs:number}>[];readonly taskProgress:Readonly<Record<string,number>>;readonly completedTaskIds:readonly string[];readonly boosterUse:Readonly<Record<'coffee'|'cokeZero',number>>;readonly terminal:WorkdayDebugSnapshot;readonly result:NonNullable<WorkdaySession['result']>}

const first=(actions:readonly PlayerAction[],type:PlayerAction['type'])=>actions.find(item=>item.type===type);
const aiProgress=(actions:readonly PlayerAction[],mode:'prompt'|'plan')=>first(actions,'approve-ai')??first(actions,'wait-ai')??actions.find(item=>item.type==='start-ai'&&item.mode===mode);
export const REPRESENTATIVE_POLICIES:Readonly<Record<'balanced'|'productive'|'risky',PlayerPolicy>>=Object.freeze({
    balanced:Object.freeze({id:'balanced',choose:(actions:readonly PlayerAction[],snapshot:WorkdayDebugSnapshot)=>first(actions,'resolve-interruption')??first(actions,'resolve-task')??(snapshot.needs.toilet>=72?first(actions,'bathroom'):undefined)??(snapshot.resources.stamina<=35?first(actions,'booster'):undefined)??aiProgress(actions,'plan')??actions[0]!}),
    productive:Object.freeze({id:'productive',choose:(actions:readonly PlayerAction[])=>first(actions,'resolve-interruption')??first(actions,'resolve-task')??aiProgress(actions,'prompt')??first(actions,'booster')??actions[0]!}),
    risky:Object.freeze({id:'risky',choose:(actions:readonly PlayerAction[])=>[...actions].reverse().find(item=>item.type==='resolve-interruption'||item.type==='resolve-task')??aiProgress(actions,'prompt')??actions[actions.length-1]!})
});
export const BALANCE_SEEDS=Object.freeze([20260906,4821,3178,911] as const);
export const BALANCE_MATRIX=Object.freeze(BALANCE_SEEDS.flatMap(seed=>Object.values(REPRESENTATIVE_POLICIES).map(policy=>Object.freeze({seed,policy:policy.id}))));

export function runWorkdaySimulation(input:{readonly profile:PacingProfile;readonly seed:number;readonly stepGameMs?:number;readonly policy:PlayerPolicy}):SimulationReport{
    if(!Number.isInteger(input.seed))throw new TypeError('Simulation seed must be an integer.');const step=input.stepGameMs??input.profile.simulationStepGameMs;if(!Number.isFinite(step)||step<=0)throw new RangeError('Simulation time step must be finite and positive.');if(!input.policy?.id.trim()||typeof input.policy.choose!=='function')throw new TypeError('Simulation requires a named deterministic player policy.');
    const session=new WorkdaySession(input.profile,input.seed),resourceExtrema={} as Record<ResourceKey,{minimum:number;maximum:number}>,needExtrema={} as Record<NeedId,{minimum:number;maximum:number}>;for(const key of RESOURCE_KEYS){const value=session.workday.snapshot.resources[key];resourceExtrema[key]={minimum:value,maximum:value};}for(const id of ['sleepiness','toilet'] as const){const value=session.playerNeeds.snapshot[id].value;needExtrema[id]={minimum:value,maximum:value};}
    let iterations=0;while(!session.workday.snapshot.isDayComplete){if(++iterations>10000)throw new Error(`Player policy ${input.policy.id} failed to reach 17:00.`);const actions=session.legalActions();if(!actions.length)throw new Error(`Player policy ${input.policy.id} has no legal progressing action at ${session.workday.snapshot.elapsedGameMs}.`);const action=input.policy.choose(actions,session.debugSnapshot);if(!action)throw new Error(`Player policy ${input.policy.id} returned no action.`);session.perform(action,Math.min(step,WORKDAY_DURATION_MS-session.workday.snapshot.elapsedGameMs));for(const key of RESOURCE_KEYS){const value=session.workday.snapshot.resources[key];resourceExtrema[key].minimum=Math.min(resourceExtrema[key].minimum,value);resourceExtrema[key].maximum=Math.max(resourceExtrema[key].maximum,value);}for(const id of ['sleepiness','toilet'] as const){const value=session.playerNeeds.snapshot[id].value;needExtrema[id].minimum=Math.min(needExtrema[id].minimum,value);needExtrema[id].maximum=Math.max(needExtrema[id].maximum,value);}}
    const bands=Object.fromEntries(PACING_BAND_IDS.map(id=>[id,Object.freeze({spawns:session.metrics.spawns.filter(x=>x.band===id).length,resolutions:session.metrics.resolutions.filter(x=>x.band===id).length})])) as unknown as Record<PacingBandId,BandReport>,tasks=session.taskQueue.snapshot;
    const result=session.result??session.finalize();if(!result)throw new Error('Simulation reached terminal time without a result.');return Object.freeze({profile:input.profile.id,seed:input.seed,policy:input.policy.id,stepGameMs:step,elapsedGameMs:session.workday.snapshot.elapsedGameMs,elapsedRealMs:WORKDAY_DURATION_MS/(input.profile.gameMinutesPerRealSecond*60),bands:Object.freeze(bands),maximumQuietGameMs:session.metrics.maximumQuietGameMs,peakPressure:session.metrics.peakPressure,floodDeferrals:session.scheduler.snapshot.floodDeferrals,emptyQuietEvaluations:session.scheduler.snapshot.emptyQuietEvaluations,resourceExtrema:Object.freeze(Object.fromEntries(RESOURCE_KEYS.map(key=>[key,Object.freeze(resourceExtrema[key])]))) as typeof resourceExtrema,needExtrema:Object.freeze({sleepiness:Object.freeze(needExtrema.sleepiness),toilet:Object.freeze(needExtrema.toilet)}),criticalWindows:session.metrics.criticalWindows,recoveryWindows:session.metrics.recoveryWindows,taskProgress:Object.freeze(Object.fromEntries(tasks.tasks.map(item=>[item.id,item.progress]))),completedTaskIds:tasks.completedTaskIds,boosterUse:session.metrics.boosterUse,terminal:session.debugSnapshot,result});
}
