import {BoosterSession,type BoosterId} from './BoosterSession';
import {ConsequenceQueue} from './ConsequenceQueue';
import {DayState,type ResourceValues} from './DayState';
import {EffectEngine} from './EffectEngine';
import {EventScheduler,type ScheduledCandidate} from './EventScheduler';
import {PlayerNeeds,type NeedId} from './PlayerNeeds';
import {activePacingBand,WORKDAY_DURATION_MS,type PacingBandId,type PacingProfile} from './WorkdayPacing';
import {createRunContext,InterruptionSession,matchesEligibility,validateInterruptionCatalog,type CaseOutcome,type InterruptionDefinition,type TransitionBatch} from './interruptions';
import type {ConsequenceFeedback} from './effects';
import {INTERRUPTION_CATALOG} from '../content/stickyCases';
import {createTerminalEvidence,evaluateTerminalEvidence,type CollapseCause,type EvaluatedResult,type TerminalResolutionEvidence} from './EndOfDayResults';

export type PlayerAction=Readonly<{type:'resolve-interruption';interruptionId:string;choiceId:string}>;
export interface PendingCaseFollowUp{readonly eventId:string;readonly dueGameMs:number;readonly sequence:number;readonly sourceEventId:string}
export interface CaseSnapshot{readonly statuses:Readonly<Record<string,'open'|CaseOutcome>>;readonly resolvedCaseIds:readonly string[];readonly failedCaseIds:readonly string[];readonly pendingFollowUps:readonly PendingCaseFollowUp[]}
export interface WorkdayDebugSnapshot{readonly profile:PacingProfile['id'];readonly seed:number;readonly dayIndex:number;readonly healthRisk:number;readonly activeBand:PacingBandId;readonly eventPressure:number;readonly quietDurationGameMs:number;readonly resources:ResourceValues;readonly needs:Readonly<Record<NeedId,number>>;readonly resolvedCaseIds:readonly string[];readonly failedCaseIds:readonly string[]}
export interface WorkdaySessionMetrics{readonly spawns:readonly Readonly<{id:string;band:PacingBandId;atGameMs:number}>[];readonly resolutions:readonly Readonly<{id:string;band:PacingBandId;atGameMs:number}>[];readonly criticalWindows:readonly Readonly<{need:NeedId;atGameMs:number}>[];readonly recoveryWindows:readonly Readonly<{action:string;atGameMs:number}>[];readonly boosterUse:Readonly<Record<BoosterId,number>>;readonly maximumQuietGameMs:number;readonly peakPressure:number}
export type WorkdayLifecycle='active'|'day-transition'|'collapsed'|'results';

export class WorkdaySession{
 readonly workday:DayState;readonly playerNeeds:PlayerNeeds;readonly boosters:BoosterSession;readonly interruptions:InterruptionSession;readonly scheduler:EventScheduler;readonly consequenceQueue:ConsequenceQueue;readonly effectEngine:EffectEngine;
 private readonly definitions=new Map<string,InterruptionDefinition>();private caseStatuses:Record<string,'open'|CaseOutcome>={};private pendingFollowUps:PendingCaseFollowUp[]=[];private nextFollowUpSequence=0;
 private spawns:{id:string;band:PacingBandId;atGameMs:number}[]=[];private resolutions:{id:string;band:PacingBandId;atGameMs:number}[]=[];private criticalWindows:{need:NeedId;atGameMs:number}[]=[];private recoveryWindows:{action:string;atGameMs:number}[]=[];private peakPressure=0;private maximumQuietGameMs=0;private lifecycleState:WorkdayLifecycle='active';private terminalResult:EvaluatedResult|null=null;private completedOvernights=0;private causalSource='passive pressure';
 constructor(readonly profile:PacingProfile,readonly seed:number,feedback:(record:ConsequenceFeedback)=>void=()=>{},private readonly autoOpenInterruptions=true,definitions:readonly InterruptionDefinition[]=INTERRUPTION_CATALOG){
  if(!Number.isInteger(seed))throw new TypeError('Workday seed must be an integer.');validateInterruptionCatalog(definitions);definitions.forEach(d=>this.definitions.set(d.id,d));for(const d of definitions)if(d.caseId)this.caseStatuses[d.caseId]='open';
  const b=profile.balance;this.workday=new DayState({gameMinutesPerRealSecond:profile.gameMinutesPerRealSecond,initialResources:b.initialResources,continuous:true});this.playerNeeds=new PlayerNeeds({},0,profile);this.boosters=new BoosterSession({boosters:{coffee:{staminaRestoration:b.coffeeStaminaRestoration},cokeZero:{staminaRestoration:b.cokeZeroStaminaRestoration,toiletNeedIncrease:b.cokeZeroToiletIncrease}}},seed+2);this.consequenceQueue=new ConsequenceQueue();
  this.interruptions=new InterruptionSession(definitions,0,false,()=>this.workday.snapshot.resources.technicalDebt,(delay,due)=>{const day=Math.floor(due/WORKDAY_DURATION_MS)+1;return delay/activePacingBand(profile,due).escalationPressure*Math.max(profile.dayScaling.minimumEscalationMultiplier,Math.pow(profile.dayScaling.intervalMultiplier,day-1));});
  this.scheduler=new EventScheduler(definitions,{minimumSpawnIntervalMs:20*60_000,maximumSpawnIntervalMs:35*60_000,activeLimit:64,endGameMs:Number.MAX_SAFE_INTEGER,pacingProfile:profile,initialSpawnGameMs:definitions===INTERRUPTION_CATALOG?0:undefined},seed);
  this.effectEngine=new EffectEngine({mutateResource:(key,amount)=>this.workday.mutateResource(key,amount),relieveNeed:(need,value)=>{this.playerNeeds.relieve(need,value);this.recoveryWindows.push({action:need==='toilet'?'bathroom':'microbreak',atGameMs:this.workday.snapshot.elapsedGameMs});},consumeBooster:id=>this.consumeBooster(id),queue:this.consequenceQueue,gameTime:()=>this.workday.snapshot.elapsedGameMs,technicalDebt:()=>this.workday.snapshot.resources.technicalDebt,feedback,consequenceConcluded:id=>this.interruptions.recordConcludedConsequence(id)},seed+1);
  this.synchronize();
 }
 get lifecycle():WorkdayLifecycle{return this.lifecycleState;}get result():EvaluatedResult|null{return this.terminalResult;}
 get cases():CaseSnapshot{const resolved=Object.keys(this.caseStatuses).filter(id=>this.caseStatuses[id]==='resolved'),failed=Object.keys(this.caseStatuses).filter(id=>this.caseStatuses[id]==='failed');return Object.freeze({statuses:Object.freeze({...this.caseStatuses}),resolvedCaseIds:Object.freeze(resolved),failedCaseIds:Object.freeze(failed),pendingFollowUps:Object.freeze(this.pendingFollowUps.map(x=>Object.freeze({...x})))});}
 get metrics():WorkdaySessionMetrics{return Object.freeze({spawns:Object.freeze(this.spawns.map(x=>Object.freeze({...x}))),resolutions:Object.freeze(this.resolutions.map(x=>Object.freeze({...x}))),criticalWindows:Object.freeze(this.criticalWindows.map(x=>Object.freeze({...x}))),recoveryWindows:Object.freeze(this.recoveryWindows.map(x=>Object.freeze({...x}))),boosterUse:this.boosters.snapshot.consumptionCounts,maximumQuietGameMs:this.maximumQuietGameMs,peakPressure:this.peakPressure});}
 get healthRisk():number{const c=this.boosters.snapshot.consumptionCounts;return Math.max(0,c.coffee*this.profile.healthRisk.coffee+c.cokeZero*this.profile.healthRisk.cokeZero-this.completedOvernights*this.profile.overnight.healthRiskRecovery);}
 get debugSnapshot():WorkdayDebugSnapshot{const d=this.workday.snapshot,n=this.playerNeeds.snapshot,s=this.scheduler.snapshot,c=this.cases;return Object.freeze({profile:this.profile.id,seed:this.seed,dayIndex:d.dayIndex,healthRisk:this.healthRisk,activeBand:activePacingBand(this.profile,d.elapsedGameMs).id,eventPressure:s.pressure+this.pendingFollowUps.length,quietDurationGameMs:s.quietDurationGameMs,resources:d.resources,needs:Object.freeze({sleepiness:n.sleepiness.value,toilet:n.toilet.value}),resolvedCaseIds:c.resolvedCaseIds,failedCaseIds:c.failedCaseIds});}
 legalActions():readonly PlayerAction[]{const open=this.interruptions.snapshot.openInterruption;if(this.lifecycleState!=='active'||!open)return Object.freeze([]);return Object.freeze(open.choices.map(c=>Object.freeze({type:'resolve-interruption' as const,interruptionId:open.id,choiceId:c.id})));}
 openInterruption(id:string):boolean{return this.interruptions.open(id);}
 perform(action:PlayerAction):void{if(!this.legalActions().some(a=>a.interruptionId===action.interruptionId&&a.choiceId===action.choiceId))throw new Error(`Player selected illegal action: ${JSON.stringify(action)}.`);const pending=this.interruptions.beginResolution(action.choiceId);if(!pending||pending.interruptionId!==action.interruptionId)throw new Error('Sticky decision did not progress.');this.advanceGameMs(pending.choice.gameMinutes*60_000,true);this.effectEngine.execute(pending.choice.effects,pending.interruptionId);this.interruptions.finalizeResolution(pending.interruptionId);const definition=this.definitions.get(pending.interruptionId)!;if(definition.caseId&&pending.choice.caseOutcome&&this.caseStatuses[definition.caseId]==='open')this.caseStatuses[definition.caseId]=pending.choice.caseOutcome;for(const follow of pending.choice.followUps??[])this.scheduleFollowUp(follow.eventId,this.workday.snapshot.elapsedGameMs+follow.delayGameMs,pending.interruptionId);this.resolutions.push({id:pending.interruptionId,band:activePacingBand(this.profile,this.workday.snapshot.elapsedGameMs).id,atGameMs:this.workday.snapshot.elapsedGameMs});this.scheduler.resolved(pending.interruptionId,c=>this.activate(c));this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);this.causalSource=pending.interruptionId;this.synchronize();this.finalize(pending.interruptionId);}
 scheduleFollowUp(eventId:string,dueGameMs:number,sourceEventId='manual'):boolean{if(!this.definitions.has(eventId))throw new TypeError(`Unknown follow-up ${eventId}.`);if(!Number.isFinite(dueGameMs)||dueGameMs<0)throw new RangeError('Follow-up time must be finite and non-negative.');if(this.pendingFollowUps.some(x=>x.eventId===eventId&&x.sourceEventId===sourceEventId)||this.interruptions.snapshot.active.some(x=>x.id===eventId))return false;this.pendingFollowUps.push(Object.freeze({eventId,dueGameMs,sequence:this.nextFollowUpSequence++,sourceEventId}));this.activateDueFollowUps();return true;}
 advanceRealMs(realMs:number):void{if(this.lifecycleState!=='active'||this.workday.snapshot.isPaused||!Number.isFinite(realMs)||realMs<=0)return;this.advanceGameMs(realMs*this.profile.gameMinutesPerRealSecond*60);}
 advanceGameMs(gameMs:number,deferCollapse=false):void{if(!Number.isFinite(gameMs)||gameMs<0)throw new RangeError('Game step must be finite and non-negative.');if(this.lifecycleState!=='active')return;let remaining=gameMs;while(remaining>0&&this.lifecycleState==='active'){const now=this.workday.snapshot.elapsedGameMs,dayBoundary=(Math.floor(now/WORKDAY_DURATION_MS)+1)*WORKDAY_DURATION_MS,nextFollow=this.pendingFollowUps.reduce((n,x)=>Math.min(n,x.dueGameMs),Infinity),boundary=Math.min(dayBoundary,nextFollow),step=Math.min(remaining,Math.max(0,boundary-now));if(step>0){this.workday.spendGameMinutes(step/60_000);remaining-=step;this.advanceSystems(step);}else this.synchronize();if(!deferCollapse)this.finalize(this.causalSource);if(this.terminalResult)break;if(this.workday.snapshot.elapsedGameMs===dayBoundary)this.beginNextDay();if(step===0&&boundary===Infinity)break;}}
 finalize(causalSource=this.causalSource):EvaluatedResult|null{if(this.terminalResult)return this.terminalResult;const day=this.workday.snapshot,causes=this.collapseCauses();if(!causes.length)return null;this.lifecycleState='collapsed';const needs=this.playerNeeds.snapshot,history=this.interruptions.snapshot,cases=this.cases,resolutions=history.resultOutcomes.map(x=>({eventId:x.eventId,choiceId:x.choiceId,category:x.category??'personal',incidentControl:x.incidentControl,resultKarma:x.resultKarma})) as TerminalResolutionEvidence[],resolvedIncidentIds=resolutions.filter(r=>(r.category==='production'||r.category==='tooling')&&r.incidentControl==='player-fixable').map(r=>r.eventId);this.terminalResult=evaluateTerminalEvidence(createTerminalEvidence({elapsedGameMs:day.elapsedGameMs,dayIndex:day.dayIndex,dayElapsedGameMs:day.dayElapsedGameMs,resources:day.resources,needs:{sleepiness:needs.sleepiness.value,toilet:needs.toilet.value},healthRisk:this.healthRisk,collapseCauses:causes,causalSource,activeInterruptionIds:history.active.map(x=>x.id),resolvedCaseIds:cases.resolvedCaseIds,failedCaseIds:cases.failedCaseIds,resolutions,resolvedIncidentIds,criticalNeedEpisodes:{sleepiness:this.criticalWindows.filter(x=>x.need==='sleepiness').length,toilet:this.criticalWindows.filter(x=>x.need==='toilet').length},boosterCounts:this.boosters.snapshot.consumptionCounts}));this.lifecycleState='results';return this.terminalResult;}
 reset():void{this.workday.reset();this.playerNeeds.reset();this.boosters.reset();this.interruptions.reset();this.scheduler.reset();this.effectEngine.reset();this.caseStatuses={};for(const d of this.definitions.values())if(d.caseId)this.caseStatuses[d.caseId]='open';this.pendingFollowUps=[];this.nextFollowUpSequence=0;this.spawns=[];this.resolutions=[];this.criticalWindows=[];this.recoveryWindows=[];this.peakPressure=0;this.maximumQuietGameMs=0;this.lifecycleState='active';this.terminalResult=null;this.completedOvernights=0;this.causalSource='passive pressure';this.synchronize();}
 private advanceSystems(ms:number):void{const minutes=ms/60_000,active=this.interruptions.snapshot.active;if(minutes){this.workday.mutateResource('stamina',-minutes*(.08+active.length*.015));this.workday.mutateResource('poHappiness',-minutes*active.filter(x=>x.category==='product-owner'||x.category==='teammate').length*.025);this.workday.mutateResource('systemStability',-minutes*active.filter(x=>x.category==='production'||x.category==='tooling').length*.025);}this.synchronize();}
 private synchronize():void{const now=this.workday.snapshot.elapsedGameMs,needs=this.playerNeeds.synchronize(now);if(needs.additionalStaminaCost)this.workday.mutateResource('stamina',-needs.additionalStaminaCost);for(const t of needs.transitions){const index=this.playerNeeds.config.needs[t.need].stages.findIndex(s=>s.id===t.nextStage.id);if(index>=2){this.interruptions.activate(t.need==='toilet'?'need-bathroom':'need-sleepiness',t.atGameMs);if(index===4)this.criticalWindows.push({need:t.need,atGameMs:t.atGameMs});}}this.activateDueFollowUps();this.scheduler.cancelIneligible(this.context());this.scheduler.synchronize(now,c=>this.activate(c),this.context());let batch=this.interruptions.setCurrentGameMs(now),guard=0;while(batch.length){if(++guard>1000)throw new Error('Synchronization transition limit exceeded.');this.applyTransitions(batch);batch=this.interruptions.setCurrentGameMs(now);}this.effectEngine.synchronize(now);this.maximumQuietGameMs=Math.max(this.maximumQuietGameMs,this.scheduler.snapshot.quietDurationGameMs);this.peakPressure=Math.max(this.peakPressure,this.scheduler.snapshot.pressure+this.pendingFollowUps.length);if(this.autoOpenInterruptions&&!this.interruptions.snapshot.openInterruption){const first=this.interruptions.snapshot.active[0];if(first)this.interruptions.open(first.id);}}
 private activateDueFollowUps():void{const now=this.workday.snapshot.elapsedGameMs;this.pendingFollowUps.sort((a,b)=>a.dueGameMs-b.dueGameMs||a.sequence-b.sequence);for(let index=0;index<this.pendingFollowUps.length;){const item=this.pendingFollowUps[index]!;if(item.dueGameMs>now)break;const definition=this.definitions.get(item.eventId)!;if((definition.caseId&&this.caseStatuses[definition.caseId]!=='open')||!matchesEligibility(definition.eligibility,this.context())||this.interruptions.snapshot.active.some(x=>x.id===item.eventId)){this.pendingFollowUps.splice(index,1);continue;}if(this.interruptions.activate(item.eventId,item.dueGameMs,item.sequence)){this.spawns.push({id:item.eventId,band:activePacingBand(this.profile,item.dueGameMs).id,atGameMs:item.dueGameMs});this.pendingFollowUps.splice(index,1);}else{const key=definition.deduplicationKey??definition.id;const retry=this.interruptions.snapshot.cooldownUntilGameMs[key]??now+1;this.pendingFollowUps[index]=Object.freeze({...item,dueGameMs:Math.max(now+1,retry)});index++;}}}
 private activate(candidate:ScheduledCandidate):boolean{const d=this.definitions.get(candidate.definitionId);if(d?.caseId&&this.caseStatuses[d.caseId]!=='open')return false;const activated=this.interruptions.activate(candidate.definitionId,candidate.dueGameMs,candidate.sequence);if(activated)this.spawns.push({id:candidate.definitionId,band:activePacingBand(this.profile,candidate.dueGameMs).id,atGameMs:candidate.dueGameMs});return activated;}
 private applyTransitions(batch:TransitionBatch):void{for(const item of batch){this.effectEngine.execute(item.effects,item.interruptionId);for(const id of item.followUpIds)this.scheduleFollowUp(id,item.deadlineGameMs,item.interruptionId);}}
 private consumeBooster(id:BoosterId):void{const day=this.workday.snapshot,activation=this.boosters.activate(id,{elapsedGameMs:day.elapsedGameMs,stamina:day.resources.stamina,isDecisionOpen:false,isDayComplete:false});if(!activation.result)return;this.workday.mutateResource('stamina',activation.result.staminaRestoration);if(activation.result.toiletNeedIncrease)this.playerNeeds.mutateNeed('toilet',activation.result.toiletNeedIncrease);this.recoveryWindows.push({action:id,atGameMs:day.elapsedGameMs});}
 private beginNextDay():void{this.lifecycleState='day-transition';this.completedOvernights++;const now=this.workday.snapshot.elapsedGameMs,o=this.profile.overnight,stamina=this.workday.snapshot.resources.stamina;this.workday.mutateResource('stamina',Math.max(0,Math.min(o.staminaCap,stamina+o.staminaRestoration)-stamina));this.playerNeeds.beginNextDay(now,{sleepiness:o.sleepiness,toilet:o.toilet});this.applyTransitions(this.interruptions.beginNextDay());this.scheduler.beginNextDay(now);this.lifecycleState='active';this.causalSource='another day at work';this.synchronize();}
 private collapseCauses():readonly CollapseCause[]{const r=this.workday.snapshot.resources,c:CollapseCause[]=[];if(r.stamina<=0)c.push('stamina');if(r.poHappiness<=0)c.push('firing');if(r.systemStability<=0)c.push('outage');if(this.healthRisk>=this.profile.healthRisk.collapse)c.push('health');return Object.freeze(c);}
 private context(){const day=this.workday.snapshot,h=this.interruptions.snapshot,n=this.playerNeeds.snapshot,b=this.boosters.snapshot,stage=(id:NeedId)=>this.playerNeeds.config.needs[id].stages.findIndex(x=>x.id===n[id].stage.id);return createRunContext({resolvedEventIds:h.resolvedIds,resolvedChoices:h.resolvedOutcomes,resources:day.resources,caseStatuses:this.caseStatuses,needStages:{sleepiness:stage('sleepiness'),toilet:stage('toilet')},boosterCounts:b.consumptionCounts,incidentCounts:h.incidentCounts,concludedConsequenceIds:h.concludedConsequenceIds,activeDeduplicationKeys:h.active.map(x=>x.deduplicationKey??x.id),cooldownUntilGameMs:h.cooldownUntilGameMs,currentGameMs:day.elapsedGameMs});}
}
