import { BoosterSession,type BoosterId } from './BoosterSession';
import { CodingDisruptionLedger } from './CodingDisruptionLedger';
import { CodingSession } from './CodingSession';
import { AiWorkCycle } from './AiWorkCycle';
import type { AiModeId } from '../content/aiModes';
import { ConsequenceQueue } from './ConsequenceQueue';
import { DayState,type ResourceValues } from './DayState';
import { EffectEngine } from './EffectEngine';
import { EngineeringTaskQueue } from './EngineeringTaskQueue';
import { EventScheduler,type ScheduledCandidate } from './EventScheduler';
import { PlayerNeeds,type NeedId } from './PlayerNeeds';
import { activePacingBand,WORKDAY_DURATION_MS,type PacingBandId,type PacingProfile } from './WorkdayPacing';
import { createRunContext,InterruptionSession,type TransitionBatch } from './interruptions';
import type { ConsequenceFeedback } from './effects';
import { ENGINEERING_TASKS } from '../content/engineeringTasks';
import { INTERRUPTION_CATALOG } from '../content/poTeamInterruptions';
import { createTerminalEvidence,evaluateTerminalEvidence,type CollapseCause,type EvaluatedResult,type TerminalResolutionEvidence } from './EndOfDayResults';

export type PlayerAction = Readonly<{type:'start-ai';mode:AiModeId;taskId:string}|{type:'wait-ai'}|{type:'approve-ai';taskId:string;cycleId:string;batchId:string}|{type:'revise-ai';taskId:string;cycleId:string;batchId:string}|{type:'resolve-interruption';interruptionId:string;choiceId:string}|{type:'resolve-task';choiceId:string}|{type:'switch-task';taskId:string}|{type:'bathroom'}|{type:'booster';boosterId:BoosterId}>;
export interface WorkdayDebugSnapshot {readonly profile:PacingProfile['id'];readonly seed:number;readonly dayIndex:number;readonly healthRisk:number;readonly activeBand:PacingBandId;readonly eventPressure:number;readonly quietDurationGameMs:number;readonly resources:ResourceValues;readonly needs:Readonly<Record<NeedId,number>>}
export interface WorkdaySessionMetrics {readonly spawns:readonly Readonly<{id:string;band:PacingBandId;atGameMs:number}>[];readonly resolutions:readonly Readonly<{id:string;band:PacingBandId;atGameMs:number}>[];readonly criticalWindows:readonly Readonly<{need:NeedId;atGameMs:number}>[];readonly recoveryWindows:readonly Readonly<{action:string;atGameMs:number}>[];readonly boosterUse:Readonly<Record<BoosterId,number>>;readonly maximumQuietGameMs:number;readonly peakPressure:number}
export type WorkdayLifecycle='active'|'day-transition'|'collapsed'|'results';

export class WorkdaySession {
    readonly workday:DayState;readonly coding:CodingSession;readonly ai:AiWorkCycle;readonly taskQueue:EngineeringTaskQueue;readonly playerNeeds:PlayerNeeds;readonly boosters:BoosterSession;readonly interruptions:InterruptionSession;readonly scheduler:EventScheduler;readonly consequenceQueue:ConsequenceQueue;readonly disruptions:CodingDisruptionLedger;readonly effectEngine:EffectEngine;
    private spawns:{id:string;band:PacingBandId;atGameMs:number}[]=[];private resolutions:{id:string;band:PacingBandId;atGameMs:number}[]=[];private criticalWindows:{need:NeedId;atGameMs:number}[]=[];private recoveryWindows:{action:string;atGameMs:number}[]=[];private peakPressure=0;private maximumQuietGameMs=0;private lifecycleState:WorkdayLifecycle='active';private terminalResult:EvaluatedResult|null=null;private completedOvernights=0;private causalSource='passive pressure';
    constructor(readonly profile:PacingProfile,readonly seed:number,feedback:(record:ConsequenceFeedback)=>void=()=>{},private readonly autoOpenInterruptions=true){
        if(!Number.isInteger(seed))throw new TypeError('Workday seed must be an integer.');
        const balance=profile.balance;this.workday=new DayState({gameMinutesPerRealSecond:profile.gameMinutesPerRealSecond,initialResources:balance.initialResources,continuous:true});this.coding=new CodingSession({workPerGameMinute:balance.taskWorkPerGameMinute,staminaPerGameMinute:balance.codingStaminaPerGameMinute});this.ai=new AiWorkCycle(seed+3);this.taskQueue=new EngineeringTaskQueue(ENGINEERING_TASKS);this.playerNeeds=new PlayerNeeds({bathroomGameMinutes:balance.bathroomGameMinutes,bathroomFocusReduction:balance.bathroomFocusReduction},0,profile);this.boosters=new BoosterSession({boosters:{coffee:{staminaRestoration:balance.coffeeStaminaRestoration},cokeZero:{staminaRestoration:balance.cokeZeroStaminaRestoration,toiletNeedIncrease:balance.cokeZeroToiletIncrease}}},seed+2);this.consequenceQueue=new ConsequenceQueue();this.disruptions=new CodingDisruptionLedger();
        this.interruptions=new InterruptionSession(INTERRUPTION_CATALOG,0,false,()=>this.workday.snapshot.resources.technicalDebt,(delay,due)=>{const day=Math.floor(due/WORKDAY_DURATION_MS)+1;return delay/activePacingBand(profile,due).escalationPressure*Math.max(profile.dayScaling.minimumEscalationMultiplier,Math.pow(profile.dayScaling.intervalMultiplier,day-1));});
        this.scheduler=new EventScheduler(INTERRUPTION_CATALOG,{minimumSpawnIntervalMs:20*60_000,maximumSpawnIntervalMs:35*60_000,activeLimit:64,endGameMs:Number.MAX_SAFE_INTEGER,pacingProfile:profile},seed);
        this.effectEngine=new EffectEngine({mutateResource:(key,amount)=>this.workday.mutateResource(key,amount),reduceFocus:amount=>this.coding.reduceFocus(amount),reduceTaskProgress:amount=>this.taskQueue.reduceSelectedProgress(amount),disruptions:this.disruptions,queue:this.consequenceQueue,gameTime:()=>this.workday.snapshot.elapsedGameMs,technicalDebt:()=>this.workday.snapshot.resources.technicalDebt,feedback,consequenceConcluded:id=>this.interruptions.recordConcludedConsequence(id)},seed+1);
        this.synchronizeAvailability();
    }
    get metrics():WorkdaySessionMetrics{return Object.freeze({spawns:Object.freeze(this.spawns.map(item=>Object.freeze({...item}))),resolutions:Object.freeze(this.resolutions.map(item=>Object.freeze({...item}))),criticalWindows:Object.freeze(this.criticalWindows.map(item=>Object.freeze({...item}))),recoveryWindows:Object.freeze(this.recoveryWindows.map(item=>Object.freeze({...item}))),boosterUse:this.boosters.snapshot.consumptionCounts,maximumQuietGameMs:this.maximumQuietGameMs,peakPressure:this.peakPressure});}
    get lifecycle():WorkdayLifecycle{return this.lifecycleState;}get result():EvaluatedResult|null{return this.terminalResult;}
    get healthRisk():number{const counts=this.boosters.snapshot.consumptionCounts;return Math.max(0,counts.coffee*this.profile.healthRisk.coffee+counts.cokeZero*this.profile.healthRisk.cokeZero-this.completedOvernights*this.profile.overnight.healthRiskRecovery);}
    finalize(causalSource=this.causalSource):EvaluatedResult|null{if(this.terminalResult)return this.terminalResult;const day=this.workday.snapshot,causes=this.collapseCauses();if(!causes.length)return null;this.causalSource=causalSource;this.lifecycleState='collapsed';this.coding.cancelCoding();this.ai.cancel();const needs=this.playerNeeds.snapshot,history=this.interruptions.snapshot;const resolutions=history.resultOutcomes.map(item=>({eventId:item.eventId,choiceId:item.choiceId,category:item.category??'personal',incidentControl:item.incidentControl,resultKarma:item.resultKarma})) as TerminalResolutionEvidence[];const resolvedIncidentIds=resolutions.filter(r=>(r.category==='production'||r.category==='tooling')&&r.incidentControl==='player-fixable').map(r=>r.eventId);this.terminalResult=evaluateTerminalEvidence(createTerminalEvidence({elapsedGameMs:day.elapsedGameMs,dayIndex:day.dayIndex,dayElapsedGameMs:day.dayElapsedGameMs,resources:day.resources,needs:{sleepiness:needs.sleepiness.value,toilet:needs.toilet.value},healthRisk:this.healthRisk,collapseCauses:causes,causalSource,activeInterruptionIds:history.active.map(item=>item.id),completedTaskIds:this.taskQueue.snapshot.runCompletedTaskIds,resolutions,resolvedIncidentIds,criticalNeedEpisodes:{sleepiness:this.criticalWindows.filter(x=>x.need==='sleepiness').length,toilet:this.criticalWindows.filter(x=>x.need==='toilet').length},boosterCounts:this.boosters.snapshot.consumptionCounts}));this.lifecycleState='results';return this.terminalResult;}
    get debugSnapshot():WorkdayDebugSnapshot{const day=this.workday.snapshot,needs=this.playerNeeds.snapshot,scheduler=this.scheduler.snapshot;return Object.freeze({profile:this.profile.id,seed:this.seed,dayIndex:day.dayIndex,healthRisk:this.healthRisk,activeBand:activePacingBand(this.profile,day.elapsedGameMs).id,eventPressure:scheduler.pressure,quietDurationGameMs:scheduler.quietDurationGameMs,resources:day.resources,needs:Object.freeze({sleepiness:needs.sleepiness.value,toilet:needs.toilet.value})});}
    legalActions():readonly PlayerAction[]{
        const day=this.workday.snapshot,task=this.taskQueue.snapshot,intr=this.interruptions.snapshot,actions:PlayerAction[]=[];if(this.lifecycleState==='results')return Object.freeze(actions);
        if(intr.openInterruption){for(const choice of intr.openInterruption.choices)actions.push(Object.freeze({type:'resolve-interruption',interruptionId:intr.openInterruption.id,choiceId:choice.id}));return Object.freeze(actions);}
        if(task.pendingDecision){for(const choice of task.pendingDecision.definition.choices)actions.push(Object.freeze({type:'resolve-task',choiceId:choice.id}));return Object.freeze(actions);}
        const ai=this.ai.snapshot;
        if(ai.phase==='planning'||ai.phase==='generating')actions.push(Object.freeze({type:'wait-ai'}));
        else if(ai.phase==='review'&&ai.batch){const identity={taskId:ai.batch.taskId,cycleId:ai.batch.cycleId,batchId:ai.batch.id};actions.push(Object.freeze({type:'approve-ai',...identity}),Object.freeze({type:'revise-ai',...identity}));}
        else if(ai.isAvailable&&task.selectedTask){actions.push(Object.freeze({type:'start-ai',mode:'prompt',taskId:task.selectedTask.id}),Object.freeze({type:'start-ai',mode:'plan',taskId:task.selectedTask.id}));}
        task.tasks.filter(item=>!item.isComplete&&!item.isSelected).forEach(item=>actions.push(Object.freeze({type:'switch-task',taskId:item.id})));
        if(!day.isDayComplete)actions.push(Object.freeze({type:'bathroom'}));
        this.boosters.synchronize(this.boosterContext());for(const id of ['coffee','cokeZero'] as const)if(this.boosters.snapshot.availability[id].available)actions.push(Object.freeze({type:'booster',boosterId:id}));
        return Object.freeze(actions);
    }
    perform(action:PlayerAction,stepGameMs=this.profile.simulationStepGameMs):void{
        const legal=this.legalActions();if(!legal.some(item=>JSON.stringify(item)===JSON.stringify(action)))throw new Error(`Player policy selected illegal or non-progressing action: ${JSON.stringify(action)}.`);
        this.causalSource=action.type;
        if(action.type==='wait-ai'){this.advanceGameMs(Math.min(stepGameMs,60_000));this.finalize();return;}
        if(action.type==='start-ai'){if(!this.ai.start(action.mode,action.taskId))throw new Error('AI cycle did not start.');this.advanceGameMs(Math.min(stepGameMs,60_000));this.finalize();return;}
        if(action.type==='approve-ai'){const transition=this.ai.approve(action);if(!transition.accepted||!transition.batch)throw new Error('AI batch approval did not progress.');const result=this.taskQueue.applyWork(transition.batch.proposedWork);if(result.completionEffects.length)this.effectEngine.execute(result.completionEffects,result.completedTaskId!);if(transition.batch.effects.length)this.effectEngine.execute(transition.batch.effects as unknown as readonly import('./effects').Effect[],transition.batch.id);this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);this.synchronizeAvailability();this.finalize(transition.batch.id);return;}
        if(action.type==='revise-ai'){const transition=this.ai.revise(action);if(!transition.accepted)throw new Error('AI batch revision did not progress.');if(transition.staminaCost)this.workday.mutateResource('stamina',-transition.staminaCost);this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);this.synchronizeAvailability();return;}
        if(action.type==='switch-task'){this.taskQueue.select(action.taskId);this.ai.cancel();this.coding.reduceFocus(.2);this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);this.synchronizeAvailability();return;}
        if(action.type==='bathroom'){this.coding.reduceFocus(this.playerNeeds.config.bathroomFocusReduction);this.advanceGameMs(this.playerNeeds.config.bathroomGameMinutes*60_000,true);this.playerNeeds.relieve('toilet');this.recoveryWindows.push({action:'bathroom',atGameMs:this.workday.snapshot.elapsedGameMs});this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);this.finalize('bathroom break');return;}
        if(action.type==='booster'){const activation=this.boosters.activate(action.boosterId,this.boosterContext());if(!activation.result)throw new Error('Legal booster activation did not progress.');this.workday.mutateResource('stamina',activation.result.staminaRestoration);if(activation.result.toiletNeedIncrease)this.playerNeeds.mutateNeed('toilet',activation.result.toiletNeedIncrease);this.recoveryWindows.push({action:action.boosterId,atGameMs:this.workday.snapshot.elapsedGameMs});this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);this.finalize(`${action.boosterId} overuse`);return;}
        if(action.type==='resolve-task'){const choice=this.taskQueue.resolvePendingDecision(action.choiceId);if(!choice)throw new Error('Task decision did not progress.');this.advanceGameMs(choice.gameMinutes*60_000,true);this.effectEngine.execute(choice.effects,`task:${choice.id}`);this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);this.finalize(`task:${choice.id}`);return;}
        const pending=this.interruptions.beginResolution(action.choiceId);if(!pending||pending.interruptionId!==action.interruptionId)throw new Error('Interruption decision did not progress.');this.advanceGameMs(pending.choice.gameMinutes*60_000,true);this.effectEngine.execute(pending.choice.effects,pending.interruptionId);this.interruptions.finalizeResolution(pending.interruptionId);this.resolutions.push({id:pending.interruptionId,band:activePacingBand(this.profile,this.workday.snapshot.elapsedGameMs).id,atGameMs:this.workday.snapshot.elapsedGameMs});this.scheduler.resolved(pending.interruptionId,c=>this.activate(c));this.scheduler.markMeaningfulAction(this.workday.snapshot.elapsedGameMs);this.synchronize();this.finalize(pending.interruptionId);
    }
    advanceRealMs(realMs:number):void{if(this.lifecycleState==='results'||this.workday.snapshot.isPaused||!Number.isFinite(realMs)||realMs<=0)return;this.advanceGameMs(realMs*this.profile.gameMinutesPerRealSecond*60);}
    advanceGameMs(gameMs:number,deferCollapse=false):void{if(!Number.isFinite(gameMs)||gameMs<0)throw new RangeError('Game step must be finite and non-negative.');if(this.lifecycleState==='results')return;let remaining=gameMs;while(remaining>0&&this.lifecycleState==='active'){const now=this.workday.snapshot.elapsedGameMs,nextBoundary=(Math.floor(now/WORKDAY_DURATION_MS)+1)*WORKDAY_DURATION_MS,step=Math.min(remaining,nextBoundary-now);this.workday.spendGameMinutes(step/60_000);this.advanceSystems(step);remaining-=step;if(!deferCollapse)this.finalize(this.causalSource);if(this.terminalResult)break;if(this.workday.snapshot.elapsedGameMs===nextBoundary)this.beginNextDay();}}
    reset():void{this.workday.reset();this.coding.cancelCoding();this.ai.reset();this.taskQueue.reset();this.playerNeeds.reset();this.boosters.reset();this.interruptions.reset();this.scheduler.reset();this.effectEngine.reset();this.spawns=[];this.resolutions=[];this.criticalWindows=[];this.recoveryWindows=[];this.peakPressure=0;this.maximumQuietGameMs=0;this.lifecycleState='active';this.terminalResult=null;this.completedOvernights=0;this.causalSource='passive pressure';this.synchronizeAvailability();}
    private advanceSystems(elapsedGameMs:number):void{const minutes=elapsedGameMs/60_000,active=this.interruptions.snapshot.active;if(minutes>0){this.workday.mutateResource('stamina',-minutes*(.08+active.length*.015));this.workday.mutateResource('poHappiness',-minutes*active.filter(item=>item.category==='product-owner'||item.category==='teammate').length*.025);this.workday.mutateResource('systemStability',-minutes*active.filter(item=>item.category==='production'||item.category==='tooling').length*.025);}this.synchronize();if(!this.workday.snapshot.isPaused)this.ai.advance(elapsedGameMs,Math.min(this.playerNeeds.snapshot.codingSpeedModifier,this.disruptions.snapshot.effectiveSpeedFactor));this.synchronizeAvailability();}
    private synchronize():void{const now=this.workday.snapshot.elapsedGameMs;const needs=this.playerNeeds.synchronize(now);if(needs.additionalStaminaCost)this.workday.mutateResource('stamina',-needs.additionalStaminaCost);for(const transition of needs.transitions){if(transition.criticalEffect){this.criticalWindows.push({need:transition.need,atGameMs:transition.atGameMs});this.coding.reduceFocus(transition.criticalEffect.focusReduction);if(transition.criticalEffect.staminaCost)this.workday.mutateResource('stamina',-transition.criticalEffect.staminaCost);}}
        this.scheduler.synchronize(now,c=>this.activate(c),this.context());let batch=this.interruptions.setCurrentGameMs(now),guard=0;while(batch.length){if(++guard>1000)throw new Error('Workday synchronization transition limit exceeded.');this.applyTransitions(batch);batch=this.interruptions.setCurrentGameMs(now);}this.effectEngine.synchronize(now);this.disruptions.synchronize(now);this.maximumQuietGameMs=Math.max(this.maximumQuietGameMs,this.scheduler.snapshot.quietDurationGameMs);this.peakPressure=Math.max(this.peakPressure,this.scheduler.snapshot.pressure);if(this.autoOpenInterruptions&&this.interruptions.snapshot.active.length&&!this.interruptions.snapshot.openInterruption)this.interruptions.open(this.interruptions.snapshot.active[0]!.id);this.synchronizeAvailability();}
    private activate(candidate:ScheduledCandidate):boolean{const activated=this.interruptions.activate(candidate.definitionId,candidate.dueGameMs,candidate.sequence);if(activated)this.spawns.push({id:candidate.definitionId,band:activePacingBand(this.profile,candidate.dueGameMs).id,atGameMs:candidate.dueGameMs});return activated;}
    private applyTransitions(batch:TransitionBatch):void{for(const item of batch){this.effectEngine.execute(item.effects,item.interruptionId);for(const follow of item.followUpIds)this.scheduler.enqueueFollowUp(follow,item.deadlineGameMs,c=>this.activate(c));}}
    private beginNextDay():void{this.lifecycleState='day-transition';this.completedOvernights++;const now=this.workday.snapshot.elapsedGameMs,overnight=this.profile.overnight,stamina=this.workday.snapshot.resources.stamina,before=this.interruptions.snapshot.active.filter(item=>item.severity!=='high'&&item.severity!=='critical').map(item=>item.id);this.workday.mutateResource('stamina',Math.max(0,Math.min(overnight.staminaCap,stamina+overnight.staminaRestoration)-stamina));this.playerNeeds.beginNextDay(now,{sleepiness:overnight.sleepiness,toilet:overnight.toilet});this.applyTransitions(this.interruptions.beginNextDay());for(const id of before)this.scheduler.resolved(id,c=>this.activate(c));this.taskQueue.beginNextDay(this.workday.snapshot.dayIndex);this.scheduler.beginNextDay(now);this.ai.cancel();this.coding.reduceFocus(1);this.lifecycleState='active';this.causalSource='another day at work';this.synchronize();}
    private collapseCauses():readonly CollapseCause[]{const r=this.workday.snapshot.resources,causes:CollapseCause[]=[];if(r.stamina<=0)causes.push('stamina');if(r.poHappiness<=0)causes.push('firing');if(r.systemStability<=0)causes.push('outage');if(this.healthRisk>=this.profile.healthRisk.collapse)causes.push('health');return Object.freeze(causes);}
    private context(){const day=this.workday.snapshot,tasks=this.taskQueue.snapshot,history=this.interruptions.snapshot,needs=this.playerNeeds.snapshot,boosters=this.boosters.snapshot;const stage=(id:NeedId)=>this.playerNeeds.config.needs[id].stages.findIndex(item=>item.id===needs[id].stage.id);return createRunContext({selectedTaskId:tasks.selectedTaskId,completedTaskIds:tasks.completedTaskIds,resolvedEventIds:history.resolvedIds,resolvedChoices:history.resolvedOutcomes,resources:day.resources,needStages:{sleepiness:stage('sleepiness'),toilet:stage('toilet')},boosterCounts:boosters.consumptionCounts,incidentCounts:history.incidentCounts,concludedConsequenceIds:history.concludedConsequenceIds,activeDeduplicationKeys:history.active.map(item=>item.deduplicationKey??item.id),cooldownUntilGameMs:history.cooldownUntilGameMs,currentGameMs:day.elapsedGameMs});}
    private boosterContext(){const day=this.workday.snapshot;return {elapsedGameMs:day.elapsedGameMs,stamina:day.resources.stamina,isDecisionOpen:Boolean(this.interruptions.snapshot.openInterruption||this.taskQueue.snapshot.pendingDecision),isDayComplete:day.isDayComplete};}
    private synchronizeAvailability():void{const day=this.workday.snapshot,task=this.taskQueue.snapshot;this.coding.setRuntimeModifiers({codingSpeed:1,focusGain:0});this.coding.synchronizeAvailability(false,day.resources.stamina,false);this.ai.synchronize({taskId:task.selectedTask?.id??null,available:!day.isPaused&&!day.isDayComplete&&day.resources.stamina>0&&Boolean(task.selectedTask)&&!task.pendingDecision,disabledReason:day.isDayComplete?'Day complete':day.isPaused?'Paused':day.resources.stamina<=0?'Stamina exhausted':task.pendingDecision?'Decision pending':!task.selectedTask?'All work complete':null,focus:this.coding.snapshot.focus,workBoundary:this.taskQueue.nextWorkBoundary()});if(day.isDayComplete)this.ai.cancel();}
}
