import{Core,GameObjects,Input,Scene,Scenes}from'phaser';import{WorkdaySession}from'../domain/WorkdaySession';import type{DayState,ResourceKey}from'../domain/DayState';import type{InterruptionSession,ActiveInterruptionSnapshot}from'../domain/interruptions';import type{PlayerNeeds,NeedId}from'../domain/PlayerNeeds';import{DEVELOPER_PACING_PROFILE,NORMAL_PACING_PROFILE}from'../domain/WorkdayPacing';import{COLORS,DEPTH,SEVERITY,TYPE}from'../ui/theme';import{meter,panel,roundedSurface,type MeterView}from'../ui/primitives';import{configureHighDpiScene}from'../presentation/HighDpiRendering';import{presentationTexture}from'../presentation/assets';import{gameAudio,SceneAudioDirector}from'../audio/GameAudio';import{browserGuidanceStorage,GuidancePreference}from'../presentation/GuidancePreference';import{createGuidanceOverlay,type GuidanceOverlayView}from'../presentation/GuidanceOverlay';import{installWorkstationDiagnostics}from'../presentation/PlaytestDiagnostics';
import{notificationIdentity}from'../presentation/identities';
import{InterruptionPanel}from'../ui/InterruptionPanel';
const PAUSE='player-pause',GUIDANCE='first-run-guidance',VISIBILITY='browser-visibility';
const STICKY_SLOTS=Object.freeze([{x:20,y:88},{x:270,y:88},{x:520,y:88},{x:770,y:88},{x:20,y:322},{x:770,y:322}]);
export class Workstation extends Scene{
 session!:WorkdaySession;workday!:DayState;interruptions!:InterruptionSession;playerNeeds!:PlayerNeeds;
 private resources!:Record<ResourceKey,{text:GameObjects.Text;bar:MeterView}>;private needs!:Record<NeedId,{text:GameObjects.Text;bar:MeterView}>;private clock!:GameObjects.Text;private progress!:MeterView;private stickyLayer!:GameObjects.Container;private page=0;private pageLabel!:GameObjects.Text;private guidance?:GuidanceOverlayView;private guidancePreference?:GuidancePreference;private removeDiagnostics?:()=>void;private audio?:SceneAudioDirector;private pauseLabel!:GameObjects.Text;private resultsStarted=false;
 constructor(){super('Workstation');}
 create():void{configureHighDpiScene(this);this.resultsStarted=false;this.session=new WorkdaySession(import.meta.env.VITE_PACING_PROFILE==='developer'?DEVELOPER_PACING_PROFILE:NORMAL_PACING_PROFILE,20260907,()=>{},false);this.workday=this.session.workday;this.interruptions=this.session.interruptions;this.playerNeeds=this.session.playerNeeds;this.cameras.main.setBackgroundColor(COLORS.backdrop);this.buildScene();this.audio=new SceneAudioDirector(this.sound);gameAudio.attach(this.sound);this.render();this.renderStickies();this.workday.subscribe(()=>this.render());this.interruptions.subscribe(()=>this.renderStickies());this.playerNeeds.subscribe(()=>this.renderNeeds());this.guidancePreference=new GuidancePreference(browserGuidanceStorage());if(!this.guidancePreference.dismissed)this.openGuidance();this.removeDiagnostics=installWorkstationDiagnostics(this,()=>Boolean(this.guidance));this.bindLifecycle();this.events.once(Scenes.Events.SHUTDOWN,()=>this.cleanup());this.events.once(Scenes.Events.DESTROY,()=>this.cleanup());}
 update(_time:number,delta:number):void{if(this.resultsStarted)return;this.session.advanceRealMs(delta);this.render();const result=this.session.finalize();if(result){this.resultsStarted=true;const runId=window.__WORKDAY_PLAYTEST__?.getSnapshot().runId;this.scene.start('Results',{result,runId});}}
 private buildScene():void{this.add.image(640,360,presentationTexture(this,'presentation.background.office')).setDisplaySize(1280,720).setDepth(DEPTH.background);this.add.image(640,360,presentationTexture(this,'presentation.environment.desk')).setDisplaySize(1280,720).setDepth(DEPTH.environment);if(this.textures.exists('presentation.character.calm'))this.add.image(640,155,'presentation.character.calm').setDisplaySize(344,230).setDepth(DEPTH.character);if(this.textures.exists('presentation.ui.laptop-shell'))this.add.image(640,474,'presentation.ui.laptop-shell').setDisplaySize(520,378).setDepth(DEPTH.environment);if(this.textures.exists('presentation.foreground.frame'))this.add.image(640,360,'presentation.foreground.frame').setDisplaySize(1280,720).setDepth(DEPTH.foreground);this.buildStatus();this.buildClock();this.stickyLayer=this.add.container(0,0).setDepth(DEPTH.controls);this.buildMetaButton(1028,658,108,'⏸','PAUSE',()=>this.togglePause(),label=>this.pauseLabel=label);this.buildMetaButton(1144,658,112,'♫','SOUND',()=>gameAudio.toggle());const prev=this.add.text(774,622,'‹ PREV',{fontFamily:TYPE.family,fontSize:12,color:COLORS.text,fontStyle:'bold'}).setInteractive({useHandCursor:true}).setDepth(DEPTH.controls),next=this.add.text(934,622,'NEXT ›',{fontFamily:TYPE.family,fontSize:12,color:COLORS.text,fontStyle:'bold'}).setInteractive({useHandCursor:true}).setDepth(DEPTH.controls);this.pageLabel=this.add.text(878,622,'',{fontFamily:TYPE.family,fontSize:10,color:COLORS.textMuted}).setOrigin(.5,0).setDepth(DEPTH.controls);prev.on(Input.Events.GAMEOBJECT_POINTER_DOWN,()=>{this.page=Math.max(0,this.page-1);this.renderStickies();});next.on(Input.Events.GAMEOBJECT_POINTER_DOWN,()=>{this.page++;this.renderStickies();});}
 private buildStatus():void{const root=panel(this,{x:1024,y:84,width:252,height:562},0x172331).setDepth(DEPTH.controls);root.add(this.add.text(16,14,'WORKDAY STATUS',{fontFamily:TYPE.family,fontSize:14,color:COLORS.text,fontStyle:'bold'}));this.resources={}as typeof this.resources;(['stamina','poHappiness','systemStability','technicalDebt']as const).forEach((key,i)=>{const y=54+i*62,label=key==='poHappiness'?'PO HAPPINESS':key==='systemStability'?'SYSTEM STABILITY':key==='technicalDebt'?'TECHNICAL DEBT':'STAMINA',text=this.add.text(16,y,label,{fontFamily:TYPE.family,fontSize:9,color:COLORS.textMuted}),value=this.add.text(232,y,'',{fontFamily:TYPE.family,fontSize:9,color:COLORS.text,fontStyle:'bold'}).setOrigin(1,0);root.add([text,value]);this.resources[key]={text:value,bar:meter(this,root,16,y+22,216,0,key==='technicalDebt'?COLORS.danger:COLORS.mint)};});root.add(this.add.text(16,310,'PERSONAL NEEDS',{fontFamily:TYPE.family,fontSize:10,color:COLORS.text,fontStyle:'bold'}));this.needs={}as typeof this.needs;(['sleepiness','toilet']as const).forEach((id,i)=>{const y=342+i*62,text=this.add.text(16,y,'',{fontFamily:TYPE.family,fontSize:9,color:COLORS.textMuted});root.add(text);this.needs[id]={text,bar:meter(this,root,16,y+22,216,0,id==='toilet'?COLORS.amber:COLORS.blue)};});root.add(this.add.text(16,478,'CASE RECORD',{fontFamily:TYPE.family,fontSize:10,color:COLORS.text,fontStyle:'bold'}));root.add(this.add.text(16,504,'Resolved and failed cases appear\nin the final run autopsy.',{fontFamily:TYPE.family,fontSize:9,color:COLORS.textMuted,lineSpacing:4}));}
 private buildClock():void{const root=panel(this,{x:984,y:4,width:292,height:72},0x172331).setDepth(DEPTH.controls);this.clock=this.add.text(16,14,'',{fontFamily:TYPE.family,fontSize:22,color:COLORS.text,fontStyle:'bold'});root.add(this.clock);this.progress=meter(this,root,16,54,260,0,COLORS.mint);}
 private buildMetaButton(x:number,y:number,w:number,icon:string,label:string,action:()=>void,capture?:(label:GameObjects.Text)=>void):void{roundedSurface(this,x,y,w,54,0x1b2836,COLORS.borderStrong,9,.98,2).setDepth(DEPTH.controls);const hit=this.add.rectangle(x,y,w,54,0xffffff,0).setOrigin(0).setDepth(DEPTH.controls).setInteractive({useHandCursor:true}),text=this.add.text(x+42,y+19,label,{fontFamily:TYPE.family,fontSize:10,color:COLORS.text,fontStyle:'bold'}).setDepth(DEPTH.controls);this.add.text(x+22,y+27,icon,{fontFamily:TYPE.family,fontSize:18,color:'#f2bd61'}).setOrigin(.5).setDepth(DEPTH.controls);hit.on(Input.Events.GAMEOBJECT_POINTER_DOWN,action);capture?.(text);}
 private render():void{const d=this.workday.snapshot;this.clock.setText(`DAY ${d.dayIndex} · ${String(d.clockHour).padStart(2,'0')}:${String(d.clockMinute).padStart(2,'0')}`);this.progress.setValue(d.dayProgress);for(const key of ['stamina','poHappiness','systemStability','technicalDebt']as const){this.resources[key].text.setText(`${Math.round(d.resources[key])}${key==='technicalDebt'?'%':' / 100'}`);this.resources[key].bar.setValue(d.resources[key]/100);}this.renderNeeds();}
 private renderNeeds():void{if(!this.needs)return;for(const id of ['sleepiness','toilet']as const){const n=this.playerNeeds.snapshot[id];this.needs[id].text.setText(`${n.label.toUpperCase()} · ${n.stage.label} · ${Math.round(n.value)}%`);this.needs[id].bar.setValue(n.severity);}}
 private renderStickies():void{if(!this.stickyLayer)return;this.stickyLayer.removeAll(true);const active=this.interruptions.snapshot.active,limit=STICKY_SLOTS.length,pages=Math.max(1,Math.ceil(active.length/limit));this.page=Math.min(this.page,pages-1);this.pageLabel.setText(`${this.page+1}/${pages} · ${active.length} ACTIVE`);active.slice(this.page*limit,(this.page+1)*limit).forEach((item,index)=>this.buildSticky(item,STICKY_SLOTS[index]!.x,STICKY_SLOTS[index]!.y));}
 private buildSticky(item:ActiveInterruptionSnapshot,x:number,y:number):void{const identity=notificationIdentity(item.id,item.category,item.title),isSlack=identity.channel==='Slack',isGithub=identity.sender==='GitHub',accent=isSlack?0x611f69:isGithub?0x24292f:SEVERITY[item.severity].color,hash=[...`${item.id}:${item.activationSequence}`].reduce((value,char)=>(value*31+char.charCodeAt(0))>>>0,7),rawAngle=((hash%41)-20)/10,angle=Math.abs(rawAngle)<.6?(rawAngle<0?-1:1):rawAngle,panel=new InterruptionPanel(this,{x,y,angle,backgroundColor:isSlack?0xfffbff:isGithub?0xf6f8fa:undefined,borderColor:isSlack?0xc9a7cd:isGithub?0xd0d7de:undefined,accentColor:accent,icon:{texture:identity.texture,fallback:identity.fallback,backgroundColor:accent},sourceLabel:identity.sender,metadata:`${identity.channel} · ${SEVERITY[item.severity].marker} ${item.ageGameMinutes}m`,title:item.title,description:item.copy,controls:item.choices.map(choice=>({label:`${choice.label} · ${choice.gameMinutes}m`,description:choice.description,activate:()=>{if(item.status==='active')this.interruptions.open(item.id);const action=this.session.legalActions().find(a=>a.interruptionId===item.id&&a.choiceId===choice.id);if(action){this.audio?.cue('choice',`${item.id}:${choice.id}`);this.session.perform(action);this.render();}}}))});this.stickyLayer.add(panel.root);}
 private togglePause():void{if(this.workday.snapshot.pauseReasons.includes(PAUSE)){this.workday.resume(PAUSE);this.pauseLabel.setText('PAUSE');}else{this.workday.pause(PAUSE);this.pauseLabel.setText('RESUME');}}
 private openGuidance():void{this.workday.pause(GUIDANCE);this.guidance=createGuidanceOverlay(this,()=>{this.guidancePreference?.dismiss();this.guidance?.destroy();this.guidance=undefined;this.workday.resume(GUIDANCE);});}
 private bindLifecycle():void{this.game.events.on(Core.Events.BLUR,()=>this.workday.pause(VISIBILITY));this.game.events.on(Core.Events.FOCUS,()=>this.workday.resume(VISIBILITY));document.addEventListener('visibilitychange',this.visibility);}
 private visibility=():void=>document.visibilityState==='hidden'?this.workday.pause(VISIBILITY):this.workday.resume(VISIBILITY);
 private cleanup():void{this.removeDiagnostics?.();this.guidance?.destroy();document.removeEventListener('visibilitychange',this.visibility);this.game.events.removeAllListeners(Core.Events.BLUR);this.game.events.removeAllListeners(Core.Events.FOCUS);}
}
