import type { EngineeringTaskDefinition } from '../domain/EngineeringTaskQueue';

export const ENGINEERING_TASKS: readonly EngineeringTaskDefinition[] = Object.freeze([
    { id: 'BUG-4821', title: 'Fix login error', effort: 18, priority: 'urgent', stakeholder:'Product Owner',initialDeadlineGameMs:90*60_000,crisisTaskId:'INC-LOGIN',failureEffects:[{type:'resource',resource:'poHappiness',amount:-10},{type:'resource',resource:'systemStability',amount:-8}],rewardCopy: 'Restore customer access.', riskCopy: 'A rushed patch can weaken stability.', completionEffects: [{ type: 'resource', resource: 'poHappiness', amount: 8 }], technicalDebtEffects: [{ type: 'resource', resource: 'technicalDebt', amount: 2 }] },
    { id: 'TASK-3178', title: 'Improve search', effort: 24, priority: 'high',stakeholder:'Product Owner',crisisTaskId:'INC-SEARCH',failureEffects:[{type:'resource',resource:'poHappiness',amount:-12},{type:'resource',resource:'technicalDebt',amount:5}], rewardCopy: 'Faster results delight users.', riskCopy: 'Index strategy needs a deliberate choice.', completionEffects: [{ type: 'resource', resource: 'systemStability', amount: 7 }], midpointDecision: { id: 'search-index', title: 'Choose an indexing strategy', copy: 'The profiling results expose two viable trade-offs.', threshold: 50, choices: [
        { id: 'safe-index', label: 'Build the safe index', description: 'Spend longer and protect production.', gameMinutes: 20, effects: [{ type: 'resource', resource: 'systemStability', amount: 5 }] },
        { id: 'fast-cache', label: 'Ship the cache shortcut', description: 'Move quickly and accept debt.', gameMinutes: 8, effects: [{ type: 'resource', resource: 'technicalDebt', amount: 6 }, { type: 'resource', resource: 'poHappiness', amount: 3 }] }
    ] } },
    { id: 'DEBT-204', title: 'Refactor auth service', effort: 28, priority: 'medium', rewardCopy: 'Retire brittle internals.', riskCopy: 'Touches a mature subsystem.', completionEffects: [{ type: 'resource', resource: 'technicalDebt', amount: -10 }, { type: 'resource', resource: 'systemStability', amount: 5 }] },
    { id: 'TEST-911', title: 'Cover payment retries', effort: 20, priority: 'medium', rewardCopy: 'Catch regressions earlier.', riskCopy: 'Low immediate product visibility.', completionEffects: [{ type: 'resource', resource: 'systemStability', amount: 9 }] },
    { id: 'CHORE-88', title: 'Upgrade build tooling', effort: 14, priority: 'low', rewardCopy: 'Keep the pipeline current.', riskCopy: 'Small compatibility risk.', completionEffects: [{ type: 'resource', resource: 'poHappiness', amount: 4 }], technicalDebtEffects: [{ type: 'resource', resource: 'technicalDebt', amount: -4 }] },
    {id:'INC-LOGIN',title:'Contain login incident',effort:12,priority:'urgent',initialStatus:'dormant',stakeholder:'Product Owner',rewardCopy:'Restore access and confidence.',riskCopy:'Containment adds follow-up debt.',completionEffects:[{type:'resource',resource:'systemStability',amount:8},{type:'resource',resource:'poHappiness',amount:4},{type:'resource',resource:'technicalDebt',amount:3}]},
    {id:'INC-SEARCH',title:'Recover search delivery',effort:12,priority:'urgent',initialStatus:'dormant',stakeholder:'Product Owner',rewardCopy:'Recover the missed delivery.',riskCopy:'Recovery leaves cleanup behind.',completionEffects:[{type:'resource',resource:'poHappiness',amount:6},{type:'resource',resource:'technicalDebt',amount:4}]}
]);
