import { DEFAULT_DAY_STATE_CONFIG } from '../domain/DayState';
import { createRunContext, validateInterruptionCatalog, type Effect, type InterruptionDefinition, type InterruptionRunContext } from '../domain/interruptions';

const context = (overrides: Partial<InterruptionRunContext> = {}): InterruptionRunContext => createRunContext({
    selectedTaskId: null, completedTaskIds: [], resolvedEventIds: [], resolvedChoices: [],
    resources: DEFAULT_DAY_STATE_CONFIG.initialResources, needStages: { sleepiness: 0, toilet: 0 },
    boosterCounts: { coffee: 0, cokeZero: 0 }, incidentCounts: {}, concludedConsequenceIds: [], ...overrides
});
const choice = (id:string,label:string,description:string,gameMinutes:number,effects:readonly Effect[],outcomeCertainty?:'certain'|'uncertain') => ({ id,label,description,gameMinutes,effects,outcomeCertainty });

export const PERSONAL_INTERRUPTION_PACK: readonly InterruptionDefinition[] = Object.freeze([
    { id:'personal-sleep-warning',category:'personal',severity:'medium',title:'EYELIDS DEPLOYING',copy:'The screen is beginning to read you back.',topics:['sleep-warning'],baseWeight:1.2,deduplicationKey:'need-sleepiness',cooldownGameMs:30*60_000,eligibility:{type:'need-stage',need:'sleepiness',minimumStage:2},documentedContexts:[context({needStages:{sleepiness:2,toilet:0}})],choices:[choice('take-microbreak','TAKE A MICROBREAK','Spend 12m and recover some Stamina.',12,[{type:'resource',resource:'stamina',amount:12}]),choice('power-through-sleep','POWER THROUGH','Keep moving; Focus -18%.',0,[{type:'focus',reduction:.18}])]},
    { id:'personal-bathroom-warning',category:'personal',severity:'high',title:'BIOLOGICAL SLA',copy:'The bathroom request has reached urgent priority.',topics:['bathroom-urgency'],baseWeight:1.3,deduplicationKey:'need-toilet',cooldownGameMs:20*60_000,eligibility:{type:'need-stage',need:'toilet',minimumStage:2},documentedContexts:[context({needStages:{sleepiness:0,toilet:2}})],choices:[choice('go-now','GO NOW','Spend 10m and step away safely.',10,[{type:'focus',reduction:.05}]),choice('hold-it','HOLD IT','Save time; Focus -22%.',0,[{type:'focus',reduction:.22}])]},
    { id:'personal-coffee-pressure',category:'personal',severity:'medium',title:'COFFEE-DRIVEN ROADMAP',copy:'Two coffees in, every ticket looks achievable.',topics:['coffee-pressure'],baseWeight:1,deduplicationKey:'booster-coffee-pressure',cooldownGameMs:45*60_000,eligibility:{type:'booster-count',booster:'coffee',minimumCount:2},documentedContexts:[context({boosterCounts:{coffee:2,cokeZero:0}})],choices:[choice('write-it-down','WRITE IT DOWN','Spend 8m; PO +4.',8,[{type:'resource',resource:'poHappiness',amount:4}]),choice('promise-everything','PROMISE EVERYTHING','PO +8, debt +9.',2,[{type:'resource',resource:'poHappiness',amount:8},{type:'resource',resource:'technicalDebt',amount:9}])]},
    { id:'personal-accidental-mistake',category:'personal',severity:'low',title:'WRONG CHAT WINDOW',copy:'A debugging rant landed in the project channel.',topics:['accidental-mistake'],baseWeight:.8,deduplicationKey:'personal-mistake',cooldownGameMs:55*60_000,eligibility:{any:[{type:'booster-count',booster:'cokeZero',minimumCount:1},{type:'need-stage',need:'sleepiness',minimumStage:1}]},documentedContexts:[context({boosterCounts:{coffee:0,cokeZero:1}})],choices:[choice('own-the-message','OWN IT','Apologize; PO +2, Focus -8%.',6,[{type:'resource',resource:'poHappiness',amount:2},{type:'focus',reduction:.08}]),choice('blame-autocomplete','BLAME AUTOCOMPLETE','Save time; PO -4.',0,[{type:'resource',resource:'poHappiness',amount:-4}])]}
]);

export const CONSEQUENCE_INTERRUPTION_PACK: readonly InterruptionDefinition[] = Object.freeze([
    { id:'consequence-coffee-crash',category:'consequence',severity:'high',title:'COFFEE CRASH',copy:'The borrowed energy has filed a repayment request.',topics:['coffee-crash'],baseWeight:1,deduplicationKey:'coffee-crash',cooldownGameMs:60*60_000,cause:{type:'current-state',predicate:{type:'booster-count',booster:'coffee',minimumCount:3}},eligibility:{type:'booster-count',booster:'coffee',minimumCount:3},documentedContexts:[context({boosterCounts:{coffee:3,cokeZero:0}})],choices:[choice('hydrate-and-reset','HYDRATE AND RESET','Spend 16m; Stamina +10, Focus -5%.',16,[{type:'resource',resource:'stamina',amount:10},{type:'focus',reduction:.05}]),choice('add-another-coffee','DOUBLE DOWN','Stamina +18 now; debt +7.',2,[{type:'resource',resource:'stamina',amount:18},{type:'resource',resource:'technicalDebt',amount:7}])]},
    { id:'consequence-scope-regression',category:'consequence',severity:'high',title:'TINY CHANGE, LARGE REGRESSION',copy:'The accepted shortcut has returned with a larger diff.',topics:['shortcut-regression'],baseWeight:1,cause:{type:'resolved-choice',eventId:'po-scope-request',choiceId:'accept-scope'},eligibility:{type:'resolved-choice',eventId:'po-scope-request',choiceId:'accept-scope'},documentedContexts:[context({resolvedEventIds:['po-scope-request'],resolvedChoices:[{eventId:'po-scope-request',choiceId:'accept-scope'}]})],choices:[choice('repair-scope-regression','REPAIR IT','Stability +12, progress -8%.',24,[{type:'resource',resource:'systemStability',amount:12},{type:'task-progress',reduction:8}]),choice('patch-scope-regression','PATCH AGAIN','Debt +11, stability -4.',7,[{type:'resource',resource:'technicalDebt',amount:11},{type:'resource',resource:'systemStability',amount:-4}])]},
    { id:'consequence-quick-approve',category:'consequence',severity:'medium',title:'APPROVAL SPEEDRUN PAYOFF',copy:'The quickly approved change now has several interpretations.',topics:['shortcut-regression'],baseWeight:.9,cause:{type:'resolved-choice',eventId:'team-review-request',choiceId:'quick-approve'},eligibility:{type:'resolved-choice',eventId:'team-review-request',choiceId:'quick-approve'},documentedContexts:[context({resolvedEventIds:['team-review-request'],resolvedChoices:[{eventId:'team-review-request',choiceId:'quick-approve'}]})],choices:[choice('review-for-real','REVIEW FOR REAL','Spend 20m; debt -7.',20,[{type:'resource',resource:'technicalDebt',amount:-7}]),choice('approve-the-approval','APPROVE THE APPROVAL','PO -3, stability -7.',1,[{type:'resource',resource:'poHappiness',amount:-3},{type:'resource',resource:'systemStability',amount:-7}])]},
    { id:'consequence-repeat-production',category:'consequence',severity:'critical',title:'INCIDENT REUNION TOUR',copy:'Production recognizes this failure mode and has notes.',topics:['repeated-incident'],baseWeight:1.1,cause:{type:'incident-history',incidentId:'production-errors',minimumCount:2},eligibility:{type:'incident-count',incidentId:'production-errors',minimumCount:2},documentedContexts:[context({incidentCounts:{'production-errors':2}})],choices:[choice('root-cause-session','ROOT CAUSE SESSION','Spend 30m; stability +18, debt -8.',30,[{type:'resource',resource:'systemStability',amount:18},{type:'resource',resource:'technicalDebt',amount:-8}]),choice('rename-the-alert','RENAME THE ALERT','It feels new; stability -10.',3,[{type:'resource',resource:'systemStability',amount:-10}])]},
    { id:'consequence-deploy-retry',category:'consequence',severity:'medium',title:'RETRY SUCCESS, SEMANTICALLY',copy:'The deployment completed. The definition of completed is under review.',topics:['follow-on-mistake'],baseWeight:.8,cause:{type:'concluded-consequence',consequenceId:'deploy-retry-risk'},eligibility:{type:'concluded-consequence',consequenceId:'deploy-retry-risk'},documentedContexts:[context({concludedConsequenceIds:['deploy-retry-risk']})],choices:[choice('verify-retry','VERIFY THE RETRY','Spend 14m; stability +9.',14,[{type:'resource',resource:'systemStability',amount:9}]),choice('celebrate-retry','DECLARE VICTORY','PO +4; 35% uncertain stability loss.',1,[{type:'probability',id:'victory-lap-risk',chance:.35,successEffects:[{type:'resource',resource:'systemStability',amount:-9}],failureEffects:[],successFeedback:'The victory lap found a regression.',failureFeedback:'Nothing else broke. Yet.'}],'uncertain')]}
]);

export function auditPersonalAndConsequenceCatalog(all:readonly InterruptionDefinition[],taskIds:readonly string[]):void{
    validateInterruptionCatalog(all,taskIds);
    if(all.length<25||all.length>30)throw new TypeError('MVP catalog must contain between 25 and 30 events.');
    if(all.filter(x=>x.category==='personal').length!==4||all.filter(x=>x.category==='consequence').length!==5)throw new TypeError('Catalog requires exactly four personal and five consequence events.');
    const topics=new Set(all.flatMap(x=>x.topics??[]));for(const topic of ['sleep-warning','bathroom-urgency','coffee-crash','shortcut-regression','repeated-incident','accidental-mistake'])if(!topics.has(topic))throw new TypeError(`Catalog is missing topic ${topic}.`);
    for(const item of all){if(!item.documentedContexts?.some(ctx=>matches(item,ctx))&&item.category!=='product-owner'&&item.category!=='teammate')throw new TypeError(`${item.id} is unreachable.`);const signatures=new Set(item.choices.map(c=>JSON.stringify([c.gameMinutes,c.effects])));if(signatures.size!==item.choices.length)throw new TypeError(`${item.id} choices must have distinct trade-offs.`);}
}
const matches=(item:InterruptionDefinition,ctx:InterruptionRunContext)=>{try{return !item.eligibility||Boolean(item.documentedContexts?.includes(ctx));}catch{return false;}};
