import { validateInterruptionCatalog,type InterruptionDefinition,type InterruptionRunContext } from '../domain/interruptions';
import { DEFAULT_DAY_STATE_CONFIG } from '../domain/DayState';
import { PRODUCTION_AND_TOOLING_PACK } from './productionToolingInterruptions';
import { CONSEQUENCE_INTERRUPTION_PACK, PERSONAL_INTERRUPTION_PACK } from './personalConsequenceInterruptions';
const context=(selectedTaskId:string|null=null,resolvedChoices:readonly {eventId:string;choiceId:string}[]=[]):InterruptionRunContext=>Object.freeze({selectedTaskId,completedTaskIds:Object.freeze([]),resolvedEventIds:Object.freeze(resolvedChoices.map(item=>item.eventId)),resolvedChoices:Object.freeze(resolvedChoices),resources:DEFAULT_DAY_STATE_CONFIG.initialResources});
const pressure={resource:'poHappiness',referenceValue:75,perPoint:-.012,minimum:.75,maximum:1.65} as const;
const esc=(copy:string,effects:InterruptionDefinition['choices'][number]['effects'],followUpIds?:readonly string[])=>[{delayGameMs:35*60_000,postponeGameMs:15*60_000,severity:'high' as const,copy,effects,followUpIds}];
const constructive=new Set(['pair-with-junior','fix-qa-now','review-carefully','debug-flake','own-public-followup']);
const teamChoiceIds=new Set(['pair-with-junior','send-pointer','fix-qa-now','document-qa','review-carefully','quick-approve','debug-flake','rerun-flake','own-public-followup','redirect-public-followup']);
const c=(id:string,label:string,description:string,gameMinutes:number,effects:InterruptionDefinition['choices'][number]['effects'])=>({id,label,description,gameMinutes,effects,...(teamChoiceIds.has(id)?{resultKarma:constructive.has(id)?'constructive' as const:'self-serving' as const}:{})});
export const PO_AND_TEAM_INTERRUPTION_PACK:readonly InterruptionDefinition[]=Object.freeze([
{id:'po-scope-request',category:'product-owner',severity:'medium',title:'TINY SCOPE CHANGE',topics:['tiny-scope-change'],baseWeight:1,selectionWeightModifier:pressure,copy:'Can search show one more field today?',eligibility:{type:'selected-task',taskId:'TASK-3178'},documentedContexts:[context('TASK-3178')],escalationStages:esc('Acceptance is blocked on the requested field.',[{type:'resource',resource:'poHappiness',amount:-7}]),choices:[c('accept-scope','ACCEPT CHANGE','PO +10, debt +6, Focus -15%.',18,[{type:'resource',resource:'poHappiness',amount:10},{type:'resource',resource:'technicalDebt',amount:6},{type:'focus',reduction:.15}]),c('negotiate-scope','NEGOTIATE','Protect scope; PO -3, debt -2.',25,[{type:'resource',resource:'poHappiness',amount:-3},{type:'resource',resource:'technicalDebt',amount:-2}])]},
{id:'po-status-login',category:'product-owner',severity:'low',title:'LOGIN STATUS',topics:['status-request'],baseWeight:1,selectionWeightModifier:pressure,copy:'What is the latest on the login error?',eligibility:{any:[{type:'selected-task',taskId:'BUG-4821'},{type:'completed-task',taskId:'BUG-4821'}]},documentedContexts:[context('BUG-4821')],escalationStages:esc('The status request moved into release chat.',[{type:'resource',resource:'poHappiness',amount:-5}]),choices:[c('send-login-status','SEND UPDATE','PO +6.',8,[{type:'resource',resource:'poHappiness',amount:6}]),c('stay-focused-login','STAY FOCUSED','No time cost; PO -4.',0,[{type:'resource',resource:'poHappiness',amount:-4}])]},
{id:'po-estimate-search',category:'product-owner',severity:'medium',title:'ESTIMATE PRESSURE',topics:['estimate-pressure'],baseWeight:.9,selectionWeightModifier:pressure,copy:'Can you commit to a search delivery time?',eligibility:{type:'selected-task',taskId:'TASK-3178'},documentedContexts:[context('TASK-3178')],escalationStages:esc('Planning flags the estimate as missing.',[{type:'resource',resource:'poHappiness',amount:-6}]),choices:[c('estimate-carefully','CHECK THEN ESTIMATE','PO +5, stability +2.',16,[{type:'resource',resource:'poHappiness',amount:5},{type:'resource',resource:'systemStability',amount:2}]),c('estimate-fast','QUICK ESTIMATE','PO +3, debt +4.',3,[{type:'resource',resource:'poHappiness',amount:3},{type:'resource',resource:'technicalDebt',amount:4}])]},
{id:'po-demo-request',category:'product-owner',severity:'medium',title:'SURPRISE DEMO',topics:['status-request'],baseWeight:.8,selectionWeightModifier:pressure,copy:'Can you demo today’s progress now?',escalationStages:esc('The demo slot passed without an update.',[{type:'resource',resource:'poHappiness',amount:-6}]),choices:[c('prepare-demo','PREPARE DEMO','PO +8, Focus -10%.',20,[{type:'resource',resource:'poHappiness',amount:8},{type:'focus',reduction:.1}]),c('send-notes','SEND NOTES','PO +3.',7,[{type:'resource',resource:'poHappiness',amount:3}])]},
{id:'po-priority-check',category:'product-owner',severity:'low',title:'PRIORITY CHECK',topics:['status-request'],baseWeight:1,selectionWeightModifier:pressure,copy:'Are you on the highest-value item?',escalationStages:esc('The priority check is now in stand-up notes.',[{type:'resource',resource:'poHappiness',amount:-4}]),choices:[c('explain-priority','EXPLAIN','PO +5.',10,[{type:'resource',resource:'poHappiness',amount:5}]),c('switch-for-optics','SWITCH FOR OPTICS','Focus -20%, PO +4.',4,[{type:'focus',reduction:.2},{type:'resource',resource:'poHappiness',amount:4}])]},
{id:'po-followup-scope',category:'product-owner',severity:'high',title:'SCOPE FOLLOW-UP',topics:['tiny-scope-change'],baseWeight:.7,selectionWeightModifier:pressure,copy:'Did the accepted search change make it in?',eligibility:{type:'resolved-choice',eventId:'po-scope-request',choiceId:'accept-scope'},documentedContexts:[context(null,[{eventId:'po-scope-request',choiceId:'accept-scope'}])],escalationStages:esc('The promised item is called out as missing.',[{type:'resource',resource:'poHappiness',amount:-9}]),choices:[c('finish-promise','FINISH PROMISE','PO +9, debt +3.',22,[{type:'resource',resource:'poHappiness',amount:9},{type:'resource',resource:'technicalDebt',amount:3}]),c('correct-expectation','RESET EXPECTATION','PO -5, debt -3.',12,[{type:'resource',resource:'poHappiness',amount:-5},{type:'resource',resource:'technicalDebt',amount:-3}])]},
{id:'teammate-help',category:'teammate',severity:'medium',title:'JUNIOR NEEDS HELP',topics:['junior-help'],baseWeight:1.2,copy:'A junior is stuck on the login failure.',eligibility:{type:'selected-task',taskId:'BUG-4821'},documentedContexts:[context('BUG-4821')],escalationStages:[{delayGameMs:30*60_000,postponeGameMs:12*60_000,severity:'high',copy:'The junior asks in the public engineering channel.',effects:[{type:'resource',resource:'poHappiness',amount:-3},{type:'focus',reduction:.12}],followUpIds:['team-public-followup']}],choices:[c('pair-with-junior','PAIR NOW','Stability +6, Focus -10%.',18,[{type:'resource',resource:'systemStability',amount:6},{type:'focus',reduction:.1}]),c('send-pointer','SEND POINTERS','Stability +2.',6,[{type:'resource',resource:'systemStability',amount:2}])]},
{id:'team-qa-finding',category:'teammate',severity:'high',title:'QA REGRESSION',topics:['qa-finding'],baseWeight:1.1,copy:'QA found duplicate payment retries.',escalationStages:esc('QA marked the regression release-blocking.',[{type:'resource',resource:'systemStability',amount:-8}]),choices:[c('fix-qa-now','FIX NOW','Stability +10, progress -5%.',24,[{type:'resource',resource:'systemStability',amount:10},{type:'task-progress',reduction:5}]),c('document-qa','DOCUMENT RISK','Stability -4, debt +5.',8,[{type:'resource',resource:'systemStability',amount:-4},{type:'resource',resource:'technicalDebt',amount:5}])]},
{id:'team-review-request',category:'teammate',severity:'medium',title:'REVIEW REQUEST',topics:['review-request'],baseWeight:1.2,copy:'A teammate needs a review before merging.',escalationStages:esc('The review now blocks the team.',[{type:'resource',resource:'systemStability',amount:-4}]),choices:[c('review-carefully','REVIEW CAREFULLY','Stability +6.',17,[{type:'resource',resource:'systemStability',amount:6}]),c('quick-approve','QUICK APPROVE','Debt +5.',4,[{type:'resource',resource:'technicalDebt',amount:5}])]},
{id:'team-test-flake',category:'teammate',severity:'low',title:'FLAKY TEST',topics:['qa-finding'],baseWeight:1,copy:'CI has a flaky test blocking a teammate.',escalationStages:esc('The flaky test delays the shared branch.',[{type:'resource',resource:'poHappiness',amount:-3}]),choices:[c('debug-flake','DEBUG FLAKE','Stability +5, debt -2.',15,[{type:'resource',resource:'systemStability',amount:5},{type:'resource',resource:'technicalDebt',amount:-2}]),c('rerun-flake','RERUN CI','Focus -8%.',5,[{type:'focus',reduction:.08}])]},
{id:'team-public-followup',category:'teammate',severity:'high',title:'PUBLIC CHANNEL FOLLOW-UP',topics:['junior-help'],baseWeight:0,copy:'The public channel asks who owns the blocked request.',eligibility:{type:'resolved-event',eventId:'teammate-help'},documentedContexts:[context(null,[{eventId:'teammate-help',choiceId:'send-pointer'}])],escalationStages:esc('Leadership records the unanswered public request.',[{type:'resource',resource:'poHappiness',amount:-5}]),choices:[c('own-public-followup','OWN IT','PO +3, stability +3.',14,[{type:'resource',resource:'poHappiness',amount:3},{type:'resource',resource:'systemStability',amount:3}]),c('redirect-public-followup','REDIRECT','PO -3, Focus -8%.',5,[{type:'resource',resource:'poHappiness',amount:-3},{type:'focus',reduction:.08}])]},
]);
export const PRODUCTION_INTERRUPTION:InterruptionDefinition=Object.freeze({id:'production-errors',category:'production',severity:'critical',title:'PRODUCTION INCIDENT',topics:['production'],baseWeight:1,debtWeightModifier:{perDebtPoint:.02,maximum:3},copy:'Checkout errors are climbing fast.',escalationStages:esc('Checkout failures affect active customers.',[{type:'resource',resource:'systemStability',amount:-12}]),choices:[c('hotfix','HOTFIX','Stability +18, debt +14.',25,[{type:'resource',resource:'systemStability',amount:18},{type:'resource',resource:'technicalDebt',amount:14}]),c('investigate','INVESTIGATE','Stamina -18, stability +24.',55,[{type:'resource',resource:'stamina',amount:-18},{type:'resource',resource:'systemStability',amount:24}]),c('rollback','ROLLBACK','Stability +12, progress -15%.',35,[{type:'resource',resource:'systemStability',amount:12},{type:'task-progress',reduction:15}]),c('ignore-incident','IGNORE','Stability -16, PO -8.',5,[{type:'resource',resource:'systemStability',amount:-16},{type:'resource',resource:'poHappiness',amount:-8}])]});
export const INTERRUPTION_CATALOG:readonly InterruptionDefinition[]=Object.freeze([...PO_AND_TEAM_INTERRUPTION_PACK,...PRODUCTION_AND_TOOLING_PACK,...PERSONAL_INTERRUPTION_PACK,...CONSEQUENCE_INTERRUPTION_PACK]);
export function auditPoAndTeamCatalog(taskIds:readonly string[]):void{validateInterruptionCatalog(INTERRUPTION_CATALOG,taskIds);const po=PO_AND_TEAM_INTERRUPTION_PACK.filter(item=>item.category==='product-owner');const team=PO_AND_TEAM_INTERRUPTION_PACK.filter(item=>item.category==='teammate');if(po.length!==6||team.length!==5)throw new TypeError('PO/team catalog must contain exactly six Product Owner and five teammate events.');const topics=new Set(PO_AND_TEAM_INTERRUPTION_PACK.flatMap(item=>item.topics??[]));for(const required of ['status-request','tiny-scope-change','estimate-pressure','junior-help','qa-finding','review-request'])if(!topics.has(required))throw new TypeError(`PO/team catalog is missing topic ${required}.`);for(const item of PO_AND_TEAM_INTERRUPTION_PACK){if(!item.escalationStages?.length)throw new TypeError(`${item.id} requires escalation copy.`);const signatures=new Set(item.choices.map(choice=>JSON.stringify([choice.gameMinutes,choice.effects])));if(signatures.size!==item.choices.length)throw new TypeError(`${item.id} choices must have distinct trade-offs.`);}}
