import { validateInterruptionCatalog,type Effect,type InterruptionChoiceDefinition,type InterruptionDefinition } from '../domain/interruptions';
import { DEFAULT_DAY_STATE_CONFIG } from '../domain/DayState';
const ctx=Object.freeze({selectedTaskId:null,completedTaskIds:Object.freeze([]),resolvedEventIds:Object.freeze([]),resolvedChoices:Object.freeze([]),resources:DEFAULT_DAY_STATE_CONFIG.initialResources});
const choice=(id:string,label:string,description:string,gameMinutes:number,effects:readonly Effect[],outcomeCertainty?:'certain'|'uncertain'):InterruptionChoiceDefinition=>({id,label,description,gameMinutes,effects,outcomeCertainty});
const disruption=(id:string,speedFactor:number,duration:number,startFeedback:string,endFeedback:string):Effect=>({type:'coding-disruption',id,speedFactor,durationGameMs:duration*60_000,startFeedback,endFeedback});
const stage=(delay:number,severity:'low'|'medium'|'high'|'critical',copy:string,effects:readonly Effect[]=[],debt=false)=>({delayGameMs:delay*60_000,postponeGameMs:10*60_000,severity,copy,effects,...(debt?{debtSeverityModifier:{perDebtPoint:.02,minimumRank:1,maximumRank:3}}:{})});
export const PRODUCTION_AND_TOOLING_PACK:readonly InterruptionDefinition[]=Object.freeze([
 {id:'production-errors',category:'production',incidentControl:'player-fixable',severity:'medium',title:'CHECKOUT ERROR RATE',copy:'Checkout errors have crossed the warning threshold.',topics:['production','escalating-errors'],baseWeight:1,debtWeightModifier:{perDebtPoint:.02,maximum:3},documentedContexts:[ctx],escalationStages:[stage(18,'high','Checkout is degraded and customers are retrying.',[{type:'resource',resource:'systemStability',amount:-8}],true),stage(16,'critical','Checkout is now unavailable.',[{type:'resource',resource:'systemStability',amount:-14}],true)],choices:[choice('rollback','ROLL BACK','Restore the last release; stability +14, progress -10%.',18,[{type:'resource',resource:'systemStability',amount:14},{type:'task-progress',reduction:10}]),choice('fast-fix','RISKY FAST FIX','Patch quickly; stability +8, debt +12.',8,[{type:'resource',resource:'systemStability',amount:8},{type:'resource',resource:'technicalDebt',amount:12}]),choice('investigate','INVESTIGATE','Trace the fault; stability +20, Stamina -14.',32,[{type:'resource',resource:'systemStability',amount:20},{type:'resource',resource:'stamina',amount:-14}]),choice('ignore-errors','IGNORE','Save time; stability -16.',0,[{type:'resource',resource:'systemStability',amount:-16}])]},
 {id:'production-latency',category:'production',incidentControl:'player-fixable',severity:'high',title:'API LATENCY',copy:'The API p95 has doubled.',topics:['production','latency'],baseWeight:.9,documentedContexts:[ctx],escalationStages:[stage(25,'critical','Requests are timing out.',[{type:'resource',resource:'systemStability',amount:-10}])],choices:[choice('latency-investigate','INVESTIGATE','Profile requests; stability +12.',25,[{type:'resource',resource:'systemStability',amount:12}]),choice('latency-fast-fix','FAST CACHE FIX','Reduce latency; debt +8.',10,[{type:'resource',resource:'technicalDebt',amount:8}])]},
 {id:'production-deploy',category:'production',incidentControl:'player-fixable',severity:'high',title:'FAILED DEPLOYMENT',copy:'The release failed during rollout.',topics:['production','failed-deployment'],baseWeight:1,documentedContexts:[ctx],choices:[choice('deploy-rollback','ROLL BACK','Restore service; stability +12.',16,[{type:'resource',resource:'systemStability',amount:12}]),choice('deploy-retry','RETRY DEPLOY','Retry now; 40% uncertain regression risk.',8,[{type:'probability',id:'deploy-retry-risk',chance:.4,successEffects:[{type:'resource',resource:'systemStability',amount:-10}],failureEffects:[{type:'resource',resource:'systemStability',amount:5}],successFeedback:'The retry regressed.',failureFeedback:'The retry completed.'}],'uncertain')]},
 {id:'production-database',category:'production',incidentControl:'player-fixable',severity:'high',title:'DATABASE PRESSURE',copy:'Connection pools are close to saturation.',topics:['production','database-pressure'],baseWeight:1,debtWeightModifier:{perDebtPoint:.01,maximum:2},documentedContexts:[ctx],choices:[choice('db-investigate','INVESTIGATE','Tune safely; stability +15, Stamina -10.',28,[{type:'resource',resource:'systemStability',amount:15},{type:'resource',resource:'stamina',amount:-10}]),choice('db-fast-fix','RAISE LIMIT','Gain headroom; debt +10.',7,[{type:'resource',resource:'technicalDebt',amount:10}])]},
 {id:'production-memory',category:'production',incidentControl:'player-fixable',severity:'medium',title:'MEMORY PRESSURE',copy:'Workers are approaching memory limits.',topics:['production','capacity'],baseWeight:.8,documentedContexts:[ctx],choices:[choice('memory-investigate','PROFILE','Find the leak; stability +10.',22,[{type:'resource',resource:'systemStability',amount:10}]),choice('memory-restart','RESTART WORKERS','Recover quickly; debt +5.',6,[{type:'resource',resource:'technicalDebt',amount:5}])]},
 {id:'production-certificate',category:'production',incidentControl:'player-fixable',severity:'medium',title:'CERTIFICATE WARNING',copy:'A production certificate expires soon.',topics:['production','maintenance'],baseWeight:.7,documentedContexts:[ctx],choices:[choice('cert-renew','RENEW PROPERLY','Renew and document; debt -4.',20,[{type:'resource',resource:'technicalDebt',amount:-4}]),choice('cert-fast-fix','TEMPORARY CERT','Buy time; debt +7.',5,[{type:'resource',resource:'technicalDebt',amount:7}])]},
 {id:'tooling-github',category:'tooling',incidentControl:'external',severity:'high',title:'GITHUB OUTAGE',copy:'GitHub is unavailable.',topics:['tooling','github-outage'],baseWeight:1,documentedContexts:[ctx],choices:[choice('github-wait','WAIT','Wait for recovery; coding blocked for 12m.',0,[disruption('github-wait-block',0,12,'GitHub outage blocks coding.','GitHub recovered.')]),choice('github-workaround','SWITCH WORKFLOW','Work locally at 60% speed for 18m.',4,[disruption('github-local-workaround',.6,18,'Local workflow slows coding.','Normal GitHub workflow restored.')])]},
 {id:'tooling-ci',category:'tooling',incidentControl:'external',severity:'medium',title:'CI PROVIDER OUTAGE',copy:'The CI provider cannot start jobs.',topics:['tooling','ci-outage'],baseWeight:1,documentedContexts:[ctx],choices:[choice('ci-retry','RETRY LATER','Retry later; 50% uncertain slowdown.',3,[{type:'probability',id:'ci-retry-risk',chance:.5,successEffects:[disruption('ci-retry-slow',.5,10,'CI retries slow coding.','CI retry load cleared.')],failureEffects:[],successFeedback:'CI remains congested.',failureFeedback:'CI accepted the build.'}],'uncertain'),choice('ci-ignore','IGNORE FOR NOW','Continue without CI; debt +6.',0,[{type:'resource',resource:'technicalDebt',amount:6}])]},
 {id:'tooling-ai',category:'tooling',incidentControl:'external',severity:'low',title:'AI ASSISTANT FAILURE',copy:'The coding assistant is returning errors.',topics:['tooling','ai-assistant-failure'],baseWeight:.9,documentedContexts:[ctx],choices:[choice('ai-wait','WAIT','Wait 8m for service recovery.',0,[disruption('ai-wait-block',0,8,'Assistant outage blocks the current workflow.','Assistant service recovered.')]),choice('ai-manual','WORK MANUALLY','Code manually at 70% speed for 15m.',0,[disruption('ai-manual-slow',.7,15,'Manual workflow slows coding.','Assistant workflow restored.')])]},
 {id:'tooling-local',category:'tooling',incidentControl:'player-fixable',severity:'medium',title:'LOCAL ENVIRONMENT BROKEN',copy:'The local build no longer starts.',topics:['tooling','local-environment'],baseWeight:1,documentedContexts:[ctx],choices:[choice('local-investigate','INVESTIGATE','Repair properly; coding blocked for 10m, debt -3.',12,[disruption('local-repair-block',0,10,'Environment repair blocks coding.','Local environment repaired.'),{type:'resource',resource:'technicalDebt',amount:-3}]),choice('local-retry','CLEAN AND RETRY','Retry quickly at 50% speed for 12m.',5,[disruption('local-retry-slow',.5,12,'Rebuild slows coding.','Local rebuild completed.')])]},
]);

export function auditProductionAndToolingCatalog(all:readonly InterruptionDefinition[],taskIds:readonly string[]):void{validateInterruptionCatalog(all,taskIds);const pack=all.filter(item=>item.category==='production'||item.category==='tooling');if(pack.filter(item=>item.category==='production').length!==6||pack.filter(item=>item.category==='tooling').length!==4)throw new TypeError('Catalog must contain exactly six production and four tooling events.');const topics=new Set(pack.flatMap(item=>item.topics??[]));for(const topic of ['escalating-errors','latency','failed-deployment','database-pressure','github-outage','ci-outage','ai-assistant-failure','local-environment'])if(!topics.has(topic))throw new TypeError(`Production/tooling catalog is missing topic ${topic}.`);for(const item of pack){if(!item.documentedContexts?.some(context=>context&&true))throw new TypeError(`${item.id} is unreachable.`);if(item.incidentControl==='external'&&item.choices.some(c=>/repair|fix|rollback|investigate/i.test(c.label)))throw new TypeError(`${item.id} external choices promise direct repair.`);const signatures=new Set(item.choices.map(c=>JSON.stringify([c.gameMinutes,c.effects])));if(signatures.size!==item.choices.length)throw new TypeError(`${item.id} choices must have distinct trade-offs.`);} }
