import { expect, test, type Page } from 'playwright/test';

type Snapshot={runId:number;scene:'workstation'|'results';clock:string;elapsedGameMs:number;paused:boolean;pauseReasons:string[];activeInterruptionIds:string[];resolvedInterruptionIds:string[];completedTaskIds:string[];codingRequested:boolean;guidanceVisible:boolean;terminal:boolean};
const snap=(page:Page)=>page.evaluate(()=>window.__WORKDAY_PLAYTEST__?.getSnapshot() as Snapshot|undefined);
async function point(page:Page,x:number,y:number,kind:'click'|'down'|'up'|'tap'='click'){const box=await page.locator('canvas').boundingBox();if(!box)throw new Error('milestone canvas: no rendered canvas');const px=box.x+x/1280*box.width,py=box.y+y/720*box.height;if(kind==='tap')await page.touchscreen.tap(px,py);else if(kind==='down')await page.mouse.move(px,py).then(()=>page.mouse.down());else if(kind==='up')await page.mouse.up();else await page.mouse.click(px,py);}
async function touchHold(page:Page,x:number,y:number){const box=await page.locator('canvas').boundingBox();if(!box)throw new Error('touch milestone: no canvas');const px=box.x+x/1280*box.width,py=box.y+y/720*box.height,cdp=await page.context().newCDPSession(page);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:px,y:py}]});await expect.poll(async()=>(await snap(page))?.codingRequested,{message:'touch coding armed'}).toBe(true);await page.waitForTimeout(250);await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await expect.poll(async()=>(await snap(page))?.codingRequested,{message:'touch coding released'}).toBe(false);await cdp.detach();}
async function start(page:Page){await page.goto('/?playtest=1');const canvas=page.locator('canvas');await expect(canvas,'milestone boot: canvas').toBeVisible();expect((await canvas.screenshot()).byteLength,'milestone usable rendered surface').toBeGreaterThan(10_000);await expect.poll(()=>snap(page),{message:'milestone boot: diagnostics'}).toBeTruthy();await point(page,640,555);await expect.poll(async()=>!(await snap(page))?.guidanceVisible,{message:'milestone guidance dismissed'}).toBeTruthy();return canvas;}

test.beforeEach(async({page})=>{const failures:string[]=[];page.on('pageerror',e=>failures.push(`pageerror: ${e.message}`));page.on('console',m=>{if(m.type()==='error')failures.push(`console: ${m.text()}`);});page.on('requestfailed',r=>{if(!/\.(?:mp3|ogg)(?:\?|$)/.test(r.url()))failures.push(`request: ${r.url()} ${r.failure()?.errorText}`);});(page as Page&{__failures?:string[]}).__failures=failures;});
test.afterEach(async({page},info)=>{const failures=(page as Page&{__failures?:string[]}).__failures??[];if(failures.length){await page.screenshot({path:info.outputPath('runtime-failure.png')});throw new Error(`runtime diagnostics:\n${failures.join('\n')}`);}});

test('accelerated complete workday reaches results and restarts fresh',async({page})=>{
 await start(page);const first=await snap(page);expect(first?.clock).toBe('09:00');
 await page.keyboard.down('Space');await expect.poll(async()=>((await snap(page))?.elapsedGameMs??0)>0,{message:'milestone time progression'}).toBeTruthy();
 let resolved=false,completed=false;const deadline=Date.now()+90_000;
 while(Date.now()<deadline){const state=await snap(page);if(!state)throw new Error('milestone diagnostics disappeared');if(state.scene==='results')break;
  if(state.pauseReasons.includes('task-decision')){await page.keyboard.up('Space');await point(page,640,337);await page.keyboard.down('Space');}
  else if(!resolved&&state.activeInterruptionIds.length){await page.keyboard.up('Space');await point(page,1100,260);await point(page,640,337);resolved=true;await page.keyboard.down('Space');}
  else if(!state.codingRequested&&!state.paused){await page.keyboard.up('Space');await page.keyboard.down('Space');}
  completed ||= state.completedTaskIds.length>0;await page.waitForTimeout(100);
 }
 await page.keyboard.up('Space');await expect.poll(async()=>(await snap(page))?.scene,{message:'milestone terminal results',timeout:10_000}).toBe('results');
 expect(resolved,'milestone interruption resolved through visible controls').toBeTruthy();expect(completed,'milestone task completion').toBeTruthy();await expect(page.locator('canvas')).toBeVisible();
 await page.keyboard.press('Enter');await expect.poll(async()=>(await snap(page))?.scene,{message:'milestone fresh restart'}).toBe('workstation');const fresh=await snap(page);expect(fresh?.elapsedGameMs).toBeLessThan(2*60_000);expect(fresh?.activeInterruptionIds).toEqual([]);expect(fresh?.completedTaskIds).toEqual([]);expect(fresh?.runId).toBeGreaterThan(first!.runId);
});

test('mouse and keyboard holds cancel across pause focus visibility orientation and resize',async({page})=>{await start(page);await point(page,632,444,'down');await expect.poll(async()=>(await snap(page))?.codingRequested).toBe(true);await page.setViewportSize({width:1024,height:640});await expect.poll(async()=>(await snap(page))?.codingRequested).toBe(false);await point(page,632,444,'up');await page.keyboard.down('Space');await expect.poll(async()=>(await snap(page))?.codingRequested).toBe(true);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await expect.poll(async()=>(await snap(page))?.codingRequested).toBe(false);await page.keyboard.up('Space');await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'));});await expect.poll(async()=>(await snap(page))?.pauseReasons.includes('browser-visibility')).toBe(true);const hiddenAt=(await snap(page))!.elapsedGameMs;await page.waitForTimeout(300);expect((await snap(page))!.elapsedGameMs).toBe(hiddenAt);await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'visible'});document.dispatchEvent(new Event('visibilitychange'));window.dispatchEvent(new Event('focus'));window.dispatchEvent(new Event('orientationchange'));});await expect.poll(async()=>(await snap(page))?.paused).toBe(false);await page.keyboard.press('KeyP');await expect.poll(async()=>(await snap(page))?.pauseReasons.includes('player-pause')).toBe(true);const before=(await snap(page))!.elapsedGameMs;await page.waitForTimeout(300);expect((await snap(page))!.elapsedGameMs).toBe(before);await page.keyboard.press('KeyP');await expect.poll(async()=>(await snap(page))?.paused).toBe(false);});

test.describe('minimum touch viewport',()=>{test.use({viewport:{width:390,height:700},hasTouch:true,isMobile:true});test('guidance and touch coding stay reachable after resize and mute remains operable',async({page})=>{await page.goto('/?playtest=1');await expect(page.locator('canvas')).toBeVisible();await point(page,640,555,'tap');await touchHold(page,632,444);await page.setViewportSize({width:700,height:390});await expect(page.locator('canvas')).toBeVisible();await point(page,1200,698,'tap');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('another-day-at-work:audio:v1')??'{}').muted)).toBe(true);await point(page,1200,698,'tap');expect(await page.evaluate(()=>JSON.parse(localStorage.getItem('another-day-at-work:audio:v1')??'{}').muted)).toBe(false);expect((await snap(page))?.guidanceVisible).toBe(false);});});

test('normal mode exposes no diagnostics',async({page})=>{await page.goto('/');await expect(page.locator('canvas')).toBeVisible();expect(await page.evaluate(()=>('__WORKDAY_PLAYTEST__' in window))).toBe(false);});
