import{expect,test,type Page}from'playwright/test';
type Snapshot={runId:number;scene:'workstation'|'results';clock:string;elapsedGameMs:number;paused:boolean;pauseReasons:string[];activeInterruptionIds:string[];completedTaskIds:string[];guidanceVisible:boolean;aiPhase:'available'|'planning'|'generating'|'review';aiProgress:number;cycleId:string|null;batchId:string|null;reviewAvailable:boolean};
const snap=(page:Page)=>page.evaluate(()=>window.__WORKDAY_PLAYTEST__?.getSnapshot() as Snapshot|undefined);
async function point(page:Page,x:number,y:number){const box=await page.locator('canvas').boundingBox();if(!box)throw new Error('No canvas');await page.mouse.click(box.x+x/1280*box.width,box.y+y/720*box.height);}
async function start(page:Page){await page.goto('/?playtest=1');await expect(page.locator('canvas')).toBeVisible();await expect.poll(()=>snap(page)).toBeTruthy();await point(page,640,555);await expect.poll(async()=>!(await snap(page))?.guidanceVisible).toBeTruthy();}
async function reachReview(page:Page){const end=Date.now()+30_000;while(Date.now()<end){const state=await snap(page);if(state?.aiPhase==='review')return;if(state?.activeInterruptionIds.length){await point(page,1100,260);await point(page,640,337);}await page.waitForTimeout(100);}throw new Error('AI review did not become ready');}
test('prompt generation presents one stable review and approval advances once',async({page})=>{await start(page);await page.keyboard.press('Space');await reachReview(page);const review=await snap(page);expect(review?.batchId).toBeTruthy();await page.evaluate(()=>window.dispatchEvent(new Event('blur')));expect((await snap(page))?.batchId).toBe(review?.batchId);await page.keyboard.press('Space');await expect.poll(async()=>(await snap(page))?.aiPhase).toBe('available');});
test('plan pauses through visibility and revision returns a higher-tier batch',async({page})=>{await start(page);await point(page,120,154);await page.keyboard.press('Digit2');await expect.poll(async()=>(await snap(page))?.aiPhase).toBe('planning');await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'));});const frozen=(await snap(page))!.aiProgress;await page.waitForTimeout(300);expect((await snap(page))!.aiProgress).toBe(frozen);await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'visible'});document.dispatchEvent(new Event('visibilitychange'));});await reachReview(page);const first=(await snap(page))!.batchId;await page.keyboard.press('KeyR');await expect.poll(async()=>(await snap(page))?.aiPhase).toBe('generating');await reachReview(page);expect((await snap(page))!.batchId).not.toBe(first);});
test.describe('minimum touch viewport',()=>{test.use({viewport:{width:390,height:700},hasTouch:true,isMobile:true});test('discrete mode controls remain reachable after resize',async({page})=>{await start(page);await expect(page.locator('canvas')).toHaveScreenshot('workstation-calm-minimum.png',{animations:'disabled',maxDiffPixelRatio:.02});await point(page,503,444);await expect.poll(async()=>['generating','review'].includes((await snap(page))?.aiPhase??'')).toBeTruthy();await page.setViewportSize({width:700,height:390});await expect(page.locator('canvas')).toBeVisible();});});
test('normal mode exposes no diagnostics',async({page})=>{await page.goto('/');await expect(page.locator('canvas')).toBeVisible();expect(await page.evaluate(()=>('__WORKDAY_PLAYTEST__' in window))).toBe(false);});
test('optional art failure falls back and critical failure blocks the hero scene',async({page})=>{await page.goto('/?playtest=1&assetFailure=presentation.foreground.frame');await expect.poll(()=>snap(page)).toBeTruthy();expect(await page.evaluate(()=>(window as any).__PRESENTATION_LOAD__?.ready)).toBe(true);await page.goto('/?playtest=1&assetFailure=presentation.background.office');await expect.poll(()=>page.evaluate(()=>(window as any).__PRESENTATION_LOAD__?.ready)).toBe(false);expect(await snap(page)).toBeUndefined();});
test('deterministic calm workstation visual baseline',async({page})=>{await start(page);await expect(page.locator('canvas')).toHaveScreenshot('workstation-calm.png',{animations:'disabled',maxDiffPixelRatio:.02});});
